// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "calc_pt_hw.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic calc_pt_hw::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic calc_pt_hw::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> calc_pt_hw::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<32> calc_pt_hw::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> calc_pt_hw::ap_const_lv1_1 = "1";
const sc_lv<64> calc_pt_hw::ap_const_lv64_3EB52E8BE9B8ACE4 = "11111010110101001011101000101111101001101110001010110011100100";
const sc_lv<32> calc_pt_hw::ap_const_lv32_E = "1110";
const sc_lv<15> calc_pt_hw::ap_const_lv15_4000 = "100000000000000";
const sc_lv<32> calc_pt_hw::ap_const_lv32_3F = "111111";
const sc_lv<32> calc_pt_hw::ap_const_lv32_34 = "110100";
const sc_lv<32> calc_pt_hw::ap_const_lv32_3E = "111110";
const sc_lv<63> calc_pt_hw::ap_const_lv63_0 = "000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<12> calc_pt_hw::ap_const_lv12_433 = "10000110011";
const sc_lv<54> calc_pt_hw::ap_const_lv54_0 = "000000000000000000000000000000000000000000000000000000";
const sc_lv<12> calc_pt_hw::ap_const_lv12_16 = "10110";
const sc_lv<12> calc_pt_hw::ap_const_lv12_FEA = "111111101010";
const sc_lv<12> calc_pt_hw::ap_const_lv12_36 = "110110";
const sc_lv<12> calc_pt_hw::ap_const_lv12_18 = "11000";
const sc_lv<24> calc_pt_hw::ap_const_lv24_FFFFFF = "111111111111111111111111";
const sc_lv<24> calc_pt_hw::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<32> calc_pt_hw::ap_const_lv32_A = "1010";
const sc_lv<32> calc_pt_hw::ap_const_lv32_17 = "10111";
const sc_lv<32> calc_pt_hw::ap_const_lv32_1A = "11010";
const sc_lv<10> calc_pt_hw::ap_const_lv10_0 = "0000000000";
const sc_lv<14> calc_pt_hw::ap_const_lv14_1 = "1";
const sc_lv<27> calc_pt_hw::ap_const_lv27_AF7 = "101011110111";

calc_pt_hw::calc_pt_hw(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_rinvToPt_fu_97 = new rinvToPt("grp_rinvToPt_fu_97");
    grp_rinvToPt_fu_97->ap_clk(ap_clk);
    grp_rinvToPt_fu_97->ap_rst(ap_rst);
    grp_rinvToPt_fu_97->ap_start(grp_rinvToPt_fu_97_ap_start);
    grp_rinvToPt_fu_97->ap_done(grp_rinvToPt_fu_97_ap_done);
    grp_rinvToPt_fu_97->ap_idle(grp_rinvToPt_fu_97_ap_idle);
    grp_rinvToPt_fu_97->ap_ready(grp_rinvToPt_fu_97_ap_ready);
    grp_rinvToPt_fu_97->data_V_read(grp_rinvToPt_fu_97_data_V_read);
    grp_rinvToPt_fu_97->ap_return(grp_rinvToPt_fu_97_ap_return);
    calc_pt_hw_dmul_6dEe_U4 = new calc_pt_hw_dmul_6dEe<1,10,64,64,64>("calc_pt_hw_dmul_6dEe_U4");
    calc_pt_hw_dmul_6dEe_U4->clk(ap_clk);
    calc_pt_hw_dmul_6dEe_U4->reset(ap_rst);
    calc_pt_hw_dmul_6dEe_U4->din0(tmp_s_reg_463);
    calc_pt_hw_dmul_6dEe_U4->din1(ap_var_for_const0);
    calc_pt_hw_dmul_6dEe_U4->ce(ap_var_for_const1);
    calc_pt_hw_dmul_6dEe_U4->dout(grp_fu_104_p2);
    calc_pt_hw_sitodpeOg_U5 = new calc_pt_hw_sitodpeOg<1,6,32,64>("calc_pt_hw_sitodpeOg_U5");
    calc_pt_hw_sitodpeOg_U5->clk(ap_clk);
    calc_pt_hw_sitodpeOg_U5->reset(ap_rst);
    calc_pt_hw_sitodpeOg_U5->din0(grp_fu_109_p0);
    calc_pt_hw_sitodpeOg_U5->ce(ap_var_for_const1);
    calc_pt_hw_sitodpeOg_U5->dout(grp_fu_109_p1);
    calc_pt_hw_mul_mufYi_U6 = new calc_pt_hw_mul_mufYi<1,3,13,14,27>("calc_pt_hw_mul_mufYi_U6");
    calc_pt_hw_mul_mufYi_U6->clk(ap_clk);
    calc_pt_hw_mul_mufYi_U6->reset(ap_rst);
    calc_pt_hw_mul_mufYi_U6->din0(grp_fu_444_p0);
    calc_pt_hw_mul_mufYi_U6->din1(absPt_V_reg_567);
    calc_pt_hw_mul_mufYi_U6->ce(ap_var_for_const1);
    calc_pt_hw_mul_mufYi_U6->dout(grp_fu_444_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_F2_fu_177_p2);
    sensitive << ( tmp_3_fu_163_p1 );

    SC_METHOD(thread_absInvRinv_V_1_fu_126_p3);
    sensitive << ( hwRinv_V );
    sensitive << ( tmp_fu_112_p3 );
    sensitive << ( absInvRinv_V_fu_120_p2 );

    SC_METHOD(thread_absInvRinv_V_fu_120_p2);
    sensitive << ( hwRinv_V );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter29 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_enable_reg_pp0_iter13 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( ap_enable_reg_pp0_iter15 );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_enable_reg_pp0_iter17 );
    sensitive << ( ap_enable_reg_pp0_iter18 );
    sensitive << ( ap_enable_reg_pp0_iter19 );
    sensitive << ( ap_enable_reg_pp0_iter20 );
    sensitive << ( ap_enable_reg_pp0_iter21 );
    sensitive << ( ap_enable_reg_pp0_iter22 );
    sensitive << ( ap_enable_reg_pp0_iter23 );
    sensitive << ( ap_enable_reg_pp0_iter24 );
    sensitive << ( ap_enable_reg_pp0_iter25 );
    sensitive << ( ap_enable_reg_pp0_iter26 );
    sensitive << ( ap_enable_reg_pp0_iter27 );
    sensitive << ( ap_enable_reg_pp0_iter28 );
    sensitive << ( ap_enable_reg_pp0_iter29 );

    SC_METHOD(thread_ap_pipeline_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_enable_reg_pp0_iter13 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( ap_enable_reg_pp0_iter15 );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_enable_reg_pp0_iter17 );
    sensitive << ( ap_enable_reg_pp0_iter18 );
    sensitive << ( ap_enable_reg_pp0_iter19 );
    sensitive << ( ap_enable_reg_pp0_iter20 );
    sensitive << ( ap_enable_reg_pp0_iter21 );
    sensitive << ( ap_enable_reg_pp0_iter22 );
    sensitive << ( ap_enable_reg_pp0_iter23 );
    sensitive << ( ap_enable_reg_pp0_iter24 );
    sensitive << ( ap_enable_reg_pp0_iter25 );
    sensitive << ( ap_enable_reg_pp0_iter26 );
    sensitive << ( ap_enable_reg_pp0_iter27 );
    sensitive << ( ap_enable_reg_pp0_iter28 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exp_tmp_V_fu_153_p4);
    sensitive << ( ireg_V_fu_138_p1 );

    SC_METHOD(thread_grp_fu_109_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( absInvRinv_V_1_reg_453 );

    SC_METHOD(thread_grp_fu_444_p0);
    sensitive << ( ap_enable_reg_pp0_iter26 );

    SC_METHOD(thread_grp_rinvToPt_fu_97_ap_start);
    sensitive << ( ap_reg_grp_rinvToPt_fu_97_ap_start );

    SC_METHOD(thread_grp_rinvToPt_fu_97_data_V_read);
    sensitive << ( ap_enable_reg_pp0_iter20 );
    sensitive << ( or_cond2_reg_562 );
    sensitive << ( newSel2_fu_374_p3 );

    SC_METHOD(thread_ireg_V_fu_138_p1);
    sensitive << ( v_assign_reg_468 );

    SC_METHOD(thread_man_V_1_fu_194_p2);
    sensitive << ( p_Result_s_fu_190_p1 );

    SC_METHOD(thread_man_V_2_fu_200_p3);
    sensitive << ( isneg_reg_473 );
    sensitive << ( p_Result_s_fu_190_p1 );
    sensitive << ( man_V_1_fu_194_p2 );

    SC_METHOD(thread_newSel1_fu_329_p3);
    sensitive << ( tmp_22_reg_519 );
    sensitive << ( sel_tmp8_fu_293_p2 );
    sensitive << ( tmp_24_fu_279_p1 );

    SC_METHOD(thread_newSel2_fu_374_p3);
    sensitive << ( or_cond_reg_552 );
    sensitive << ( newSel1_reg_557 );
    sensitive << ( newSel_fu_367_p3 );

    SC_METHOD(thread_newSel_fu_367_p3);
    sensitive << ( sel_tmp5_reg_547 );
    sensitive << ( p_1_fu_348_p3 );
    sensitive << ( tmp_25_fu_363_p1 );

    SC_METHOD(thread_or_cond1_fu_336_p2);
    sensitive << ( sel_tmp8_fu_293_p2 );
    sensitive << ( sel_tmp2_fu_288_p2 );

    SC_METHOD(thread_or_cond2_fu_342_p2);
    sensitive << ( or_cond_fu_323_p2 );
    sensitive << ( or_cond1_fu_336_p2 );

    SC_METHOD(thread_or_cond_fu_323_p2);
    sensitive << ( sel_tmp5_fu_318_p2 );
    sensitive << ( sel_tmp3_fu_307_p2 );

    SC_METHOD(thread_outPt_V);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter29 );
    sensitive << ( tmp_18_reg_592 );
    sensitive << ( tmp_26_fu_412_p3 );
    sensitive << ( tmp_19_fu_429_p3 );

    SC_METHOD(thread_outPt_V_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter29 );

    SC_METHOD(thread_p_1_fu_348_p3);
    sensitive << ( ap_pipeline_reg_pp0_iter19_isneg_reg_473 );

    SC_METHOD(thread_p_Result_s_fu_190_p1);
    sensitive << ( tmp_4_fu_183_p3 );

    SC_METHOD(thread_ret_V_1_fu_424_p2);
    sensitive << ( ret_V_reg_582 );

    SC_METHOD(thread_sel_tmp14_demorgan_fu_297_p2);
    sensitive << ( tmp_7_reg_503 );
    sensitive << ( sel_tmp6_demorgan_reg_531 );

    SC_METHOD(thread_sel_tmp1_fu_283_p2);
    sensitive << ( ap_pipeline_reg_pp0_iter18_tmp_5_reg_484 );

    SC_METHOD(thread_sel_tmp2_fu_288_p2);
    sensitive << ( tmp_1_reg_514 );
    sensitive << ( sel_tmp1_fu_283_p2 );

    SC_METHOD(thread_sel_tmp3_fu_307_p2);
    sensitive << ( tmp_10_fu_265_p2 );
    sensitive << ( sel_tmp_fu_301_p2 );

    SC_METHOD(thread_sel_tmp4_fu_313_p2);
    sensitive << ( tmp_6_reg_525 );

    SC_METHOD(thread_sel_tmp5_fu_318_p2);
    sensitive << ( sel_tmp7_reg_536 );
    sensitive << ( sel_tmp4_fu_313_p2 );

    SC_METHOD(thread_sel_tmp6_demorgan_fu_245_p2);
    sensitive << ( tmp_5_reg_484 );
    sensitive << ( tmp_1_fu_230_p2 );

    SC_METHOD(thread_sel_tmp6_fu_250_p2);
    sensitive << ( sel_tmp6_demorgan_fu_245_p2 );

    SC_METHOD(thread_sel_tmp7_fu_256_p2);
    sensitive << ( tmp_7_fu_207_p2 );
    sensitive << ( sel_tmp6_fu_250_p2 );

    SC_METHOD(thread_sel_tmp8_fu_293_p2);
    sensitive << ( tmp_6_reg_525 );
    sensitive << ( sel_tmp7_reg_536 );

    SC_METHOD(thread_sel_tmp_fu_301_p2);
    sensitive << ( sel_tmp14_demorgan_fu_297_p2 );

    SC_METHOD(thread_sh_amt_cast_fu_262_p1);
    sensitive << ( sh_amt_reg_508 );

    SC_METHOD(thread_sh_amt_fu_222_p3);
    sensitive << ( tmp_7_fu_207_p2 );
    sensitive << ( tmp_8_fu_212_p2 );
    sensitive << ( tmp_9_fu_217_p2 );

    SC_METHOD(thread_tmp_10_fu_265_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter19 );
    sensitive << ( sh_amt_reg_508 );

    SC_METHOD(thread_tmp_11_fu_270_p1);
    sensitive << ( sh_amt_cast_fu_262_p1 );

    SC_METHOD(thread_tmp_12_fu_274_p2);
    sensitive << ( man_V_2_reg_498 );
    sensitive << ( tmp_11_fu_270_p1 );

    SC_METHOD(thread_tmp_14_fu_355_p1);
    sensitive << ( ap_pipeline_reg_pp0_iter19_tmp_22_reg_519 );

    SC_METHOD(thread_tmp_15_fu_358_p2);
    sensitive << ( sh_amt_cast_reg_542 );
    sensitive << ( tmp_14_fu_355_p1 );

    SC_METHOD(thread_tmp_16_fu_141_p1);
    sensitive << ( ireg_V_fu_138_p1 );

    SC_METHOD(thread_tmp_17_fu_419_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter29 );
    sensitive << ( tmp_27_reg_587 );

    SC_METHOD(thread_tmp_19_fu_429_p3);
    sensitive << ( tmp_18_reg_592 );
    sensitive << ( tmp_17_fu_419_p2 );
    sensitive << ( ret_V_1_fu_424_p2 );

    SC_METHOD(thread_tmp_1_fu_230_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter18 );
    sensitive << ( F2_reg_490 );

    SC_METHOD(thread_tmp_20_fu_167_p1);
    sensitive << ( ireg_V_fu_138_p1 );

    SC_METHOD(thread_tmp_22_fu_235_p1);
    sensitive << ( man_V_2_fu_200_p3 );

    SC_METHOD(thread_tmp_24_fu_279_p1);
    sensitive << ( tmp_12_fu_274_p2 );

    SC_METHOD(thread_tmp_25_fu_363_p1);
    sensitive << ( tmp_15_fu_358_p2 );

    SC_METHOD(thread_tmp_26_fu_412_p3);
    sensitive << ( r_V_reg_577 );

    SC_METHOD(thread_tmp_27_fu_400_p1);
    sensitive << ( grp_fu_444_p2 );

    SC_METHOD(thread_tmp_3_fu_163_p1);
    sensitive << ( exp_tmp_V_fu_153_p4 );

    SC_METHOD(thread_tmp_4_fu_183_p3);
    sensitive << ( tmp_20_reg_479 );

    SC_METHOD(thread_tmp_5_fu_171_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter17 );
    sensitive << ( tmp_16_fu_141_p1 );

    SC_METHOD(thread_tmp_6_fu_239_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter18 );
    sensitive << ( sh_amt_fu_222_p3 );

    SC_METHOD(thread_tmp_7_fu_207_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter18 );
    sensitive << ( F2_reg_490 );

    SC_METHOD(thread_tmp_8_fu_212_p2);
    sensitive << ( F2_reg_490 );

    SC_METHOD(thread_tmp_9_fu_217_p2);
    sensitive << ( F2_reg_490 );

    SC_METHOD(thread_tmp_fu_112_p3);
    sensitive << ( hwRinv_V );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_pipeline_idle_pp0 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter11 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter12 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter13 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter14 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter15 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter16 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter17 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter18 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter19 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter20 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter21 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter22 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter23 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter24 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter25 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter26 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter27 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter28 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter29 = SC_LOGIC_0;
    ap_reg_grp_rinvToPt_fu_97_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "calc_pt_hw_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, hwRinv_V, "(port)hwRinv_V");
    sc_trace(mVcdFile, outPt_V, "(port)outPt_V");
    sc_trace(mVcdFile, outPt_V_ap_vld, "(port)outPt_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter11, "ap_enable_reg_pp0_iter11");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter12, "ap_enable_reg_pp0_iter12");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter13, "ap_enable_reg_pp0_iter13");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter14, "ap_enable_reg_pp0_iter14");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter15, "ap_enable_reg_pp0_iter15");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter16, "ap_enable_reg_pp0_iter16");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter17, "ap_enable_reg_pp0_iter17");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter18, "ap_enable_reg_pp0_iter18");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter19, "ap_enable_reg_pp0_iter19");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter20, "ap_enable_reg_pp0_iter20");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter21, "ap_enable_reg_pp0_iter21");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter22, "ap_enable_reg_pp0_iter22");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter23, "ap_enable_reg_pp0_iter23");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter24, "ap_enable_reg_pp0_iter24");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter25, "ap_enable_reg_pp0_iter25");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter26, "ap_enable_reg_pp0_iter26");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter27, "ap_enable_reg_pp0_iter27");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter28, "ap_enable_reg_pp0_iter28");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter29, "ap_enable_reg_pp0_iter29");
    sc_trace(mVcdFile, absInvRinv_V_1_fu_126_p3, "absInvRinv_V_1_fu_126_p3");
    sc_trace(mVcdFile, absInvRinv_V_1_reg_453, "absInvRinv_V_1_reg_453");
    sc_trace(mVcdFile, grp_fu_109_p1, "grp_fu_109_p1");
    sc_trace(mVcdFile, tmp_s_reg_463, "tmp_s_reg_463");
    sc_trace(mVcdFile, grp_fu_104_p2, "grp_fu_104_p2");
    sc_trace(mVcdFile, v_assign_reg_468, "v_assign_reg_468");
    sc_trace(mVcdFile, isneg_reg_473, "isneg_reg_473");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter18_isneg_reg_473, "ap_pipeline_reg_pp0_iter18_isneg_reg_473");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter19_isneg_reg_473, "ap_pipeline_reg_pp0_iter19_isneg_reg_473");
    sc_trace(mVcdFile, tmp_20_fu_167_p1, "tmp_20_fu_167_p1");
    sc_trace(mVcdFile, tmp_20_reg_479, "tmp_20_reg_479");
    sc_trace(mVcdFile, tmp_5_fu_171_p2, "tmp_5_fu_171_p2");
    sc_trace(mVcdFile, tmp_5_reg_484, "tmp_5_reg_484");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter18_tmp_5_reg_484, "ap_pipeline_reg_pp0_iter18_tmp_5_reg_484");
    sc_trace(mVcdFile, F2_fu_177_p2, "F2_fu_177_p2");
    sc_trace(mVcdFile, F2_reg_490, "F2_reg_490");
    sc_trace(mVcdFile, man_V_2_fu_200_p3, "man_V_2_fu_200_p3");
    sc_trace(mVcdFile, man_V_2_reg_498, "man_V_2_reg_498");
    sc_trace(mVcdFile, tmp_7_fu_207_p2, "tmp_7_fu_207_p2");
    sc_trace(mVcdFile, tmp_7_reg_503, "tmp_7_reg_503");
    sc_trace(mVcdFile, sh_amt_fu_222_p3, "sh_amt_fu_222_p3");
    sc_trace(mVcdFile, sh_amt_reg_508, "sh_amt_reg_508");
    sc_trace(mVcdFile, tmp_1_fu_230_p2, "tmp_1_fu_230_p2");
    sc_trace(mVcdFile, tmp_1_reg_514, "tmp_1_reg_514");
    sc_trace(mVcdFile, tmp_22_fu_235_p1, "tmp_22_fu_235_p1");
    sc_trace(mVcdFile, tmp_22_reg_519, "tmp_22_reg_519");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter19_tmp_22_reg_519, "ap_pipeline_reg_pp0_iter19_tmp_22_reg_519");
    sc_trace(mVcdFile, tmp_6_fu_239_p2, "tmp_6_fu_239_p2");
    sc_trace(mVcdFile, tmp_6_reg_525, "tmp_6_reg_525");
    sc_trace(mVcdFile, sel_tmp6_demorgan_fu_245_p2, "sel_tmp6_demorgan_fu_245_p2");
    sc_trace(mVcdFile, sel_tmp6_demorgan_reg_531, "sel_tmp6_demorgan_reg_531");
    sc_trace(mVcdFile, sel_tmp7_fu_256_p2, "sel_tmp7_fu_256_p2");
    sc_trace(mVcdFile, sel_tmp7_reg_536, "sel_tmp7_reg_536");
    sc_trace(mVcdFile, sh_amt_cast_fu_262_p1, "sh_amt_cast_fu_262_p1");
    sc_trace(mVcdFile, sh_amt_cast_reg_542, "sh_amt_cast_reg_542");
    sc_trace(mVcdFile, sel_tmp5_fu_318_p2, "sel_tmp5_fu_318_p2");
    sc_trace(mVcdFile, sel_tmp5_reg_547, "sel_tmp5_reg_547");
    sc_trace(mVcdFile, or_cond_fu_323_p2, "or_cond_fu_323_p2");
    sc_trace(mVcdFile, or_cond_reg_552, "or_cond_reg_552");
    sc_trace(mVcdFile, newSel1_fu_329_p3, "newSel1_fu_329_p3");
    sc_trace(mVcdFile, newSel1_reg_557, "newSel1_reg_557");
    sc_trace(mVcdFile, or_cond2_fu_342_p2, "or_cond2_fu_342_p2");
    sc_trace(mVcdFile, or_cond2_reg_562, "or_cond2_reg_562");
    sc_trace(mVcdFile, grp_rinvToPt_fu_97_ap_return, "grp_rinvToPt_fu_97_ap_return");
    sc_trace(mVcdFile, absPt_V_reg_567, "absPt_V_reg_567");
    sc_trace(mVcdFile, grp_fu_444_p2, "grp_fu_444_p2");
    sc_trace(mVcdFile, r_V_reg_577, "r_V_reg_577");
    sc_trace(mVcdFile, ret_V_reg_582, "ret_V_reg_582");
    sc_trace(mVcdFile, tmp_27_fu_400_p1, "tmp_27_fu_400_p1");
    sc_trace(mVcdFile, tmp_27_reg_587, "tmp_27_reg_587");
    sc_trace(mVcdFile, tmp_18_reg_592, "tmp_18_reg_592");
    sc_trace(mVcdFile, grp_rinvToPt_fu_97_ap_start, "grp_rinvToPt_fu_97_ap_start");
    sc_trace(mVcdFile, grp_rinvToPt_fu_97_ap_done, "grp_rinvToPt_fu_97_ap_done");
    sc_trace(mVcdFile, grp_rinvToPt_fu_97_ap_idle, "grp_rinvToPt_fu_97_ap_idle");
    sc_trace(mVcdFile, grp_rinvToPt_fu_97_ap_ready, "grp_rinvToPt_fu_97_ap_ready");
    sc_trace(mVcdFile, grp_rinvToPt_fu_97_data_V_read, "grp_rinvToPt_fu_97_data_V_read");
    sc_trace(mVcdFile, ap_reg_grp_rinvToPt_fu_97_ap_start, "ap_reg_grp_rinvToPt_fu_97_ap_start");
    sc_trace(mVcdFile, grp_fu_109_p0, "grp_fu_109_p0");
    sc_trace(mVcdFile, tmp_fu_112_p3, "tmp_fu_112_p3");
    sc_trace(mVcdFile, absInvRinv_V_fu_120_p2, "absInvRinv_V_fu_120_p2");
    sc_trace(mVcdFile, ireg_V_fu_138_p1, "ireg_V_fu_138_p1");
    sc_trace(mVcdFile, exp_tmp_V_fu_153_p4, "exp_tmp_V_fu_153_p4");
    sc_trace(mVcdFile, tmp_16_fu_141_p1, "tmp_16_fu_141_p1");
    sc_trace(mVcdFile, tmp_3_fu_163_p1, "tmp_3_fu_163_p1");
    sc_trace(mVcdFile, tmp_4_fu_183_p3, "tmp_4_fu_183_p3");
    sc_trace(mVcdFile, p_Result_s_fu_190_p1, "p_Result_s_fu_190_p1");
    sc_trace(mVcdFile, man_V_1_fu_194_p2, "man_V_1_fu_194_p2");
    sc_trace(mVcdFile, tmp_8_fu_212_p2, "tmp_8_fu_212_p2");
    sc_trace(mVcdFile, tmp_9_fu_217_p2, "tmp_9_fu_217_p2");
    sc_trace(mVcdFile, sel_tmp6_fu_250_p2, "sel_tmp6_fu_250_p2");
    sc_trace(mVcdFile, tmp_11_fu_270_p1, "tmp_11_fu_270_p1");
    sc_trace(mVcdFile, tmp_12_fu_274_p2, "tmp_12_fu_274_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_283_p2, "sel_tmp1_fu_283_p2");
    sc_trace(mVcdFile, sel_tmp14_demorgan_fu_297_p2, "sel_tmp14_demorgan_fu_297_p2");
    sc_trace(mVcdFile, tmp_10_fu_265_p2, "tmp_10_fu_265_p2");
    sc_trace(mVcdFile, sel_tmp_fu_301_p2, "sel_tmp_fu_301_p2");
    sc_trace(mVcdFile, sel_tmp4_fu_313_p2, "sel_tmp4_fu_313_p2");
    sc_trace(mVcdFile, sel_tmp3_fu_307_p2, "sel_tmp3_fu_307_p2");
    sc_trace(mVcdFile, sel_tmp8_fu_293_p2, "sel_tmp8_fu_293_p2");
    sc_trace(mVcdFile, tmp_24_fu_279_p1, "tmp_24_fu_279_p1");
    sc_trace(mVcdFile, sel_tmp2_fu_288_p2, "sel_tmp2_fu_288_p2");
    sc_trace(mVcdFile, or_cond1_fu_336_p2, "or_cond1_fu_336_p2");
    sc_trace(mVcdFile, tmp_14_fu_355_p1, "tmp_14_fu_355_p1");
    sc_trace(mVcdFile, tmp_15_fu_358_p2, "tmp_15_fu_358_p2");
    sc_trace(mVcdFile, p_1_fu_348_p3, "p_1_fu_348_p3");
    sc_trace(mVcdFile, tmp_25_fu_363_p1, "tmp_25_fu_363_p1");
    sc_trace(mVcdFile, newSel_fu_367_p3, "newSel_fu_367_p3");
    sc_trace(mVcdFile, newSel2_fu_374_p3, "newSel2_fu_374_p3");
    sc_trace(mVcdFile, tmp_17_fu_419_p2, "tmp_17_fu_419_p2");
    sc_trace(mVcdFile, ret_V_1_fu_424_p2, "ret_V_1_fu_424_p2");
    sc_trace(mVcdFile, tmp_26_fu_412_p3, "tmp_26_fu_412_p3");
    sc_trace(mVcdFile, tmp_19_fu_429_p3, "tmp_19_fu_429_p3");
    sc_trace(mVcdFile, grp_fu_444_p0, "grp_fu_444_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_pipeline_idle_pp0, "ap_pipeline_idle_pp0");
#endif

    }
    mHdltvinHandle.open("calc_pt_hw.hdltvin.dat");
    mHdltvoutHandle.open("calc_pt_hw.hdltvout.dat");
}

calc_pt_hw::~calc_pt_hw() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_rinvToPt_fu_97;
    delete calc_pt_hw_dmul_6dEe_U4;
    delete calc_pt_hw_sitodpeOg_U5;
    delete calc_pt_hw_mul_mufYi_U6;
}

void calc_pt_hw::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_logic_1;
}

void calc_pt_hw::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv64_3EB52E8BE9B8ACE4;
}

void calc_pt_hw::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
             !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter11 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter11 = ap_enable_reg_pp0_iter10.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter12 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter12 = ap_enable_reg_pp0_iter11.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter13 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter13 = ap_enable_reg_pp0_iter12.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter14 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter14 = ap_enable_reg_pp0_iter13.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter15 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter15 = ap_enable_reg_pp0_iter14.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter16 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter16 = ap_enable_reg_pp0_iter15.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter17 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter17 = ap_enable_reg_pp0_iter16.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter18 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter18 = ap_enable_reg_pp0_iter17.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter19 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter19 = ap_enable_reg_pp0_iter18.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter20 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter20 = ap_enable_reg_pp0_iter19.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter21 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter21 = ap_enable_reg_pp0_iter20.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter22 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter22 = ap_enable_reg_pp0_iter21.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter23 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter23 = ap_enable_reg_pp0_iter22.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter24 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter24 = ap_enable_reg_pp0_iter23.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter25 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter25 = ap_enable_reg_pp0_iter24.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter26 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter26 = ap_enable_reg_pp0_iter25.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter27 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter27 = ap_enable_reg_pp0_iter26.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter28 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter28 = ap_enable_reg_pp0_iter27.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter29 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter29 = ap_enable_reg_pp0_iter28.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_rinvToPt_fu_97_ap_start = ap_const_logic_0;
    } else {
        if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter19.read()))) {
            ap_reg_grp_rinvToPt_fu_97_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_rinvToPt_fu_97_ap_ready.read())) {
            ap_reg_grp_rinvToPt_fu_97_ap_start = ap_const_logic_0;
        }
    }
    if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        F2_reg_490 = F2_fu_177_p2.read();
        absPt_V_reg_567 = grp_rinvToPt_fu_97_ap_return.read();
        ap_pipeline_reg_pp0_iter18_isneg_reg_473 = isneg_reg_473.read();
        ap_pipeline_reg_pp0_iter18_tmp_5_reg_484 = tmp_5_reg_484.read();
        ap_pipeline_reg_pp0_iter19_isneg_reg_473 = ap_pipeline_reg_pp0_iter18_isneg_reg_473.read();
        ap_pipeline_reg_pp0_iter19_tmp_22_reg_519 = tmp_22_reg_519.read();
        isneg_reg_473 = ireg_V_fu_138_p1.read().range(63, 63);
        man_V_2_reg_498 = man_V_2_fu_200_p3.read();
        newSel1_reg_557 = newSel1_fu_329_p3.read();
        or_cond2_reg_562 = or_cond2_fu_342_p2.read();
        or_cond_reg_552 = or_cond_fu_323_p2.read();
        r_V_reg_577 = grp_fu_444_p2.read();
        ret_V_reg_582 = grp_fu_444_p2.read().range(23, 10);
        sel_tmp5_reg_547 = sel_tmp5_fu_318_p2.read();
        sel_tmp6_demorgan_reg_531 = sel_tmp6_demorgan_fu_245_p2.read();
        sel_tmp7_reg_536 = sel_tmp7_fu_256_p2.read();
        sh_amt_cast_reg_542 = sh_amt_cast_fu_262_p1.read();
        sh_amt_reg_508 = sh_amt_fu_222_p3.read();
        tmp_18_reg_592 = grp_fu_444_p2.read().range(23, 10);
        tmp_1_reg_514 = tmp_1_fu_230_p2.read();
        tmp_20_reg_479 = tmp_20_fu_167_p1.read();
        tmp_22_reg_519 = tmp_22_fu_235_p1.read();
        tmp_27_reg_587 = tmp_27_fu_400_p1.read();
        tmp_5_reg_484 = tmp_5_fu_171_p2.read();
        tmp_6_reg_525 = tmp_6_fu_239_p2.read();
        tmp_7_reg_503 = tmp_7_fu_207_p2.read();
        tmp_s_reg_463 = grp_fu_109_p1.read();
        v_assign_reg_468 = grp_fu_104_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        absInvRinv_V_1_reg_453 = absInvRinv_V_1_fu_126_p3.read();
    }
}

void calc_pt_hw::thread_F2_fu_177_p2() {
    F2_fu_177_p2 = (!ap_const_lv12_433.is_01() || !tmp_3_fu_163_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_433) - sc_biguint<12>(tmp_3_fu_163_p1.read()));
}

void calc_pt_hw::thread_absInvRinv_V_1_fu_126_p3() {
    absInvRinv_V_1_fu_126_p3 = (!tmp_fu_112_p3.read()[0].is_01())? sc_lv<15>(): ((tmp_fu_112_p3.read()[0].to_bool())? absInvRinv_V_fu_120_p2.read(): hwRinv_V.read());
}

void calc_pt_hw::thread_absInvRinv_V_fu_120_p2() {
    absInvRinv_V_fu_120_p2 = (hwRinv_V.read() ^ ap_const_lv15_4000);
}

void calc_pt_hw::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read().range(0, 0);
}

void calc_pt_hw::thread_ap_done() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter29.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void calc_pt_hw::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void calc_pt_hw::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter14.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter15.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter16.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter17.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter18.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter19.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter20.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter21.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter22.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter23.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter24.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter25.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter26.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter27.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter28.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter29.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void calc_pt_hw::thread_ap_pipeline_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter14.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter15.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter16.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter17.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter18.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter19.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter20.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter21.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter22.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter23.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter24.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter25.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter26.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter27.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter28.read()))) {
        ap_pipeline_idle_pp0 = ap_const_logic_1;
    } else {
        ap_pipeline_idle_pp0 = ap_const_logic_0;
    }
}

void calc_pt_hw::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void calc_pt_hw::thread_exp_tmp_V_fu_153_p4() {
    exp_tmp_V_fu_153_p4 = ireg_V_fu_138_p1.read().range(62, 52);
}

void calc_pt_hw::thread_grp_fu_109_p0() {
    grp_fu_109_p0 = esl_sext<32,15>(absInvRinv_V_1_reg_453.read());
}

void calc_pt_hw::thread_grp_fu_444_p0() {
    grp_fu_444_p0 =  (sc_lv<13>) (ap_const_lv27_AF7);
}

void calc_pt_hw::thread_grp_rinvToPt_fu_97_ap_start() {
    grp_rinvToPt_fu_97_ap_start = ap_reg_grp_rinvToPt_fu_97_ap_start.read();
}

void calc_pt_hw::thread_grp_rinvToPt_fu_97_data_V_read() {
    grp_rinvToPt_fu_97_data_V_read = (!or_cond2_reg_562.read()[0].is_01())? sc_lv<24>(): ((or_cond2_reg_562.read()[0].to_bool())? newSel2_fu_374_p3.read(): ap_const_lv24_0);
}

void calc_pt_hw::thread_ireg_V_fu_138_p1() {
    ireg_V_fu_138_p1 = v_assign_reg_468.read();
}

void calc_pt_hw::thread_man_V_1_fu_194_p2() {
    man_V_1_fu_194_p2 = (!ap_const_lv54_0.is_01() || !p_Result_s_fu_190_p1.read().is_01())? sc_lv<54>(): (sc_biguint<54>(ap_const_lv54_0) - sc_biguint<54>(p_Result_s_fu_190_p1.read()));
}

void calc_pt_hw::thread_man_V_2_fu_200_p3() {
    man_V_2_fu_200_p3 = (!isneg_reg_473.read()[0].is_01())? sc_lv<54>(): ((isneg_reg_473.read()[0].to_bool())? man_V_1_fu_194_p2.read(): p_Result_s_fu_190_p1.read());
}

void calc_pt_hw::thread_newSel1_fu_329_p3() {
    newSel1_fu_329_p3 = (!sel_tmp8_fu_293_p2.read()[0].is_01())? sc_lv<24>(): ((sel_tmp8_fu_293_p2.read()[0].to_bool())? tmp_24_fu_279_p1.read(): tmp_22_reg_519.read());
}

void calc_pt_hw::thread_newSel2_fu_374_p3() {
    newSel2_fu_374_p3 = (!or_cond_reg_552.read()[0].is_01())? sc_lv<24>(): ((or_cond_reg_552.read()[0].to_bool())? newSel_fu_367_p3.read(): newSel1_reg_557.read());
}

void calc_pt_hw::thread_newSel_fu_367_p3() {
    newSel_fu_367_p3 = (!sel_tmp5_reg_547.read()[0].is_01())? sc_lv<24>(): ((sel_tmp5_reg_547.read()[0].to_bool())? p_1_fu_348_p3.read(): tmp_25_fu_363_p1.read());
}

void calc_pt_hw::thread_or_cond1_fu_336_p2() {
    or_cond1_fu_336_p2 = (sel_tmp8_fu_293_p2.read() | sel_tmp2_fu_288_p2.read());
}

void calc_pt_hw::thread_or_cond2_fu_342_p2() {
    or_cond2_fu_342_p2 = (or_cond_fu_323_p2.read() | or_cond1_fu_336_p2.read());
}

void calc_pt_hw::thread_or_cond_fu_323_p2() {
    or_cond_fu_323_p2 = (sel_tmp5_fu_318_p2.read() | sel_tmp3_fu_307_p2.read());
}

void calc_pt_hw::thread_outPt_V() {
    outPt_V = (!tmp_26_fu_412_p3.read()[0].is_01())? sc_lv<14>(): ((tmp_26_fu_412_p3.read()[0].to_bool())? tmp_19_fu_429_p3.read(): tmp_18_reg_592.read());
}

void calc_pt_hw::thread_outPt_V_ap_vld() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter29.read()))) {
        outPt_V_ap_vld = ap_const_logic_1;
    } else {
        outPt_V_ap_vld = ap_const_logic_0;
    }
}

void calc_pt_hw::thread_p_1_fu_348_p3() {
    p_1_fu_348_p3 = (!ap_pipeline_reg_pp0_iter19_isneg_reg_473.read()[0].is_01())? sc_lv<24>(): ((ap_pipeline_reg_pp0_iter19_isneg_reg_473.read()[0].to_bool())? ap_const_lv24_FFFFFF: ap_const_lv24_0);
}

void calc_pt_hw::thread_p_Result_s_fu_190_p1() {
    p_Result_s_fu_190_p1 = esl_zext<54,53>(tmp_4_fu_183_p3.read());
}

void calc_pt_hw::thread_ret_V_1_fu_424_p2() {
    ret_V_1_fu_424_p2 = (!ap_const_lv14_1.is_01() || !ret_V_reg_582.read().is_01())? sc_lv<14>(): (sc_biguint<14>(ap_const_lv14_1) + sc_biguint<14>(ret_V_reg_582.read()));
}

void calc_pt_hw::thread_sel_tmp14_demorgan_fu_297_p2() {
    sel_tmp14_demorgan_fu_297_p2 = (sel_tmp6_demorgan_reg_531.read() | tmp_7_reg_503.read());
}

void calc_pt_hw::thread_sel_tmp1_fu_283_p2() {
    sel_tmp1_fu_283_p2 = (ap_pipeline_reg_pp0_iter18_tmp_5_reg_484.read() ^ ap_const_lv1_1);
}

void calc_pt_hw::thread_sel_tmp2_fu_288_p2() {
    sel_tmp2_fu_288_p2 = (tmp_1_reg_514.read() & sel_tmp1_fu_283_p2.read());
}

void calc_pt_hw::thread_sel_tmp3_fu_307_p2() {
    sel_tmp3_fu_307_p2 = (tmp_10_fu_265_p2.read() & sel_tmp_fu_301_p2.read());
}

void calc_pt_hw::thread_sel_tmp4_fu_313_p2() {
    sel_tmp4_fu_313_p2 = (tmp_6_reg_525.read() ^ ap_const_lv1_1);
}

void calc_pt_hw::thread_sel_tmp5_fu_318_p2() {
    sel_tmp5_fu_318_p2 = (sel_tmp7_reg_536.read() & sel_tmp4_fu_313_p2.read());
}

void calc_pt_hw::thread_sel_tmp6_demorgan_fu_245_p2() {
    sel_tmp6_demorgan_fu_245_p2 = (tmp_5_reg_484.read() | tmp_1_fu_230_p2.read());
}

void calc_pt_hw::thread_sel_tmp6_fu_250_p2() {
    sel_tmp6_fu_250_p2 = (sel_tmp6_demorgan_fu_245_p2.read() ^ ap_const_lv1_1);
}

void calc_pt_hw::thread_sel_tmp7_fu_256_p2() {
    sel_tmp7_fu_256_p2 = (tmp_7_fu_207_p2.read() & sel_tmp6_fu_250_p2.read());
}

void calc_pt_hw::thread_sel_tmp8_fu_293_p2() {
    sel_tmp8_fu_293_p2 = (sel_tmp7_reg_536.read() & tmp_6_reg_525.read());
}

void calc_pt_hw::thread_sel_tmp_fu_301_p2() {
    sel_tmp_fu_301_p2 = (sel_tmp14_demorgan_fu_297_p2.read() ^ ap_const_lv1_1);
}

void calc_pt_hw::thread_sh_amt_cast_fu_262_p1() {
    sh_amt_cast_fu_262_p1 = esl_sext<32,12>(sh_amt_reg_508.read());
}

void calc_pt_hw::thread_sh_amt_fu_222_p3() {
    sh_amt_fu_222_p3 = (!tmp_7_fu_207_p2.read()[0].is_01())? sc_lv<12>(): ((tmp_7_fu_207_p2.read()[0].to_bool())? tmp_8_fu_212_p2.read(): tmp_9_fu_217_p2.read());
}

void calc_pt_hw::thread_tmp_10_fu_265_p2() {
    tmp_10_fu_265_p2 = (!sh_amt_reg_508.read().is_01() || !ap_const_lv12_18.is_01())? sc_lv<1>(): (sc_biguint<12>(sh_amt_reg_508.read()) < sc_biguint<12>(ap_const_lv12_18));
}

void calc_pt_hw::thread_tmp_11_fu_270_p1() {
    tmp_11_fu_270_p1 = esl_zext<54,32>(sh_amt_cast_fu_262_p1.read());
}

void calc_pt_hw::thread_tmp_12_fu_274_p2() {
    tmp_12_fu_274_p2 = (!man_V_2_reg_498.read().is_01() || !tmp_11_fu_270_p1.read().is_01())? sc_lv<54>(): sc_bigint<54>(man_V_2_reg_498.read()) >> (unsigned short)tmp_11_fu_270_p1.read().to_uint();
}

void calc_pt_hw::thread_tmp_14_fu_355_p1() {
    tmp_14_fu_355_p1 = esl_sext<32,24>(ap_pipeline_reg_pp0_iter19_tmp_22_reg_519.read());
}

void calc_pt_hw::thread_tmp_15_fu_358_p2() {
    tmp_15_fu_358_p2 = (!sh_amt_cast_reg_542.read().is_01())? sc_lv<32>(): tmp_14_fu_355_p1.read() << (unsigned short)sh_amt_cast_reg_542.read().to_uint();
}

void calc_pt_hw::thread_tmp_16_fu_141_p1() {
    tmp_16_fu_141_p1 = ireg_V_fu_138_p1.read().range(63-1, 0);
}

void calc_pt_hw::thread_tmp_17_fu_419_p2() {
    tmp_17_fu_419_p2 = (!tmp_27_reg_587.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_27_reg_587.read() == ap_const_lv10_0);
}

void calc_pt_hw::thread_tmp_19_fu_429_p3() {
    tmp_19_fu_429_p3 = (!tmp_17_fu_419_p2.read()[0].is_01())? sc_lv<14>(): ((tmp_17_fu_419_p2.read()[0].to_bool())? tmp_18_reg_592.read(): ret_V_1_fu_424_p2.read());
}

void calc_pt_hw::thread_tmp_1_fu_230_p2() {
    tmp_1_fu_230_p2 = (!F2_reg_490.read().is_01() || !ap_const_lv12_16.is_01())? sc_lv<1>(): sc_lv<1>(F2_reg_490.read() == ap_const_lv12_16);
}

void calc_pt_hw::thread_tmp_20_fu_167_p1() {
    tmp_20_fu_167_p1 = ireg_V_fu_138_p1.read().range(52-1, 0);
}

void calc_pt_hw::thread_tmp_22_fu_235_p1() {
    tmp_22_fu_235_p1 = man_V_2_fu_200_p3.read().range(24-1, 0);
}

void calc_pt_hw::thread_tmp_24_fu_279_p1() {
    tmp_24_fu_279_p1 = tmp_12_fu_274_p2.read().range(24-1, 0);
}

void calc_pt_hw::thread_tmp_25_fu_363_p1() {
    tmp_25_fu_363_p1 = tmp_15_fu_358_p2.read().range(24-1, 0);
}

void calc_pt_hw::thread_tmp_26_fu_412_p3() {
    tmp_26_fu_412_p3 = r_V_reg_577.read().range(26, 26);
}

void calc_pt_hw::thread_tmp_27_fu_400_p1() {
    tmp_27_fu_400_p1 = grp_fu_444_p2.read().range(10-1, 0);
}

void calc_pt_hw::thread_tmp_3_fu_163_p1() {
    tmp_3_fu_163_p1 = esl_zext<12,11>(exp_tmp_V_fu_153_p4.read());
}

void calc_pt_hw::thread_tmp_4_fu_183_p3() {
    tmp_4_fu_183_p3 = esl_concat<1,52>(ap_const_lv1_1, tmp_20_reg_479.read());
}

void calc_pt_hw::thread_tmp_5_fu_171_p2() {
    tmp_5_fu_171_p2 = (!tmp_16_fu_141_p1.read().is_01() || !ap_const_lv63_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_16_fu_141_p1.read() == ap_const_lv63_0);
}

void calc_pt_hw::thread_tmp_6_fu_239_p2() {
    tmp_6_fu_239_p2 = (!sh_amt_fu_222_p3.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_biguint<12>(sh_amt_fu_222_p3.read()) < sc_biguint<12>(ap_const_lv12_36));
}

void calc_pt_hw::thread_tmp_7_fu_207_p2() {
    tmp_7_fu_207_p2 = (!F2_reg_490.read().is_01() || !ap_const_lv12_16.is_01())? sc_lv<1>(): (sc_bigint<12>(F2_reg_490.read()) > sc_bigint<12>(ap_const_lv12_16));
}

void calc_pt_hw::thread_tmp_8_fu_212_p2() {
    tmp_8_fu_212_p2 = (!ap_const_lv12_FEA.is_01() || !F2_reg_490.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_FEA) + sc_biguint<12>(F2_reg_490.read()));
}

void calc_pt_hw::thread_tmp_9_fu_217_p2() {
    tmp_9_fu_217_p2 = (!ap_const_lv12_16.is_01() || !F2_reg_490.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_16) - sc_biguint<12>(F2_reg_490.read()));
}

void calc_pt_hw::thread_tmp_fu_112_p3() {
    tmp_fu_112_p3 = hwRinv_V.read().range(14, 14);
}

void calc_pt_hw::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

void calc_pt_hw::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"hwRinv_V\" :  \"" << hwRinv_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outPt_V\" :  \"" << outPt_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outPt_V_ap_vld\" :  \"" << outPt_V_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

