// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "match_hw.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic match_hw::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic match_hw::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> match_hw::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<32> match_hw::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> match_hw::ap_const_lv1_1 = "1";
const sc_lv<1> match_hw::ap_const_lv1_0 = "0";
const sc_lv<14> match_hw::ap_const_lv14_0 = "00000000000000";
const sc_lv<9> match_hw::ap_const_lv9_0 = "000000000";
const sc_lv<10> match_hw::ap_const_lv10_0 = "0000000000";
const sc_lv<3> match_hw::ap_const_lv3_0 = "000";
const sc_lv<64> match_hw::ap_const_lv64_3F600000972ECF2E = "11111101100000000000000000000010010111001011101100111100101110";
const sc_lv<64> match_hw::ap_const_lv64_3F8645A1CAC08312 = "11111110000110010001011010000111001010110000001000001100010010";
const sc_lv<32> match_hw::ap_const_lv32_8 = "1000";
const sc_lv<2> match_hw::ap_const_lv2_1 = "1";
const sc_lv<32> match_hw::ap_const_lv32_3F = "111111";
const sc_lv<32> match_hw::ap_const_lv32_34 = "110100";
const sc_lv<32> match_hw::ap_const_lv32_3E = "111110";
const sc_lv<63> match_hw::ap_const_lv63_0 = "000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<12> match_hw::ap_const_lv12_433 = "10000110011";
const sc_lv<54> match_hw::ap_const_lv54_0 = "000000000000000000000000000000000000000000000000000000";
const sc_lv<12> match_hw::ap_const_lv12_A = "1010";
const sc_lv<12> match_hw::ap_const_lv12_FF6 = "111111110110";
const sc_lv<12> match_hw::ap_const_lv12_36 = "110110";
const sc_lv<12> match_hw::ap_const_lv12_6 = "110";
const sc_lv<12> match_hw::ap_const_lv12_FFA = "111111111010";
const sc_lv<12> match_hw::ap_const_lv12_E = "1110";
const sc_lv<14> match_hw::ap_const_lv14_3FFF = "11111111111111";
const sc_lv<10> match_hw::ap_const_lv10_3FF = "1111111111";
const sc_lv<4> match_hw::ap_const_lv4_0 = "0000";
const sc_lv<32> match_hw::ap_const_lv32_A = "1010";
const sc_lv<32> match_hw::ap_const_lv32_D = "1101";
const sc_lv<32> match_hw::ap_const_lv32_4 = "100";
const sc_lv<32> match_hw::ap_const_lv32_9 = "1001";
const sc_lv<6> match_hw::ap_const_lv6_0 = "000000";
const sc_lv<4> match_hw::ap_const_lv4_1 = "1";
const bool match_hw::ap_const_boolean_1 = true;

match_hw::match_hw(sc_module_name name) : sc_module(name), mVcdFile(0) {
    match_hw_dmul_64nbkb_U1 = new match_hw_dmul_64nbkb<1,10,64,64,64>("match_hw_dmul_64nbkb_U1");
    match_hw_dmul_64nbkb_U1->clk(ap_clk);
    match_hw_dmul_64nbkb_U1->reset(ap_rst);
    match_hw_dmul_64nbkb_U1->din0(tmp_reg_987);
    match_hw_dmul_64nbkb_U1->din1(ap_var_for_const0);
    match_hw_dmul_64nbkb_U1->ce(ap_var_for_const1);
    match_hw_dmul_64nbkb_U1->dout(grp_fu_257_p2);
    match_hw_dmul_64nbkb_U2 = new match_hw_dmul_64nbkb<1,10,64,64,64>("match_hw_dmul_64nbkb_U2");
    match_hw_dmul_64nbkb_U2->clk(ap_clk);
    match_hw_dmul_64nbkb_U2->reset(ap_rst);
    match_hw_dmul_64nbkb_U2->din0(tmp_20_reg_992);
    match_hw_dmul_64nbkb_U2->din1(ap_var_for_const2);
    match_hw_dmul_64nbkb_U2->ce(ap_var_for_const1);
    match_hw_dmul_64nbkb_U2->dout(grp_fu_262_p2);
    match_hw_sitodp_3cud_U3 = new match_hw_sitodp_3cud<1,6,32,64>("match_hw_sitodp_3cud_U3");
    match_hw_sitodp_3cud_U3->clk(ap_clk);
    match_hw_sitodp_3cud_U3->reset(ap_rst);
    match_hw_sitodp_3cud_U3->din0(grp_fu_267_p0);
    match_hw_sitodp_3cud_U3->ce(ap_var_for_const1);
    match_hw_sitodp_3cud_U3->dout(grp_fu_267_p1);
    match_hw_sitodp_3cud_U4 = new match_hw_sitodp_3cud<1,6,32,64>("match_hw_sitodp_3cud_U4");
    match_hw_sitodp_3cud_U4->clk(ap_clk);
    match_hw_sitodp_3cud_U4->reset(ap_rst);
    match_hw_sitodp_3cud_U4->din0(grp_fu_270_p0);
    match_hw_sitodp_3cud_U4->ce(ap_var_for_const1);
    match_hw_sitodp_3cud_U4->dout(grp_fu_270_p1);
    match_hw_mul_10s_dEe_U5 = new match_hw_mul_10s_dEe<1,3,10,2,12>("match_hw_mul_10s_dEe_U5");
    match_hw_mul_10s_dEe_U5->clk(ap_clk);
    match_hw_mul_10s_dEe_U5->reset(ap_rst);
    match_hw_mul_10s_dEe_U5->din0(tmp_54_i_reg_957);
    match_hw_mul_10s_dEe_U5->din1(tmp_17_fu_318_p2);
    match_hw_mul_10s_dEe_U5->ce(ap_var_for_const1);
    match_hw_mul_10s_dEe_U5->dout(grp_fu_331_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_F2_1_fu_429_p2);
    sensitive << ( tmp_21_fu_415_p1 );

    SC_METHOD(thread_F2_fu_384_p2);
    sensitive << ( tmp_6_fu_370_p1 );

    SC_METHOD(thread_abs_fu_929_p3);
    sensitive << ( p_1_reg_1205 );
    sensitive << ( abscond_fu_924_p2 );
    sensitive << ( neg_fu_919_p2 );

    SC_METHOD(thread_abscond_fu_924_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter25 );
    sensitive << ( p_1_reg_1205 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_condition_329);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter25 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter25 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_enable_reg_pp0_iter13 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( ap_enable_reg_pp0_iter15 );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_enable_reg_pp0_iter17 );
    sensitive << ( ap_enable_reg_pp0_iter18 );
    sensitive << ( ap_enable_reg_pp0_iter19 );
    sensitive << ( ap_enable_reg_pp0_iter20 );
    sensitive << ( ap_enable_reg_pp0_iter21 );
    sensitive << ( ap_enable_reg_pp0_iter22 );
    sensitive << ( ap_enable_reg_pp0_iter23 );
    sensitive << ( ap_enable_reg_pp0_iter24 );
    sensitive << ( ap_enable_reg_pp0_iter25 );

    SC_METHOD(thread_ap_pipeline_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter9 );
    sensitive << ( ap_enable_reg_pp0_iter10 );
    sensitive << ( ap_enable_reg_pp0_iter11 );
    sensitive << ( ap_enable_reg_pp0_iter12 );
    sensitive << ( ap_enable_reg_pp0_iter13 );
    sensitive << ( ap_enable_reg_pp0_iter14 );
    sensitive << ( ap_enable_reg_pp0_iter15 );
    sensitive << ( ap_enable_reg_pp0_iter16 );
    sensitive << ( ap_enable_reg_pp0_iter17 );
    sensitive << ( ap_enable_reg_pp0_iter18 );
    sensitive << ( ap_enable_reg_pp0_iter19 );
    sensitive << ( ap_enable_reg_pp0_iter20 );
    sensitive << ( ap_enable_reg_pp0_iter21 );
    sensitive << ( ap_enable_reg_pp0_iter22 );
    sensitive << ( ap_enable_reg_pp0_iter23 );
    sensitive << ( ap_enable_reg_pp0_iter24 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exp_tmp_V_1_fu_405_p4);
    sensitive << ( ireg_V_1_fu_390_p1 );

    SC_METHOD(thread_exp_tmp_V_fu_360_p4);
    sensitive << ( ireg_V_fu_345_p1 );

    SC_METHOD(thread_grp_fu_267_p0);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_pipeline_reg_pp0_iter3_inTrack_hwEta_V_read_reg_942 );

    SC_METHOD(thread_grp_fu_270_p0);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_18_reg_972 );

    SC_METHOD(thread_ireg_V_1_fu_390_p1);
    sensitive << ( v_assign_1_reg_1002 );

    SC_METHOD(thread_ireg_V_fu_345_p1);
    sensitive << ( v_assign_reg_997 );

    SC_METHOD(thread_man_V_1_fu_446_p2);
    sensitive << ( p_Result_s_fu_442_p1 );

    SC_METHOD(thread_man_V_2_fu_452_p3);
    sensitive << ( isneg_reg_1007 );
    sensitive << ( p_Result_s_fu_442_p1 );
    sensitive << ( man_V_1_fu_446_p2 );

    SC_METHOD(thread_man_V_4_fu_525_p2);
    sensitive << ( p_Result_1_fu_521_p1 );

    SC_METHOD(thread_man_V_5_fu_531_p3);
    sensitive << ( isneg_1_reg_1032 );
    sensitive << ( p_Result_1_fu_521_p1 );
    sensitive << ( man_V_4_fu_525_p2 );

    SC_METHOD(thread_neg_fu_919_p2);
    sensitive << ( p_1_reg_1205 );

    SC_METHOD(thread_newSel1_fu_660_p3);
    sensitive << ( tmp_16_reg_1078 );
    sensitive << ( sel_tmp8_fu_624_p2 );
    sensitive << ( tmp_28_fu_610_p1 );

    SC_METHOD(thread_newSel2_fu_791_p3);
    sensitive << ( or_cond_reg_1155 );
    sensitive << ( newSel1_reg_1160 );
    sensitive << ( newSel_fu_784_p3 );

    SC_METHOD(thread_newSel4_fu_816_p3);
    sensitive << ( sel_tmp17_reg_1175 );
    sensitive << ( p_3_fu_797_p3 );
    sensitive << ( tmp_48_fu_812_p1 );

    SC_METHOD(thread_newSel5_fu_746_p3);
    sensitive << ( tmp_46_reg_1122 );
    sensitive << ( sel_tmp13_fu_710_p2 );
    sensitive << ( tmp_47_fu_696_p1 );

    SC_METHOD(thread_newSel6_fu_823_p3);
    sensitive << ( or_cond3_reg_1180 );
    sensitive << ( newSel5_reg_1185 );
    sensitive << ( newSel4_fu_816_p3 );

    SC_METHOD(thread_newSel_fu_784_p3);
    sensitive << ( sel_tmp5_reg_1150 );
    sensitive << ( p_2_fu_765_p3 );
    sensitive << ( tmp_33_fu_780_p1 );

    SC_METHOD(thread_or_cond1_fu_667_p2);
    sensitive << ( sel_tmp8_fu_624_p2 );
    sensitive << ( sel_tmp2_fu_619_p2 );

    SC_METHOD(thread_or_cond2_fu_673_p2);
    sensitive << ( or_cond_fu_654_p2 );
    sensitive << ( or_cond1_fu_667_p2 );

    SC_METHOD(thread_or_cond3_fu_740_p2);
    sensitive << ( sel_tmp17_fu_735_p2 );
    sensitive << ( sel_tmp15_fu_724_p2 );

    SC_METHOD(thread_or_cond4_fu_753_p2);
    sensitive << ( sel_tmp13_fu_710_p2 );
    sensitive << ( sel_tmp10_fu_705_p2 );

    SC_METHOD(thread_or_cond5_fu_759_p2);
    sensitive << ( or_cond3_fu_740_p2 );
    sensitive << ( or_cond4_fu_753_p2 );

    SC_METHOD(thread_or_cond_fu_654_p2);
    sensitive << ( sel_tmp5_fu_649_p2 );
    sensitive << ( sel_tmp3_fu_638_p2 );

    SC_METHOD(thread_outTrackMuon_hwBX_V);
    sensitive << ( inTrack_hwBX_V );
    sensitive << ( tmp_41_fu_936_p2 );
    sensitive << ( ap_condition_329 );

    SC_METHOD(thread_outTrackMuon_hwBX_V_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter25 );
    sensitive << ( tmp_41_fu_936_p2 );

    SC_METHOD(thread_outTrackMuon_hwEta_V);
    sensitive << ( ap_pipeline_reg_pp0_iter24_inMuon_hwEta_V_read_reg_947 );
    sensitive << ( tmp_41_fu_936_p2 );
    sensitive << ( ap_condition_329 );

    SC_METHOD(thread_outTrackMuon_hwEta_V_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter25 );
    sensitive << ( tmp_41_fu_936_p2 );

    SC_METHOD(thread_outTrackMuon_hwPhi_V);
    sensitive << ( inMuon_hwPhi_V );
    sensitive << ( tmp_41_fu_936_p2 );
    sensitive << ( ap_condition_329 );

    SC_METHOD(thread_outTrackMuon_hwPhi_V_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter25 );
    sensitive << ( tmp_41_fu_936_p2 );

    SC_METHOD(thread_outTrackMuon_hwPt_V);
    sensitive << ( inTrack_hwPt_V );
    sensitive << ( tmp_41_fu_936_p2 );
    sensitive << ( ap_condition_329 );

    SC_METHOD(thread_outTrackMuon_hwPt_V_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter25 );
    sensitive << ( tmp_41_fu_936_p2 );

    SC_METHOD(thread_outTrackMuon_hwQ_V);
    sensitive << ( inTrack_hwQ_V );
    sensitive << ( tmp_41_fu_936_p2 );
    sensitive << ( ap_condition_329 );

    SC_METHOD(thread_outTrackMuon_hwQ_V_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter25 );
    sensitive << ( tmp_41_fu_936_p2 );

    SC_METHOD(thread_outTrackMuon_hwValid_V);
    sensitive << ( tmp_41_fu_936_p2 );
    sensitive << ( ap_condition_329 );

    SC_METHOD(thread_outTrackMuon_hwValid_V_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter25 );
    sensitive << ( tmp_41_fu_936_p2 );

    SC_METHOD(thread_p_1_fu_911_p3);
    sensitive << ( ret_V_fu_863_p4 );
    sensitive << ( tmp_49_fu_873_p3 );
    sensitive << ( p_s_fu_903_p3 );

    SC_METHOD(thread_p_2_fu_765_p3);
    sensitive << ( ap_pipeline_reg_pp0_iter22_isneg_reg_1007 );

    SC_METHOD(thread_p_3_fu_797_p3);
    sensitive << ( ap_pipeline_reg_pp0_iter22_isneg_1_reg_1032 );

    SC_METHOD(thread_p_Result_1_fu_521_p1);
    sensitive << ( tmp_22_fu_514_p3 );

    SC_METHOD(thread_p_Result_s_6_fu_881_p4);
    sensitive << ( p_Val2_3_fu_857_p2 );

    SC_METHOD(thread_p_Result_s_fu_442_p1);
    sensitive << ( tmp_4_fu_435_p3 );

    SC_METHOD(thread_p_Val2_2_fu_829_p3);
    sensitive << ( ap_pipeline_reg_pp0_iter23_or_cond2_reg_1165 );
    sensitive << ( newSel2_reg_1195 );

    SC_METHOD(thread_p_Val2_3_fu_857_p2);
    sensitive << ( tmp_37_fu_835_p1 );
    sensitive << ( tmp_46_cast_fu_853_p1 );

    SC_METHOD(thread_p_s_fu_903_p3);
    sensitive << ( ret_V_fu_863_p4 );
    sensitive << ( tmp_40_fu_891_p2 );
    sensitive << ( ret_V_1_fu_897_p2 );

    SC_METHOD(thread_ret_V_1_fu_897_p2);
    sensitive << ( ret_V_fu_863_p4 );

    SC_METHOD(thread_ret_V_fu_863_p4);
    sensitive << ( p_Val2_3_fu_857_p2 );

    SC_METHOD(thread_sel_tmp10_fu_705_p2);
    sensitive << ( tmp_27_reg_1117 );
    sensitive << ( sel_tmp9_fu_700_p2 );

    SC_METHOD(thread_sel_tmp11_fu_581_p2);
    sensitive << ( sel_tmp31_demorgan_fu_576_p2 );

    SC_METHOD(thread_sel_tmp12_fu_587_p2);
    sensitive << ( tmp_24_fu_538_p2 );
    sensitive << ( sel_tmp11_fu_581_p2 );

    SC_METHOD(thread_sel_tmp13_fu_710_p2);
    sensitive << ( tmp_29_reg_1128 );
    sensitive << ( sel_tmp12_reg_1139 );

    SC_METHOD(thread_sel_tmp14_demorgan_fu_628_p2);
    sensitive << ( tmp_3_reg_1062 );
    sensitive << ( sel_tmp6_demorgan_reg_1090 );

    SC_METHOD(thread_sel_tmp14_fu_718_p2);
    sensitive << ( sel_tmp39_demorgan_fu_714_p2 );

    SC_METHOD(thread_sel_tmp15_fu_724_p2);
    sensitive << ( tmp_30_fu_682_p2 );
    sensitive << ( sel_tmp14_fu_718_p2 );

    SC_METHOD(thread_sel_tmp16_fu_730_p2);
    sensitive << ( tmp_29_reg_1128 );

    SC_METHOD(thread_sel_tmp17_fu_735_p2);
    sensitive << ( sel_tmp12_reg_1139 );
    sensitive << ( sel_tmp16_fu_730_p2 );

    SC_METHOD(thread_sel_tmp1_fu_614_p2);
    sensitive << ( ap_pipeline_reg_pp0_iter21_tmp_1_reg_1018 );

    SC_METHOD(thread_sel_tmp2_fu_619_p2);
    sensitive << ( tmp_8_reg_1073 );
    sensitive << ( sel_tmp1_fu_614_p2 );

    SC_METHOD(thread_sel_tmp31_demorgan_fu_576_p2);
    sensitive << ( tmp_23_reg_1043 );
    sensitive << ( tmp_27_fu_561_p2 );

    SC_METHOD(thread_sel_tmp39_demorgan_fu_714_p2);
    sensitive << ( tmp_24_reg_1106 );
    sensitive << ( sel_tmp31_demorgan_reg_1134 );

    SC_METHOD(thread_sel_tmp3_fu_638_p2);
    sensitive << ( tmp_2_fu_596_p2 );
    sensitive << ( sel_tmp_fu_632_p2 );

    SC_METHOD(thread_sel_tmp4_fu_644_p2);
    sensitive << ( tmp_s_reg_1084 );

    SC_METHOD(thread_sel_tmp5_fu_649_p2);
    sensitive << ( sel_tmp7_reg_1095 );
    sensitive << ( sel_tmp4_fu_644_p2 );

    SC_METHOD(thread_sel_tmp6_demorgan_fu_497_p2);
    sensitive << ( tmp_1_reg_1018 );
    sensitive << ( tmp_8_fu_482_p2 );

    SC_METHOD(thread_sel_tmp6_fu_502_p2);
    sensitive << ( sel_tmp6_demorgan_fu_497_p2 );

    SC_METHOD(thread_sel_tmp7_fu_508_p2);
    sensitive << ( tmp_3_fu_459_p2 );
    sensitive << ( sel_tmp6_fu_502_p2 );

    SC_METHOD(thread_sel_tmp8_fu_624_p2);
    sensitive << ( tmp_s_reg_1084 );
    sensitive << ( sel_tmp7_reg_1095 );

    SC_METHOD(thread_sel_tmp9_fu_700_p2);
    sensitive << ( ap_pipeline_reg_pp0_iter21_tmp_23_reg_1043 );

    SC_METHOD(thread_sel_tmp_fu_632_p2);
    sensitive << ( sel_tmp14_demorgan_fu_628_p2 );

    SC_METHOD(thread_sh_amt_1_cast_fu_679_p1);
    sensitive << ( sh_amt_1_reg_1111 );

    SC_METHOD(thread_sh_amt_1_fu_553_p3);
    sensitive << ( tmp_24_fu_538_p2 );
    sensitive << ( tmp_25_fu_543_p2 );
    sensitive << ( tmp_26_fu_548_p2 );

    SC_METHOD(thread_sh_amt_cast_fu_593_p1);
    sensitive << ( sh_amt_reg_1067 );

    SC_METHOD(thread_sh_amt_fu_474_p3);
    sensitive << ( tmp_3_fu_459_p2 );
    sensitive << ( tmp_5_fu_464_p2 );
    sensitive << ( tmp_7_fu_469_p2 );

    SC_METHOD(thread_tmp_10_fu_601_p1);
    sensitive << ( sh_amt_cast_fu_593_p1 );

    SC_METHOD(thread_tmp_11_fu_605_p2);
    sensitive << ( man_V_2_reg_1057 );
    sensitive << ( tmp_10_fu_601_p1 );

    SC_METHOD(thread_tmp_12_fu_772_p1);
    sensitive << ( ap_pipeline_reg_pp0_iter22_tmp_16_reg_1078 );

    SC_METHOD(thread_tmp_13_fu_775_p2);
    sensitive << ( sh_amt_cast_reg_1145 );
    sensitive << ( tmp_12_fu_772_p1 );

    SC_METHOD(thread_tmp_14_fu_311_p3);
    sensitive << ( tmp_36_reg_952 );

    SC_METHOD(thread_tmp_15_fu_374_p1);
    sensitive << ( ireg_V_fu_345_p1 );

    SC_METHOD(thread_tmp_16_fu_487_p1);
    sensitive << ( man_V_2_fu_452_p3 );

    SC_METHOD(thread_tmp_17_fu_318_p2);
    sensitive << ( tmp_14_fu_311_p3 );

    SC_METHOD(thread_tmp_1_fu_378_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter20 );
    sensitive << ( tmp_9_fu_348_p1 );

    SC_METHOD(thread_tmp_21_fu_415_p1);
    sensitive << ( exp_tmp_V_1_fu_405_p4 );

    SC_METHOD(thread_tmp_22_fu_514_p3);
    sensitive << ( tmp_45_reg_1038 );

    SC_METHOD(thread_tmp_23_fu_423_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter20 );
    sensitive << ( tmp_43_fu_393_p1 );

    SC_METHOD(thread_tmp_24_fu_538_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter21 );
    sensitive << ( F2_1_reg_1049 );

    SC_METHOD(thread_tmp_25_fu_543_p2);
    sensitive << ( F2_1_reg_1049 );

    SC_METHOD(thread_tmp_26_fu_548_p2);
    sensitive << ( F2_1_reg_1049 );

    SC_METHOD(thread_tmp_27_fu_561_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter21 );
    sensitive << ( F2_1_reg_1049 );

    SC_METHOD(thread_tmp_28_fu_610_p1);
    sensitive << ( tmp_11_fu_605_p2 );

    SC_METHOD(thread_tmp_29_fu_570_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter21 );
    sensitive << ( sh_amt_1_fu_553_p3 );

    SC_METHOD(thread_tmp_2_fu_596_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter22 );
    sensitive << ( sh_amt_reg_1067 );

    SC_METHOD(thread_tmp_30_fu_682_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter22 );
    sensitive << ( sh_amt_1_reg_1111 );

    SC_METHOD(thread_tmp_31_fu_687_p1);
    sensitive << ( sh_amt_1_cast_fu_679_p1 );

    SC_METHOD(thread_tmp_32_fu_691_p2);
    sensitive << ( man_V_5_reg_1101 );
    sensitive << ( tmp_31_fu_687_p1 );

    SC_METHOD(thread_tmp_33_fu_780_p1);
    sensitive << ( tmp_13_fu_775_p2 );

    SC_METHOD(thread_tmp_34_fu_804_p1);
    sensitive << ( ap_pipeline_reg_pp0_iter22_tmp_46_reg_1122 );

    SC_METHOD(thread_tmp_35_fu_807_p2);
    sensitive << ( sh_amt_1_cast_reg_1170 );
    sensitive << ( tmp_34_fu_804_p1 );

    SC_METHOD(thread_tmp_37_fu_835_p1);
    sensitive << ( p_Val2_2_fu_829_p3 );

    SC_METHOD(thread_tmp_38_fu_839_p3);
    sensitive << ( ap_pipeline_reg_pp0_iter23_or_cond5_reg_1190 );
    sensitive << ( newSel6_reg_1200 );

    SC_METHOD(thread_tmp_39_fu_845_p3);
    sensitive << ( tmp_38_fu_839_p3 );

    SC_METHOD(thread_tmp_3_fu_459_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter21 );
    sensitive << ( F2_reg_1024 );

    SC_METHOD(thread_tmp_40_fu_891_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter24 );
    sensitive << ( p_Result_s_6_fu_881_p4 );

    SC_METHOD(thread_tmp_41_fu_936_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter25 );
    sensitive << ( abs_fu_929_p3 );

    SC_METHOD(thread_tmp_42_fu_285_p3);
    sensitive << ( inMuon_hwEta_V );

    SC_METHOD(thread_tmp_43_fu_393_p1);
    sensitive << ( ireg_V_1_fu_390_p1 );

    SC_METHOD(thread_tmp_45_fu_419_p1);
    sensitive << ( ireg_V_1_fu_390_p1 );

    SC_METHOD(thread_tmp_46_cast_fu_853_p1);
    sensitive << ( tmp_39_fu_845_p3 );

    SC_METHOD(thread_tmp_46_fu_566_p1);
    sensitive << ( man_V_5_fu_531_p3 );

    SC_METHOD(thread_tmp_47_fu_696_p1);
    sensitive << ( tmp_32_fu_691_p2 );

    SC_METHOD(thread_tmp_48_fu_812_p1);
    sensitive << ( tmp_35_fu_807_p2 );

    SC_METHOD(thread_tmp_49_fu_873_p3);
    sensitive << ( p_Val2_3_fu_857_p2 );

    SC_METHOD(thread_tmp_4_fu_435_p3);
    sensitive << ( tmp_15_reg_1013 );

    SC_METHOD(thread_tmp_52_i_fu_293_p2);
    sensitive << ( inMuon_hwEta_V );

    SC_METHOD(thread_tmp_53_i_cast_fu_299_p1);
    sensitive << ( tmp_52_i_fu_293_p2 );

    SC_METHOD(thread_tmp_54_i_fu_303_p3);
    sensitive << ( tmp_42_fu_285_p3 );
    sensitive << ( tmp_53_i_cast_fu_299_p1 );
    sensitive << ( x_assign_cast_fu_281_p1 );

    SC_METHOD(thread_tmp_5_fu_464_p2);
    sensitive << ( F2_reg_1024 );

    SC_METHOD(thread_tmp_6_fu_370_p1);
    sensitive << ( exp_tmp_V_fu_360_p4 );

    SC_METHOD(thread_tmp_7_fu_469_p2);
    sensitive << ( F2_reg_1024 );

    SC_METHOD(thread_tmp_8_fu_482_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter21 );
    sensitive << ( F2_reg_1024 );

    SC_METHOD(thread_tmp_9_fu_348_p1);
    sensitive << ( ireg_V_fu_345_p1 );

    SC_METHOD(thread_tmp_s_fu_491_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter21 );
    sensitive << ( sh_amt_fu_474_p3 );

    SC_METHOD(thread_x_assign_cast_fu_281_p1);
    sensitive << ( inMuon_hwEta_V );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_pipeline_idle_pp0 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const2);

    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter9 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter10 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter11 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter12 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter13 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter14 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter15 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter16 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter17 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter18 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter19 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter20 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter21 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter22 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter23 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter24 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter25 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "match_hw_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, inTrack_hwRinv_V, "(port)inTrack_hwRinv_V");
    sc_trace(mVcdFile, inTrack_hwPt_V, "(port)inTrack_hwPt_V");
    sc_trace(mVcdFile, inTrack_hwSinhEta_V, "(port)inTrack_hwSinhEta_V");
    sc_trace(mVcdFile, inTrack_hwEta_V, "(port)inTrack_hwEta_V");
    sc_trace(mVcdFile, inTrack_hwPhi_V, "(port)inTrack_hwPhi_V");
    sc_trace(mVcdFile, inTrack_hwPhiGlobal_V, "(port)inTrack_hwPhiGlobal_V");
    sc_trace(mVcdFile, inTrack_hwZ0_V, "(port)inTrack_hwZ0_V");
    sc_trace(mVcdFile, inTrack_hwSector_V, "(port)inTrack_hwSector_V");
    sc_trace(mVcdFile, inTrack_hwQ_V, "(port)inTrack_hwQ_V");
    sc_trace(mVcdFile, inTrack_hwX2_V, "(port)inTrack_hwX2_V");
    sc_trace(mVcdFile, inTrack_hwValid_V, "(port)inTrack_hwValid_V");
    sc_trace(mVcdFile, inTrack_hwBX_V, "(port)inTrack_hwBX_V");
    sc_trace(mVcdFile, inMuon_hwPt_V, "(port)inMuon_hwPt_V");
    sc_trace(mVcdFile, inMuon_hwEta_V, "(port)inMuon_hwEta_V");
    sc_trace(mVcdFile, inMuon_hwPhi_V, "(port)inMuon_hwPhi_V");
    sc_trace(mVcdFile, inMuon_hwQ_V, "(port)inMuon_hwQ_V");
    sc_trace(mVcdFile, inMuon_hwValid_V, "(port)inMuon_hwValid_V");
    sc_trace(mVcdFile, inMuon_hwBX_V, "(port)inMuon_hwBX_V");
    sc_trace(mVcdFile, inMuon_hwQuality_V, "(port)inMuon_hwQuality_V");
    sc_trace(mVcdFile, outTrackMuon_hwPt_V, "(port)outTrackMuon_hwPt_V");
    sc_trace(mVcdFile, outTrackMuon_hwPt_V_ap_vld, "(port)outTrackMuon_hwPt_V_ap_vld");
    sc_trace(mVcdFile, outTrackMuon_hwEta_V, "(port)outTrackMuon_hwEta_V");
    sc_trace(mVcdFile, outTrackMuon_hwEta_V_ap_vld, "(port)outTrackMuon_hwEta_V_ap_vld");
    sc_trace(mVcdFile, outTrackMuon_hwPhi_V, "(port)outTrackMuon_hwPhi_V");
    sc_trace(mVcdFile, outTrackMuon_hwPhi_V_ap_vld, "(port)outTrackMuon_hwPhi_V_ap_vld");
    sc_trace(mVcdFile, outTrackMuon_hwQ_V, "(port)outTrackMuon_hwQ_V");
    sc_trace(mVcdFile, outTrackMuon_hwQ_V_ap_vld, "(port)outTrackMuon_hwQ_V_ap_vld");
    sc_trace(mVcdFile, outTrackMuon_hwValid_V, "(port)outTrackMuon_hwValid_V");
    sc_trace(mVcdFile, outTrackMuon_hwValid_V_ap_vld, "(port)outTrackMuon_hwValid_V_ap_vld");
    sc_trace(mVcdFile, outTrackMuon_hwBX_V, "(port)outTrackMuon_hwBX_V");
    sc_trace(mVcdFile, outTrackMuon_hwBX_V_ap_vld, "(port)outTrackMuon_hwBX_V_ap_vld");
    sc_trace(mVcdFile, outTrackMuon_hwQuality_V, "(port)outTrackMuon_hwQuality_V");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter9, "ap_enable_reg_pp0_iter9");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter10, "ap_enable_reg_pp0_iter10");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter11, "ap_enable_reg_pp0_iter11");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter12, "ap_enable_reg_pp0_iter12");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter13, "ap_enable_reg_pp0_iter13");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter14, "ap_enable_reg_pp0_iter14");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter15, "ap_enable_reg_pp0_iter15");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter16, "ap_enable_reg_pp0_iter16");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter17, "ap_enable_reg_pp0_iter17");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter18, "ap_enable_reg_pp0_iter18");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter19, "ap_enable_reg_pp0_iter19");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter20, "ap_enable_reg_pp0_iter20");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter21, "ap_enable_reg_pp0_iter21");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter22, "ap_enable_reg_pp0_iter22");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter23, "ap_enable_reg_pp0_iter23");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter24, "ap_enable_reg_pp0_iter24");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter25, "ap_enable_reg_pp0_iter25");
    sc_trace(mVcdFile, inTrack_hwEta_V_read_reg_942, "inTrack_hwEta_V_read_reg_942");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter1_inTrack_hwEta_V_read_reg_942, "ap_pipeline_reg_pp0_iter1_inTrack_hwEta_V_read_reg_942");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter2_inTrack_hwEta_V_read_reg_942, "ap_pipeline_reg_pp0_iter2_inTrack_hwEta_V_read_reg_942");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter3_inTrack_hwEta_V_read_reg_942, "ap_pipeline_reg_pp0_iter3_inTrack_hwEta_V_read_reg_942");
    sc_trace(mVcdFile, inMuon_hwEta_V_read_reg_947, "inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter1_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter1_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter2_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter2_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter3_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter3_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter4_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter4_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter5_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter5_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter6_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter6_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter7_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter7_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter8_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter8_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter9_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter9_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter10_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter10_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter11_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter11_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter12_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter12_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter13_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter13_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter14_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter14_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter15_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter15_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter16_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter16_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter17_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter17_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter18_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter18_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter19_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter19_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter20_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter20_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter21_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter21_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter22_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter22_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter23_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter23_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter24_inMuon_hwEta_V_read_reg_947, "ap_pipeline_reg_pp0_iter24_inMuon_hwEta_V_read_reg_947");
    sc_trace(mVcdFile, tmp_36_reg_952, "tmp_36_reg_952");
    sc_trace(mVcdFile, tmp_54_i_fu_303_p3, "tmp_54_i_fu_303_p3");
    sc_trace(mVcdFile, tmp_54_i_reg_957, "tmp_54_i_reg_957");
    sc_trace(mVcdFile, grp_fu_331_p2, "grp_fu_331_p2");
    sc_trace(mVcdFile, tmp_18_reg_972, "tmp_18_reg_972");
    sc_trace(mVcdFile, grp_fu_267_p1, "grp_fu_267_p1");
    sc_trace(mVcdFile, tmp_reg_987, "tmp_reg_987");
    sc_trace(mVcdFile, grp_fu_270_p1, "grp_fu_270_p1");
    sc_trace(mVcdFile, tmp_20_reg_992, "tmp_20_reg_992");
    sc_trace(mVcdFile, grp_fu_257_p2, "grp_fu_257_p2");
    sc_trace(mVcdFile, v_assign_reg_997, "v_assign_reg_997");
    sc_trace(mVcdFile, grp_fu_262_p2, "grp_fu_262_p2");
    sc_trace(mVcdFile, v_assign_1_reg_1002, "v_assign_1_reg_1002");
    sc_trace(mVcdFile, isneg_reg_1007, "isneg_reg_1007");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter21_isneg_reg_1007, "ap_pipeline_reg_pp0_iter21_isneg_reg_1007");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter22_isneg_reg_1007, "ap_pipeline_reg_pp0_iter22_isneg_reg_1007");
    sc_trace(mVcdFile, tmp_15_fu_374_p1, "tmp_15_fu_374_p1");
    sc_trace(mVcdFile, tmp_15_reg_1013, "tmp_15_reg_1013");
    sc_trace(mVcdFile, tmp_1_fu_378_p2, "tmp_1_fu_378_p2");
    sc_trace(mVcdFile, tmp_1_reg_1018, "tmp_1_reg_1018");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter21_tmp_1_reg_1018, "ap_pipeline_reg_pp0_iter21_tmp_1_reg_1018");
    sc_trace(mVcdFile, F2_fu_384_p2, "F2_fu_384_p2");
    sc_trace(mVcdFile, F2_reg_1024, "F2_reg_1024");
    sc_trace(mVcdFile, isneg_1_reg_1032, "isneg_1_reg_1032");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter21_isneg_1_reg_1032, "ap_pipeline_reg_pp0_iter21_isneg_1_reg_1032");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter22_isneg_1_reg_1032, "ap_pipeline_reg_pp0_iter22_isneg_1_reg_1032");
    sc_trace(mVcdFile, tmp_45_fu_419_p1, "tmp_45_fu_419_p1");
    sc_trace(mVcdFile, tmp_45_reg_1038, "tmp_45_reg_1038");
    sc_trace(mVcdFile, tmp_23_fu_423_p2, "tmp_23_fu_423_p2");
    sc_trace(mVcdFile, tmp_23_reg_1043, "tmp_23_reg_1043");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter21_tmp_23_reg_1043, "ap_pipeline_reg_pp0_iter21_tmp_23_reg_1043");
    sc_trace(mVcdFile, F2_1_fu_429_p2, "F2_1_fu_429_p2");
    sc_trace(mVcdFile, F2_1_reg_1049, "F2_1_reg_1049");
    sc_trace(mVcdFile, man_V_2_fu_452_p3, "man_V_2_fu_452_p3");
    sc_trace(mVcdFile, man_V_2_reg_1057, "man_V_2_reg_1057");
    sc_trace(mVcdFile, tmp_3_fu_459_p2, "tmp_3_fu_459_p2");
    sc_trace(mVcdFile, tmp_3_reg_1062, "tmp_3_reg_1062");
    sc_trace(mVcdFile, sh_amt_fu_474_p3, "sh_amt_fu_474_p3");
    sc_trace(mVcdFile, sh_amt_reg_1067, "sh_amt_reg_1067");
    sc_trace(mVcdFile, tmp_8_fu_482_p2, "tmp_8_fu_482_p2");
    sc_trace(mVcdFile, tmp_8_reg_1073, "tmp_8_reg_1073");
    sc_trace(mVcdFile, tmp_16_fu_487_p1, "tmp_16_fu_487_p1");
    sc_trace(mVcdFile, tmp_16_reg_1078, "tmp_16_reg_1078");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter22_tmp_16_reg_1078, "ap_pipeline_reg_pp0_iter22_tmp_16_reg_1078");
    sc_trace(mVcdFile, tmp_s_fu_491_p2, "tmp_s_fu_491_p2");
    sc_trace(mVcdFile, tmp_s_reg_1084, "tmp_s_reg_1084");
    sc_trace(mVcdFile, sel_tmp6_demorgan_fu_497_p2, "sel_tmp6_demorgan_fu_497_p2");
    sc_trace(mVcdFile, sel_tmp6_demorgan_reg_1090, "sel_tmp6_demorgan_reg_1090");
    sc_trace(mVcdFile, sel_tmp7_fu_508_p2, "sel_tmp7_fu_508_p2");
    sc_trace(mVcdFile, sel_tmp7_reg_1095, "sel_tmp7_reg_1095");
    sc_trace(mVcdFile, man_V_5_fu_531_p3, "man_V_5_fu_531_p3");
    sc_trace(mVcdFile, man_V_5_reg_1101, "man_V_5_reg_1101");
    sc_trace(mVcdFile, tmp_24_fu_538_p2, "tmp_24_fu_538_p2");
    sc_trace(mVcdFile, tmp_24_reg_1106, "tmp_24_reg_1106");
    sc_trace(mVcdFile, sh_amt_1_fu_553_p3, "sh_amt_1_fu_553_p3");
    sc_trace(mVcdFile, sh_amt_1_reg_1111, "sh_amt_1_reg_1111");
    sc_trace(mVcdFile, tmp_27_fu_561_p2, "tmp_27_fu_561_p2");
    sc_trace(mVcdFile, tmp_27_reg_1117, "tmp_27_reg_1117");
    sc_trace(mVcdFile, tmp_46_fu_566_p1, "tmp_46_fu_566_p1");
    sc_trace(mVcdFile, tmp_46_reg_1122, "tmp_46_reg_1122");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter22_tmp_46_reg_1122, "ap_pipeline_reg_pp0_iter22_tmp_46_reg_1122");
    sc_trace(mVcdFile, tmp_29_fu_570_p2, "tmp_29_fu_570_p2");
    sc_trace(mVcdFile, tmp_29_reg_1128, "tmp_29_reg_1128");
    sc_trace(mVcdFile, sel_tmp31_demorgan_fu_576_p2, "sel_tmp31_demorgan_fu_576_p2");
    sc_trace(mVcdFile, sel_tmp31_demorgan_reg_1134, "sel_tmp31_demorgan_reg_1134");
    sc_trace(mVcdFile, sel_tmp12_fu_587_p2, "sel_tmp12_fu_587_p2");
    sc_trace(mVcdFile, sel_tmp12_reg_1139, "sel_tmp12_reg_1139");
    sc_trace(mVcdFile, sh_amt_cast_fu_593_p1, "sh_amt_cast_fu_593_p1");
    sc_trace(mVcdFile, sh_amt_cast_reg_1145, "sh_amt_cast_reg_1145");
    sc_trace(mVcdFile, sel_tmp5_fu_649_p2, "sel_tmp5_fu_649_p2");
    sc_trace(mVcdFile, sel_tmp5_reg_1150, "sel_tmp5_reg_1150");
    sc_trace(mVcdFile, or_cond_fu_654_p2, "or_cond_fu_654_p2");
    sc_trace(mVcdFile, or_cond_reg_1155, "or_cond_reg_1155");
    sc_trace(mVcdFile, newSel1_fu_660_p3, "newSel1_fu_660_p3");
    sc_trace(mVcdFile, newSel1_reg_1160, "newSel1_reg_1160");
    sc_trace(mVcdFile, or_cond2_fu_673_p2, "or_cond2_fu_673_p2");
    sc_trace(mVcdFile, or_cond2_reg_1165, "or_cond2_reg_1165");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter23_or_cond2_reg_1165, "ap_pipeline_reg_pp0_iter23_or_cond2_reg_1165");
    sc_trace(mVcdFile, sh_amt_1_cast_fu_679_p1, "sh_amt_1_cast_fu_679_p1");
    sc_trace(mVcdFile, sh_amt_1_cast_reg_1170, "sh_amt_1_cast_reg_1170");
    sc_trace(mVcdFile, sel_tmp17_fu_735_p2, "sel_tmp17_fu_735_p2");
    sc_trace(mVcdFile, sel_tmp17_reg_1175, "sel_tmp17_reg_1175");
    sc_trace(mVcdFile, or_cond3_fu_740_p2, "or_cond3_fu_740_p2");
    sc_trace(mVcdFile, or_cond3_reg_1180, "or_cond3_reg_1180");
    sc_trace(mVcdFile, newSel5_fu_746_p3, "newSel5_fu_746_p3");
    sc_trace(mVcdFile, newSel5_reg_1185, "newSel5_reg_1185");
    sc_trace(mVcdFile, or_cond5_fu_759_p2, "or_cond5_fu_759_p2");
    sc_trace(mVcdFile, or_cond5_reg_1190, "or_cond5_reg_1190");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter23_or_cond5_reg_1190, "ap_pipeline_reg_pp0_iter23_or_cond5_reg_1190");
    sc_trace(mVcdFile, newSel2_fu_791_p3, "newSel2_fu_791_p3");
    sc_trace(mVcdFile, newSel2_reg_1195, "newSel2_reg_1195");
    sc_trace(mVcdFile, newSel6_fu_823_p3, "newSel6_fu_823_p3");
    sc_trace(mVcdFile, newSel6_reg_1200, "newSel6_reg_1200");
    sc_trace(mVcdFile, p_1_fu_911_p3, "p_1_fu_911_p3");
    sc_trace(mVcdFile, p_1_reg_1205, "p_1_reg_1205");
    sc_trace(mVcdFile, tmp_41_fu_936_p2, "tmp_41_fu_936_p2");
    sc_trace(mVcdFile, grp_fu_267_p0, "grp_fu_267_p0");
    sc_trace(mVcdFile, grp_fu_270_p0, "grp_fu_270_p0");
    sc_trace(mVcdFile, tmp_52_i_fu_293_p2, "tmp_52_i_fu_293_p2");
    sc_trace(mVcdFile, tmp_42_fu_285_p3, "tmp_42_fu_285_p3");
    sc_trace(mVcdFile, tmp_53_i_cast_fu_299_p1, "tmp_53_i_cast_fu_299_p1");
    sc_trace(mVcdFile, x_assign_cast_fu_281_p1, "x_assign_cast_fu_281_p1");
    sc_trace(mVcdFile, tmp_14_fu_311_p3, "tmp_14_fu_311_p3");
    sc_trace(mVcdFile, tmp_17_fu_318_p2, "tmp_17_fu_318_p2");
    sc_trace(mVcdFile, ireg_V_fu_345_p1, "ireg_V_fu_345_p1");
    sc_trace(mVcdFile, exp_tmp_V_fu_360_p4, "exp_tmp_V_fu_360_p4");
    sc_trace(mVcdFile, tmp_9_fu_348_p1, "tmp_9_fu_348_p1");
    sc_trace(mVcdFile, tmp_6_fu_370_p1, "tmp_6_fu_370_p1");
    sc_trace(mVcdFile, ireg_V_1_fu_390_p1, "ireg_V_1_fu_390_p1");
    sc_trace(mVcdFile, exp_tmp_V_1_fu_405_p4, "exp_tmp_V_1_fu_405_p4");
    sc_trace(mVcdFile, tmp_43_fu_393_p1, "tmp_43_fu_393_p1");
    sc_trace(mVcdFile, tmp_21_fu_415_p1, "tmp_21_fu_415_p1");
    sc_trace(mVcdFile, tmp_4_fu_435_p3, "tmp_4_fu_435_p3");
    sc_trace(mVcdFile, p_Result_s_fu_442_p1, "p_Result_s_fu_442_p1");
    sc_trace(mVcdFile, man_V_1_fu_446_p2, "man_V_1_fu_446_p2");
    sc_trace(mVcdFile, tmp_5_fu_464_p2, "tmp_5_fu_464_p2");
    sc_trace(mVcdFile, tmp_7_fu_469_p2, "tmp_7_fu_469_p2");
    sc_trace(mVcdFile, sel_tmp6_fu_502_p2, "sel_tmp6_fu_502_p2");
    sc_trace(mVcdFile, tmp_22_fu_514_p3, "tmp_22_fu_514_p3");
    sc_trace(mVcdFile, p_Result_1_fu_521_p1, "p_Result_1_fu_521_p1");
    sc_trace(mVcdFile, man_V_4_fu_525_p2, "man_V_4_fu_525_p2");
    sc_trace(mVcdFile, tmp_25_fu_543_p2, "tmp_25_fu_543_p2");
    sc_trace(mVcdFile, tmp_26_fu_548_p2, "tmp_26_fu_548_p2");
    sc_trace(mVcdFile, sel_tmp11_fu_581_p2, "sel_tmp11_fu_581_p2");
    sc_trace(mVcdFile, tmp_10_fu_601_p1, "tmp_10_fu_601_p1");
    sc_trace(mVcdFile, tmp_11_fu_605_p2, "tmp_11_fu_605_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_614_p2, "sel_tmp1_fu_614_p2");
    sc_trace(mVcdFile, sel_tmp14_demorgan_fu_628_p2, "sel_tmp14_demorgan_fu_628_p2");
    sc_trace(mVcdFile, tmp_2_fu_596_p2, "tmp_2_fu_596_p2");
    sc_trace(mVcdFile, sel_tmp_fu_632_p2, "sel_tmp_fu_632_p2");
    sc_trace(mVcdFile, sel_tmp4_fu_644_p2, "sel_tmp4_fu_644_p2");
    sc_trace(mVcdFile, sel_tmp3_fu_638_p2, "sel_tmp3_fu_638_p2");
    sc_trace(mVcdFile, sel_tmp8_fu_624_p2, "sel_tmp8_fu_624_p2");
    sc_trace(mVcdFile, tmp_28_fu_610_p1, "tmp_28_fu_610_p1");
    sc_trace(mVcdFile, sel_tmp2_fu_619_p2, "sel_tmp2_fu_619_p2");
    sc_trace(mVcdFile, or_cond1_fu_667_p2, "or_cond1_fu_667_p2");
    sc_trace(mVcdFile, tmp_31_fu_687_p1, "tmp_31_fu_687_p1");
    sc_trace(mVcdFile, tmp_32_fu_691_p2, "tmp_32_fu_691_p2");
    sc_trace(mVcdFile, sel_tmp9_fu_700_p2, "sel_tmp9_fu_700_p2");
    sc_trace(mVcdFile, sel_tmp39_demorgan_fu_714_p2, "sel_tmp39_demorgan_fu_714_p2");
    sc_trace(mVcdFile, tmp_30_fu_682_p2, "tmp_30_fu_682_p2");
    sc_trace(mVcdFile, sel_tmp14_fu_718_p2, "sel_tmp14_fu_718_p2");
    sc_trace(mVcdFile, sel_tmp16_fu_730_p2, "sel_tmp16_fu_730_p2");
    sc_trace(mVcdFile, sel_tmp15_fu_724_p2, "sel_tmp15_fu_724_p2");
    sc_trace(mVcdFile, sel_tmp13_fu_710_p2, "sel_tmp13_fu_710_p2");
    sc_trace(mVcdFile, tmp_47_fu_696_p1, "tmp_47_fu_696_p1");
    sc_trace(mVcdFile, sel_tmp10_fu_705_p2, "sel_tmp10_fu_705_p2");
    sc_trace(mVcdFile, or_cond4_fu_753_p2, "or_cond4_fu_753_p2");
    sc_trace(mVcdFile, tmp_12_fu_772_p1, "tmp_12_fu_772_p1");
    sc_trace(mVcdFile, tmp_13_fu_775_p2, "tmp_13_fu_775_p2");
    sc_trace(mVcdFile, p_2_fu_765_p3, "p_2_fu_765_p3");
    sc_trace(mVcdFile, tmp_33_fu_780_p1, "tmp_33_fu_780_p1");
    sc_trace(mVcdFile, newSel_fu_784_p3, "newSel_fu_784_p3");
    sc_trace(mVcdFile, tmp_34_fu_804_p1, "tmp_34_fu_804_p1");
    sc_trace(mVcdFile, tmp_35_fu_807_p2, "tmp_35_fu_807_p2");
    sc_trace(mVcdFile, p_3_fu_797_p3, "p_3_fu_797_p3");
    sc_trace(mVcdFile, tmp_48_fu_812_p1, "tmp_48_fu_812_p1");
    sc_trace(mVcdFile, newSel4_fu_816_p3, "newSel4_fu_816_p3");
    sc_trace(mVcdFile, p_Val2_2_fu_829_p3, "p_Val2_2_fu_829_p3");
    sc_trace(mVcdFile, tmp_38_fu_839_p3, "tmp_38_fu_839_p3");
    sc_trace(mVcdFile, tmp_39_fu_845_p3, "tmp_39_fu_845_p3");
    sc_trace(mVcdFile, tmp_37_fu_835_p1, "tmp_37_fu_835_p1");
    sc_trace(mVcdFile, tmp_46_cast_fu_853_p1, "tmp_46_cast_fu_853_p1");
    sc_trace(mVcdFile, p_Val2_3_fu_857_p2, "p_Val2_3_fu_857_p2");
    sc_trace(mVcdFile, p_Result_s_6_fu_881_p4, "p_Result_s_6_fu_881_p4");
    sc_trace(mVcdFile, ret_V_fu_863_p4, "ret_V_fu_863_p4");
    sc_trace(mVcdFile, tmp_40_fu_891_p2, "tmp_40_fu_891_p2");
    sc_trace(mVcdFile, ret_V_1_fu_897_p2, "ret_V_1_fu_897_p2");
    sc_trace(mVcdFile, tmp_49_fu_873_p3, "tmp_49_fu_873_p3");
    sc_trace(mVcdFile, p_s_fu_903_p3, "p_s_fu_903_p3");
    sc_trace(mVcdFile, abscond_fu_924_p2, "abscond_fu_924_p2");
    sc_trace(mVcdFile, neg_fu_919_p2, "neg_fu_919_p2");
    sc_trace(mVcdFile, abs_fu_929_p3, "abs_fu_929_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_pipeline_idle_pp0, "ap_pipeline_idle_pp0");
    sc_trace(mVcdFile, ap_condition_329, "ap_condition_329");
#endif

    }
    mHdltvinHandle.open("match_hw.hdltvin.dat");
    mHdltvoutHandle.open("match_hw.hdltvout.dat");
}

match_hw::~match_hw() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete match_hw_dmul_64nbkb_U1;
    delete match_hw_dmul_64nbkb_U2;
    delete match_hw_sitodp_3cud_U3;
    delete match_hw_sitodp_3cud_U4;
    delete match_hw_mul_10s_dEe_U5;
}

void match_hw::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_logic_1;
}

void match_hw::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv64_3F600000972ECF2E;
}

void match_hw::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv64_3F8645A1CAC08312;
}

void match_hw::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
             !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter10 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter10 = ap_enable_reg_pp0_iter9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter11 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter11 = ap_enable_reg_pp0_iter10.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter12 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter12 = ap_enable_reg_pp0_iter11.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter13 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter13 = ap_enable_reg_pp0_iter12.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter14 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter14 = ap_enable_reg_pp0_iter13.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter15 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter15 = ap_enable_reg_pp0_iter14.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter16 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter16 = ap_enable_reg_pp0_iter15.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter17 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter17 = ap_enable_reg_pp0_iter16.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter18 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter18 = ap_enable_reg_pp0_iter17.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter19 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter19 = ap_enable_reg_pp0_iter18.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter20 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter20 = ap_enable_reg_pp0_iter19.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter21 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter21 = ap_enable_reg_pp0_iter20.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter22 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter22 = ap_enable_reg_pp0_iter21.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter23 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter23 = ap_enable_reg_pp0_iter22.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter24 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter24 = ap_enable_reg_pp0_iter23.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter25 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter25 = ap_enable_reg_pp0_iter24.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter9 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter9 = ap_enable_reg_pp0_iter8.read();
        }
    }
    if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        F2_1_reg_1049 = F2_1_fu_429_p2.read();
        F2_reg_1024 = F2_fu_384_p2.read();
        ap_pipeline_reg_pp0_iter10_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter9_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter11_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter10_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter12_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter11_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter13_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter12_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter14_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter13_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter15_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter14_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter16_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter15_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter17_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter16_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter18_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter17_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter19_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter18_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter20_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter19_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter21_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter20_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter21_isneg_1_reg_1032 = isneg_1_reg_1032.read();
        ap_pipeline_reg_pp0_iter21_isneg_reg_1007 = isneg_reg_1007.read();
        ap_pipeline_reg_pp0_iter21_tmp_1_reg_1018 = tmp_1_reg_1018.read();
        ap_pipeline_reg_pp0_iter21_tmp_23_reg_1043 = tmp_23_reg_1043.read();
        ap_pipeline_reg_pp0_iter22_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter21_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter22_isneg_1_reg_1032 = ap_pipeline_reg_pp0_iter21_isneg_1_reg_1032.read();
        ap_pipeline_reg_pp0_iter22_isneg_reg_1007 = ap_pipeline_reg_pp0_iter21_isneg_reg_1007.read();
        ap_pipeline_reg_pp0_iter22_tmp_16_reg_1078 = tmp_16_reg_1078.read();
        ap_pipeline_reg_pp0_iter22_tmp_46_reg_1122 = tmp_46_reg_1122.read();
        ap_pipeline_reg_pp0_iter23_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter22_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter23_or_cond2_reg_1165 = or_cond2_reg_1165.read();
        ap_pipeline_reg_pp0_iter23_or_cond5_reg_1190 = or_cond5_reg_1190.read();
        ap_pipeline_reg_pp0_iter24_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter23_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter2_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter1_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter2_inTrack_hwEta_V_read_reg_942 = ap_pipeline_reg_pp0_iter1_inTrack_hwEta_V_read_reg_942.read();
        ap_pipeline_reg_pp0_iter3_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter2_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter3_inTrack_hwEta_V_read_reg_942 = ap_pipeline_reg_pp0_iter2_inTrack_hwEta_V_read_reg_942.read();
        ap_pipeline_reg_pp0_iter4_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter3_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter5_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter4_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter6_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter5_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter7_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter6_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter8_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter7_inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter9_inMuon_hwEta_V_read_reg_947 = ap_pipeline_reg_pp0_iter8_inMuon_hwEta_V_read_reg_947.read();
        isneg_1_reg_1032 = ireg_V_1_fu_390_p1.read().range(63, 63);
        isneg_reg_1007 = ireg_V_fu_345_p1.read().range(63, 63);
        man_V_2_reg_1057 = man_V_2_fu_452_p3.read();
        man_V_5_reg_1101 = man_V_5_fu_531_p3.read();
        newSel1_reg_1160 = newSel1_fu_660_p3.read();
        newSel5_reg_1185 = newSel5_fu_746_p3.read();
        or_cond2_reg_1165 = or_cond2_fu_673_p2.read();
        or_cond3_reg_1180 = or_cond3_fu_740_p2.read();
        or_cond5_reg_1190 = or_cond5_fu_759_p2.read();
        or_cond_reg_1155 = or_cond_fu_654_p2.read();
        p_1_reg_1205 = p_1_fu_911_p3.read();
        sel_tmp12_reg_1139 = sel_tmp12_fu_587_p2.read();
        sel_tmp17_reg_1175 = sel_tmp17_fu_735_p2.read();
        sel_tmp31_demorgan_reg_1134 = sel_tmp31_demorgan_fu_576_p2.read();
        sel_tmp5_reg_1150 = sel_tmp5_fu_649_p2.read();
        sel_tmp6_demorgan_reg_1090 = sel_tmp6_demorgan_fu_497_p2.read();
        sel_tmp7_reg_1095 = sel_tmp7_fu_508_p2.read();
        sh_amt_1_cast_reg_1170 = sh_amt_1_cast_fu_679_p1.read();
        sh_amt_1_reg_1111 = sh_amt_1_fu_553_p3.read();
        sh_amt_cast_reg_1145 = sh_amt_cast_fu_593_p1.read();
        sh_amt_reg_1067 = sh_amt_fu_474_p3.read();
        tmp_15_reg_1013 = tmp_15_fu_374_p1.read();
        tmp_16_reg_1078 = tmp_16_fu_487_p1.read();
        tmp_18_reg_972 = grp_fu_331_p2.read();
        tmp_1_reg_1018 = tmp_1_fu_378_p2.read();
        tmp_20_reg_992 = grp_fu_270_p1.read();
        tmp_23_reg_1043 = tmp_23_fu_423_p2.read();
        tmp_24_reg_1106 = tmp_24_fu_538_p2.read();
        tmp_27_reg_1117 = tmp_27_fu_561_p2.read();
        tmp_29_reg_1128 = tmp_29_fu_570_p2.read();
        tmp_3_reg_1062 = tmp_3_fu_459_p2.read();
        tmp_45_reg_1038 = tmp_45_fu_419_p1.read();
        tmp_46_reg_1122 = tmp_46_fu_566_p1.read();
        tmp_8_reg_1073 = tmp_8_fu_482_p2.read();
        tmp_reg_987 = grp_fu_267_p1.read();
        tmp_s_reg_1084 = tmp_s_fu_491_p2.read();
        v_assign_1_reg_1002 = grp_fu_262_p2.read();
        v_assign_reg_997 = grp_fu_257_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_pipeline_reg_pp0_iter1_inMuon_hwEta_V_read_reg_947 = inMuon_hwEta_V_read_reg_947.read();
        ap_pipeline_reg_pp0_iter1_inTrack_hwEta_V_read_reg_942 = inTrack_hwEta_V_read_reg_942.read();
        inMuon_hwEta_V_read_reg_947 = inMuon_hwEta_V.read();
        inTrack_hwEta_V_read_reg_942 = inTrack_hwEta_V.read();
        tmp_36_reg_952 = inMuon_hwEta_V.read().range(8, 8);
        tmp_54_i_reg_957 = tmp_54_i_fu_303_p3.read();
    }
    if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && !esl_seteq<1,1,1>(or_cond2_reg_1165.read(), ap_const_lv1_0))) {
        newSel2_reg_1195 = newSel2_fu_791_p3.read();
    }
    if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && !esl_seteq<1,1,1>(or_cond5_reg_1190.read(), ap_const_lv1_0))) {
        newSel6_reg_1200 = newSel6_fu_823_p3.read();
    }
}

void match_hw::thread_F2_1_fu_429_p2() {
    F2_1_fu_429_p2 = (!ap_const_lv12_433.is_01() || !tmp_21_fu_415_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_433) - sc_biguint<12>(tmp_21_fu_415_p1.read()));
}

void match_hw::thread_F2_fu_384_p2() {
    F2_fu_384_p2 = (!ap_const_lv12_433.is_01() || !tmp_6_fu_370_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_433) - sc_biguint<12>(tmp_6_fu_370_p1.read()));
}

void match_hw::thread_abs_fu_929_p3() {
    abs_fu_929_p3 = (!abscond_fu_924_p2.read()[0].is_01())? sc_lv<4>(): ((abscond_fu_924_p2.read()[0].to_bool())? p_1_reg_1205.read(): neg_fu_919_p2.read());
}

void match_hw::thread_abscond_fu_924_p2() {
    abscond_fu_924_p2 = (!p_1_reg_1205.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): (sc_bigint<4>(p_1_reg_1205.read()) > sc_bigint<4>(ap_const_lv4_0));
}

void match_hw::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read().range(0, 0);
}

void match_hw::thread_ap_condition_329() {
    ap_condition_329 = (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter25.read()));
}

void match_hw::thread_ap_done() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter25.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void match_hw::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void match_hw::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter14.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter15.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter16.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter17.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter18.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter19.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter20.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter21.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter22.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter23.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter24.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter25.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void match_hw::thread_ap_pipeline_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter9.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter10.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter11.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter12.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter13.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter14.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter15.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter16.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter17.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter18.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter19.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter20.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter21.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter22.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter23.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter24.read()))) {
        ap_pipeline_idle_pp0 = ap_const_logic_1;
    } else {
        ap_pipeline_idle_pp0 = ap_const_logic_0;
    }
}

void match_hw::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void match_hw::thread_exp_tmp_V_1_fu_405_p4() {
    exp_tmp_V_1_fu_405_p4 = ireg_V_1_fu_390_p1.read().range(62, 52);
}

void match_hw::thread_exp_tmp_V_fu_360_p4() {
    exp_tmp_V_fu_360_p4 = ireg_V_fu_345_p1.read().range(62, 52);
}

void match_hw::thread_grp_fu_267_p0() {
    grp_fu_267_p0 = esl_sext<32,14>(ap_pipeline_reg_pp0_iter3_inTrack_hwEta_V_read_reg_942.read());
}

void match_hw::thread_grp_fu_270_p0() {
    grp_fu_270_p0 = esl_sext<32,12>(tmp_18_reg_972.read());
}

void match_hw::thread_ireg_V_1_fu_390_p1() {
    ireg_V_1_fu_390_p1 = v_assign_1_reg_1002.read();
}

void match_hw::thread_ireg_V_fu_345_p1() {
    ireg_V_fu_345_p1 = v_assign_reg_997.read();
}

void match_hw::thread_man_V_1_fu_446_p2() {
    man_V_1_fu_446_p2 = (!ap_const_lv54_0.is_01() || !p_Result_s_fu_442_p1.read().is_01())? sc_lv<54>(): (sc_biguint<54>(ap_const_lv54_0) - sc_biguint<54>(p_Result_s_fu_442_p1.read()));
}

void match_hw::thread_man_V_2_fu_452_p3() {
    man_V_2_fu_452_p3 = (!isneg_reg_1007.read()[0].is_01())? sc_lv<54>(): ((isneg_reg_1007.read()[0].to_bool())? man_V_1_fu_446_p2.read(): p_Result_s_fu_442_p1.read());
}

void match_hw::thread_man_V_4_fu_525_p2() {
    man_V_4_fu_525_p2 = (!ap_const_lv54_0.is_01() || !p_Result_1_fu_521_p1.read().is_01())? sc_lv<54>(): (sc_biguint<54>(ap_const_lv54_0) - sc_biguint<54>(p_Result_1_fu_521_p1.read()));
}

void match_hw::thread_man_V_5_fu_531_p3() {
    man_V_5_fu_531_p3 = (!isneg_1_reg_1032.read()[0].is_01())? sc_lv<54>(): ((isneg_1_reg_1032.read()[0].to_bool())? man_V_4_fu_525_p2.read(): p_Result_1_fu_521_p1.read());
}

void match_hw::thread_neg_fu_919_p2() {
    neg_fu_919_p2 = (!ap_const_lv4_0.is_01() || !p_1_reg_1205.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_0) - sc_biguint<4>(p_1_reg_1205.read()));
}

void match_hw::thread_newSel1_fu_660_p3() {
    newSel1_fu_660_p3 = (!sel_tmp8_fu_624_p2.read()[0].is_01())? sc_lv<14>(): ((sel_tmp8_fu_624_p2.read()[0].to_bool())? tmp_28_fu_610_p1.read(): tmp_16_reg_1078.read());
}

void match_hw::thread_newSel2_fu_791_p3() {
    newSel2_fu_791_p3 = (!or_cond_reg_1155.read()[0].is_01())? sc_lv<14>(): ((or_cond_reg_1155.read()[0].to_bool())? newSel_fu_784_p3.read(): newSel1_reg_1160.read());
}

void match_hw::thread_newSel4_fu_816_p3() {
    newSel4_fu_816_p3 = (!sel_tmp17_reg_1175.read()[0].is_01())? sc_lv<10>(): ((sel_tmp17_reg_1175.read()[0].to_bool())? p_3_fu_797_p3.read(): tmp_48_fu_812_p1.read());
}

void match_hw::thread_newSel5_fu_746_p3() {
    newSel5_fu_746_p3 = (!sel_tmp13_fu_710_p2.read()[0].is_01())? sc_lv<10>(): ((sel_tmp13_fu_710_p2.read()[0].to_bool())? tmp_47_fu_696_p1.read(): tmp_46_reg_1122.read());
}

void match_hw::thread_newSel6_fu_823_p3() {
    newSel6_fu_823_p3 = (!or_cond3_reg_1180.read()[0].is_01())? sc_lv<10>(): ((or_cond3_reg_1180.read()[0].to_bool())? newSel4_fu_816_p3.read(): newSel5_reg_1185.read());
}

void match_hw::thread_newSel_fu_784_p3() {
    newSel_fu_784_p3 = (!sel_tmp5_reg_1150.read()[0].is_01())? sc_lv<14>(): ((sel_tmp5_reg_1150.read()[0].to_bool())? p_2_fu_765_p3.read(): tmp_33_fu_780_p1.read());
}

void match_hw::thread_or_cond1_fu_667_p2() {
    or_cond1_fu_667_p2 = (sel_tmp8_fu_624_p2.read() | sel_tmp2_fu_619_p2.read());
}

void match_hw::thread_or_cond2_fu_673_p2() {
    or_cond2_fu_673_p2 = (or_cond_fu_654_p2.read() | or_cond1_fu_667_p2.read());
}

void match_hw::thread_or_cond3_fu_740_p2() {
    or_cond3_fu_740_p2 = (sel_tmp17_fu_735_p2.read() | sel_tmp15_fu_724_p2.read());
}

void match_hw::thread_or_cond4_fu_753_p2() {
    or_cond4_fu_753_p2 = (sel_tmp13_fu_710_p2.read() | sel_tmp10_fu_705_p2.read());
}

void match_hw::thread_or_cond5_fu_759_p2() {
    or_cond5_fu_759_p2 = (or_cond3_fu_740_p2.read() | or_cond4_fu_753_p2.read());
}

void match_hw::thread_or_cond_fu_654_p2() {
    or_cond_fu_654_p2 = (sel_tmp5_fu_649_p2.read() | sel_tmp3_fu_638_p2.read());
}

void match_hw::thread_outTrackMuon_hwBX_V() {
    if (esl_seteq<1,1,1>(ap_condition_329.read(), ap_const_boolean_1)) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) {
            outTrackMuon_hwBX_V = inTrack_hwBX_V.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) {
            outTrackMuon_hwBX_V = ap_const_lv3_0;
        } else {
            outTrackMuon_hwBX_V = "XXX";
        }
    } else {
        outTrackMuon_hwBX_V = "XXX";
    }
}

void match_hw::thread_outTrackMuon_hwBX_V_ap_vld() {
    if (((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter25.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) || 
         (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter25.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())))) {
        outTrackMuon_hwBX_V_ap_vld = ap_const_logic_1;
    } else {
        outTrackMuon_hwBX_V_ap_vld = ap_const_logic_0;
    }
}

void match_hw::thread_outTrackMuon_hwEta_V() {
    if (esl_seteq<1,1,1>(ap_condition_329.read(), ap_const_boolean_1)) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) {
            outTrackMuon_hwEta_V = ap_pipeline_reg_pp0_iter24_inMuon_hwEta_V_read_reg_947.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) {
            outTrackMuon_hwEta_V = ap_const_lv9_0;
        } else {
            outTrackMuon_hwEta_V =  (sc_lv<9>) ("XXXXXXXXX");
        }
    } else {
        outTrackMuon_hwEta_V =  (sc_lv<9>) ("XXXXXXXXX");
    }
}

void match_hw::thread_outTrackMuon_hwEta_V_ap_vld() {
    if (((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter25.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) || 
         (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter25.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())))) {
        outTrackMuon_hwEta_V_ap_vld = ap_const_logic_1;
    } else {
        outTrackMuon_hwEta_V_ap_vld = ap_const_logic_0;
    }
}

void match_hw::thread_outTrackMuon_hwPhi_V() {
    if (esl_seteq<1,1,1>(ap_condition_329.read(), ap_const_boolean_1)) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) {
            outTrackMuon_hwPhi_V = inMuon_hwPhi_V.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) {
            outTrackMuon_hwPhi_V = ap_const_lv10_0;
        } else {
            outTrackMuon_hwPhi_V =  (sc_lv<10>) ("XXXXXXXXXX");
        }
    } else {
        outTrackMuon_hwPhi_V =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void match_hw::thread_outTrackMuon_hwPhi_V_ap_vld() {
    if (((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter25.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) || 
         (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter25.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())))) {
        outTrackMuon_hwPhi_V_ap_vld = ap_const_logic_1;
    } else {
        outTrackMuon_hwPhi_V_ap_vld = ap_const_logic_0;
    }
}

void match_hw::thread_outTrackMuon_hwPt_V() {
    if (esl_seteq<1,1,1>(ap_condition_329.read(), ap_const_boolean_1)) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) {
            outTrackMuon_hwPt_V = inTrack_hwPt_V.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) {
            outTrackMuon_hwPt_V = ap_const_lv14_0;
        } else {
            outTrackMuon_hwPt_V =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
        }
    } else {
        outTrackMuon_hwPt_V =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
    }
}

void match_hw::thread_outTrackMuon_hwPt_V_ap_vld() {
    if (((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter25.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) || 
         (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter25.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())))) {
        outTrackMuon_hwPt_V_ap_vld = ap_const_logic_1;
    } else {
        outTrackMuon_hwPt_V_ap_vld = ap_const_logic_0;
    }
}

void match_hw::thread_outTrackMuon_hwQ_V() {
    if (esl_seteq<1,1,1>(ap_condition_329.read(), ap_const_boolean_1)) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) {
            outTrackMuon_hwQ_V = inTrack_hwQ_V.read();
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) {
            outTrackMuon_hwQ_V = ap_const_lv1_0;
        } else {
            outTrackMuon_hwQ_V =  (sc_lv<1>) ("X");
        }
    } else {
        outTrackMuon_hwQ_V =  (sc_lv<1>) ("X");
    }
}

void match_hw::thread_outTrackMuon_hwQ_V_ap_vld() {
    if (((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter25.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) || 
         (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter25.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())))) {
        outTrackMuon_hwQ_V_ap_vld = ap_const_logic_1;
    } else {
        outTrackMuon_hwQ_V_ap_vld = ap_const_logic_0;
    }
}

void match_hw::thread_outTrackMuon_hwValid_V() {
    if (esl_seteq<1,1,1>(ap_condition_329.read(), ap_const_boolean_1)) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) {
            outTrackMuon_hwValid_V = ap_const_lv1_1;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) {
            outTrackMuon_hwValid_V = ap_const_lv1_0;
        } else {
            outTrackMuon_hwValid_V =  (sc_lv<1>) ("X");
        }
    } else {
        outTrackMuon_hwValid_V =  (sc_lv<1>) ("X");
    }
}

void match_hw::thread_outTrackMuon_hwValid_V_ap_vld() {
    if (((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter25.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())) || 
         (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter25.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_41_fu_936_p2.read())))) {
        outTrackMuon_hwValid_V_ap_vld = ap_const_logic_1;
    } else {
        outTrackMuon_hwValid_V_ap_vld = ap_const_logic_0;
    }
}

void match_hw::thread_p_1_fu_911_p3() {
    p_1_fu_911_p3 = (!tmp_49_fu_873_p3.read()[0].is_01())? sc_lv<4>(): ((tmp_49_fu_873_p3.read()[0].to_bool())? p_s_fu_903_p3.read(): ret_V_fu_863_p4.read());
}

void match_hw::thread_p_2_fu_765_p3() {
    p_2_fu_765_p3 = (!ap_pipeline_reg_pp0_iter22_isneg_reg_1007.read()[0].is_01())? sc_lv<14>(): ((ap_pipeline_reg_pp0_iter22_isneg_reg_1007.read()[0].to_bool())? ap_const_lv14_3FFF: ap_const_lv14_0);
}

void match_hw::thread_p_3_fu_797_p3() {
    p_3_fu_797_p3 = (!ap_pipeline_reg_pp0_iter22_isneg_1_reg_1032.read()[0].is_01())? sc_lv<10>(): ((ap_pipeline_reg_pp0_iter22_isneg_1_reg_1032.read()[0].to_bool())? ap_const_lv10_3FF: ap_const_lv10_0);
}

void match_hw::thread_p_Result_1_fu_521_p1() {
    p_Result_1_fu_521_p1 = esl_zext<54,53>(tmp_22_fu_514_p3.read());
}

void match_hw::thread_p_Result_s_6_fu_881_p4() {
    p_Result_s_6_fu_881_p4 = p_Val2_3_fu_857_p2.read().range(9, 4);
}

void match_hw::thread_p_Result_s_fu_442_p1() {
    p_Result_s_fu_442_p1 = esl_zext<54,53>(tmp_4_fu_435_p3.read());
}

void match_hw::thread_p_Val2_2_fu_829_p3() {
    p_Val2_2_fu_829_p3 = (!ap_pipeline_reg_pp0_iter23_or_cond2_reg_1165.read()[0].is_01())? sc_lv<14>(): ((ap_pipeline_reg_pp0_iter23_or_cond2_reg_1165.read()[0].to_bool())? newSel2_reg_1195.read(): ap_const_lv14_0);
}

void match_hw::thread_p_Val2_3_fu_857_p2() {
    p_Val2_3_fu_857_p2 = (!tmp_37_fu_835_p1.read().is_01() || !tmp_46_cast_fu_853_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_37_fu_835_p1.read()) - sc_bigint<15>(tmp_46_cast_fu_853_p1.read()));
}

void match_hw::thread_p_s_fu_903_p3() {
    p_s_fu_903_p3 = (!tmp_40_fu_891_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_40_fu_891_p2.read()[0].to_bool())? ret_V_fu_863_p4.read(): ret_V_1_fu_897_p2.read());
}

void match_hw::thread_ret_V_1_fu_897_p2() {
    ret_V_1_fu_897_p2 = (!ap_const_lv4_1.is_01() || !ret_V_fu_863_p4.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(ret_V_fu_863_p4.read()));
}

void match_hw::thread_ret_V_fu_863_p4() {
    ret_V_fu_863_p4 = p_Val2_3_fu_857_p2.read().range(13, 10);
}

void match_hw::thread_sel_tmp10_fu_705_p2() {
    sel_tmp10_fu_705_p2 = (tmp_27_reg_1117.read() & sel_tmp9_fu_700_p2.read());
}

void match_hw::thread_sel_tmp11_fu_581_p2() {
    sel_tmp11_fu_581_p2 = (sel_tmp31_demorgan_fu_576_p2.read() ^ ap_const_lv1_1);
}

void match_hw::thread_sel_tmp12_fu_587_p2() {
    sel_tmp12_fu_587_p2 = (tmp_24_fu_538_p2.read() & sel_tmp11_fu_581_p2.read());
}

void match_hw::thread_sel_tmp13_fu_710_p2() {
    sel_tmp13_fu_710_p2 = (sel_tmp12_reg_1139.read() & tmp_29_reg_1128.read());
}

void match_hw::thread_sel_tmp14_demorgan_fu_628_p2() {
    sel_tmp14_demorgan_fu_628_p2 = (sel_tmp6_demorgan_reg_1090.read() | tmp_3_reg_1062.read());
}

void match_hw::thread_sel_tmp14_fu_718_p2() {
    sel_tmp14_fu_718_p2 = (sel_tmp39_demorgan_fu_714_p2.read() ^ ap_const_lv1_1);
}

void match_hw::thread_sel_tmp15_fu_724_p2() {
    sel_tmp15_fu_724_p2 = (tmp_30_fu_682_p2.read() & sel_tmp14_fu_718_p2.read());
}

void match_hw::thread_sel_tmp16_fu_730_p2() {
    sel_tmp16_fu_730_p2 = (tmp_29_reg_1128.read() ^ ap_const_lv1_1);
}

void match_hw::thread_sel_tmp17_fu_735_p2() {
    sel_tmp17_fu_735_p2 = (sel_tmp12_reg_1139.read() & sel_tmp16_fu_730_p2.read());
}

void match_hw::thread_sel_tmp1_fu_614_p2() {
    sel_tmp1_fu_614_p2 = (ap_pipeline_reg_pp0_iter21_tmp_1_reg_1018.read() ^ ap_const_lv1_1);
}

void match_hw::thread_sel_tmp2_fu_619_p2() {
    sel_tmp2_fu_619_p2 = (tmp_8_reg_1073.read() & sel_tmp1_fu_614_p2.read());
}

void match_hw::thread_sel_tmp31_demorgan_fu_576_p2() {
    sel_tmp31_demorgan_fu_576_p2 = (tmp_23_reg_1043.read() | tmp_27_fu_561_p2.read());
}

void match_hw::thread_sel_tmp39_demorgan_fu_714_p2() {
    sel_tmp39_demorgan_fu_714_p2 = (sel_tmp31_demorgan_reg_1134.read() | tmp_24_reg_1106.read());
}

void match_hw::thread_sel_tmp3_fu_638_p2() {
    sel_tmp3_fu_638_p2 = (tmp_2_fu_596_p2.read() & sel_tmp_fu_632_p2.read());
}

void match_hw::thread_sel_tmp4_fu_644_p2() {
    sel_tmp4_fu_644_p2 = (tmp_s_reg_1084.read() ^ ap_const_lv1_1);
}

void match_hw::thread_sel_tmp5_fu_649_p2() {
    sel_tmp5_fu_649_p2 = (sel_tmp7_reg_1095.read() & sel_tmp4_fu_644_p2.read());
}

void match_hw::thread_sel_tmp6_demorgan_fu_497_p2() {
    sel_tmp6_demorgan_fu_497_p2 = (tmp_1_reg_1018.read() | tmp_8_fu_482_p2.read());
}

void match_hw::thread_sel_tmp6_fu_502_p2() {
    sel_tmp6_fu_502_p2 = (sel_tmp6_demorgan_fu_497_p2.read() ^ ap_const_lv1_1);
}

void match_hw::thread_sel_tmp7_fu_508_p2() {
    sel_tmp7_fu_508_p2 = (tmp_3_fu_459_p2.read() & sel_tmp6_fu_502_p2.read());
}

void match_hw::thread_sel_tmp8_fu_624_p2() {
    sel_tmp8_fu_624_p2 = (sel_tmp7_reg_1095.read() & tmp_s_reg_1084.read());
}

void match_hw::thread_sel_tmp9_fu_700_p2() {
    sel_tmp9_fu_700_p2 = (ap_pipeline_reg_pp0_iter21_tmp_23_reg_1043.read() ^ ap_const_lv1_1);
}

void match_hw::thread_sel_tmp_fu_632_p2() {
    sel_tmp_fu_632_p2 = (sel_tmp14_demorgan_fu_628_p2.read() ^ ap_const_lv1_1);
}

void match_hw::thread_sh_amt_1_cast_fu_679_p1() {
    sh_amt_1_cast_fu_679_p1 = esl_sext<32,12>(sh_amt_1_reg_1111.read());
}

void match_hw::thread_sh_amt_1_fu_553_p3() {
    sh_amt_1_fu_553_p3 = (!tmp_24_fu_538_p2.read()[0].is_01())? sc_lv<12>(): ((tmp_24_fu_538_p2.read()[0].to_bool())? tmp_25_fu_543_p2.read(): tmp_26_fu_548_p2.read());
}

void match_hw::thread_sh_amt_cast_fu_593_p1() {
    sh_amt_cast_fu_593_p1 = esl_sext<32,12>(sh_amt_reg_1067.read());
}

void match_hw::thread_sh_amt_fu_474_p3() {
    sh_amt_fu_474_p3 = (!tmp_3_fu_459_p2.read()[0].is_01())? sc_lv<12>(): ((tmp_3_fu_459_p2.read()[0].to_bool())? tmp_5_fu_464_p2.read(): tmp_7_fu_469_p2.read());
}

void match_hw::thread_tmp_10_fu_601_p1() {
    tmp_10_fu_601_p1 = esl_zext<54,32>(sh_amt_cast_fu_593_p1.read());
}

void match_hw::thread_tmp_11_fu_605_p2() {
    tmp_11_fu_605_p2 = (!man_V_2_reg_1057.read().is_01() || !tmp_10_fu_601_p1.read().is_01())? sc_lv<54>(): sc_bigint<54>(man_V_2_reg_1057.read()) >> (unsigned short)tmp_10_fu_601_p1.read().to_uint();
}

void match_hw::thread_tmp_12_fu_772_p1() {
    tmp_12_fu_772_p1 = esl_sext<32,14>(ap_pipeline_reg_pp0_iter22_tmp_16_reg_1078.read());
}

void match_hw::thread_tmp_13_fu_775_p2() {
    tmp_13_fu_775_p2 = (!sh_amt_cast_reg_1145.read().is_01())? sc_lv<32>(): tmp_12_fu_772_p1.read() << (unsigned short)sh_amt_cast_reg_1145.read().to_uint();
}

void match_hw::thread_tmp_14_fu_311_p3() {
    tmp_14_fu_311_p3 = esl_concat<1,1>(tmp_36_reg_952.read(), ap_const_lv1_0);
}

void match_hw::thread_tmp_15_fu_374_p1() {
    tmp_15_fu_374_p1 = ireg_V_fu_345_p1.read().range(52-1, 0);
}

void match_hw::thread_tmp_16_fu_487_p1() {
    tmp_16_fu_487_p1 = man_V_2_fu_452_p3.read().range(14-1, 0);
}

void match_hw::thread_tmp_17_fu_318_p2() {
    tmp_17_fu_318_p2 = (!ap_const_lv2_1.is_01() || !tmp_14_fu_311_p3.read().is_01())? sc_lv<2>(): (sc_biguint<2>(ap_const_lv2_1) - sc_biguint<2>(tmp_14_fu_311_p3.read()));
}

void match_hw::thread_tmp_1_fu_378_p2() {
    tmp_1_fu_378_p2 = (!tmp_9_fu_348_p1.read().is_01() || !ap_const_lv63_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_9_fu_348_p1.read() == ap_const_lv63_0);
}

void match_hw::thread_tmp_21_fu_415_p1() {
    tmp_21_fu_415_p1 = esl_zext<12,11>(exp_tmp_V_1_fu_405_p4.read());
}

void match_hw::thread_tmp_22_fu_514_p3() {
    tmp_22_fu_514_p3 = esl_concat<1,52>(ap_const_lv1_1, tmp_45_reg_1038.read());
}

void match_hw::thread_tmp_23_fu_423_p2() {
    tmp_23_fu_423_p2 = (!tmp_43_fu_393_p1.read().is_01() || !ap_const_lv63_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_43_fu_393_p1.read() == ap_const_lv63_0);
}

void match_hw::thread_tmp_24_fu_538_p2() {
    tmp_24_fu_538_p2 = (!F2_1_reg_1049.read().is_01() || !ap_const_lv12_6.is_01())? sc_lv<1>(): (sc_bigint<12>(F2_1_reg_1049.read()) > sc_bigint<12>(ap_const_lv12_6));
}

void match_hw::thread_tmp_25_fu_543_p2() {
    tmp_25_fu_543_p2 = (!ap_const_lv12_FFA.is_01() || !F2_1_reg_1049.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_FFA) + sc_biguint<12>(F2_1_reg_1049.read()));
}

void match_hw::thread_tmp_26_fu_548_p2() {
    tmp_26_fu_548_p2 = (!ap_const_lv12_6.is_01() || !F2_1_reg_1049.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_6) - sc_biguint<12>(F2_1_reg_1049.read()));
}

void match_hw::thread_tmp_27_fu_561_p2() {
    tmp_27_fu_561_p2 = (!F2_1_reg_1049.read().is_01() || !ap_const_lv12_6.is_01())? sc_lv<1>(): sc_lv<1>(F2_1_reg_1049.read() == ap_const_lv12_6);
}

void match_hw::thread_tmp_28_fu_610_p1() {
    tmp_28_fu_610_p1 = tmp_11_fu_605_p2.read().range(14-1, 0);
}

void match_hw::thread_tmp_29_fu_570_p2() {
    tmp_29_fu_570_p2 = (!sh_amt_1_fu_553_p3.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_biguint<12>(sh_amt_1_fu_553_p3.read()) < sc_biguint<12>(ap_const_lv12_36));
}

void match_hw::thread_tmp_2_fu_596_p2() {
    tmp_2_fu_596_p2 = (!sh_amt_reg_1067.read().is_01() || !ap_const_lv12_E.is_01())? sc_lv<1>(): (sc_biguint<12>(sh_amt_reg_1067.read()) < sc_biguint<12>(ap_const_lv12_E));
}

void match_hw::thread_tmp_30_fu_682_p2() {
    tmp_30_fu_682_p2 = (!sh_amt_1_reg_1111.read().is_01() || !ap_const_lv12_A.is_01())? sc_lv<1>(): (sc_biguint<12>(sh_amt_1_reg_1111.read()) < sc_biguint<12>(ap_const_lv12_A));
}

void match_hw::thread_tmp_31_fu_687_p1() {
    tmp_31_fu_687_p1 = esl_zext<54,32>(sh_amt_1_cast_fu_679_p1.read());
}

void match_hw::thread_tmp_32_fu_691_p2() {
    tmp_32_fu_691_p2 = (!man_V_5_reg_1101.read().is_01() || !tmp_31_fu_687_p1.read().is_01())? sc_lv<54>(): sc_bigint<54>(man_V_5_reg_1101.read()) >> (unsigned short)tmp_31_fu_687_p1.read().to_uint();
}

void match_hw::thread_tmp_33_fu_780_p1() {
    tmp_33_fu_780_p1 = tmp_13_fu_775_p2.read().range(14-1, 0);
}

void match_hw::thread_tmp_34_fu_804_p1() {
    tmp_34_fu_804_p1 = esl_sext<32,10>(ap_pipeline_reg_pp0_iter22_tmp_46_reg_1122.read());
}

void match_hw::thread_tmp_35_fu_807_p2() {
    tmp_35_fu_807_p2 = (!sh_amt_1_cast_reg_1170.read().is_01())? sc_lv<32>(): tmp_34_fu_804_p1.read() << (unsigned short)sh_amt_1_cast_reg_1170.read().to_uint();
}

void match_hw::thread_tmp_37_fu_835_p1() {
    tmp_37_fu_835_p1 = esl_zext<15,14>(p_Val2_2_fu_829_p3.read());
}

void match_hw::thread_tmp_38_fu_839_p3() {
    tmp_38_fu_839_p3 = (!ap_pipeline_reg_pp0_iter23_or_cond5_reg_1190.read()[0].is_01())? sc_lv<10>(): ((ap_pipeline_reg_pp0_iter23_or_cond5_reg_1190.read()[0].to_bool())? newSel6_reg_1200.read(): ap_const_lv10_0);
}

void match_hw::thread_tmp_39_fu_845_p3() {
    tmp_39_fu_845_p3 = esl_concat<10,4>(tmp_38_fu_839_p3.read(), ap_const_lv4_0);
}

void match_hw::thread_tmp_3_fu_459_p2() {
    tmp_3_fu_459_p2 = (!F2_reg_1024.read().is_01() || !ap_const_lv12_A.is_01())? sc_lv<1>(): (sc_bigint<12>(F2_reg_1024.read()) > sc_bigint<12>(ap_const_lv12_A));
}

void match_hw::thread_tmp_40_fu_891_p2() {
    tmp_40_fu_891_p2 = (!p_Result_s_6_fu_881_p4.read().is_01() || !ap_const_lv6_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_s_6_fu_881_p4.read() == ap_const_lv6_0);
}

void match_hw::thread_tmp_41_fu_936_p2() {
    tmp_41_fu_936_p2 = (!abs_fu_929_p3.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): sc_lv<1>(abs_fu_929_p3.read() == ap_const_lv4_0);
}

void match_hw::thread_tmp_42_fu_285_p3() {
    tmp_42_fu_285_p3 = inMuon_hwEta_V.read().range(8, 8);
}

void match_hw::thread_tmp_43_fu_393_p1() {
    tmp_43_fu_393_p1 = ireg_V_1_fu_390_p1.read().range(63-1, 0);
}

void match_hw::thread_tmp_45_fu_419_p1() {
    tmp_45_fu_419_p1 = ireg_V_1_fu_390_p1.read().range(52-1, 0);
}

void match_hw::thread_tmp_46_cast_fu_853_p1() {
    tmp_46_cast_fu_853_p1 = esl_sext<15,14>(tmp_39_fu_845_p3.read());
}

void match_hw::thread_tmp_46_fu_566_p1() {
    tmp_46_fu_566_p1 = man_V_5_fu_531_p3.read().range(10-1, 0);
}

void match_hw::thread_tmp_47_fu_696_p1() {
    tmp_47_fu_696_p1 = tmp_32_fu_691_p2.read().range(10-1, 0);
}

void match_hw::thread_tmp_48_fu_812_p1() {
    tmp_48_fu_812_p1 = tmp_35_fu_807_p2.read().range(10-1, 0);
}

void match_hw::thread_tmp_49_fu_873_p3() {
    tmp_49_fu_873_p3 = p_Val2_3_fu_857_p2.read().range(13, 13);
}

void match_hw::thread_tmp_4_fu_435_p3() {
    tmp_4_fu_435_p3 = esl_concat<1,52>(ap_const_lv1_1, tmp_15_reg_1013.read());
}

void match_hw::thread_tmp_52_i_fu_293_p2() {
    tmp_52_i_fu_293_p2 = (!ap_const_lv9_0.is_01() || !inMuon_hwEta_V.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_0) - sc_biguint<9>(inMuon_hwEta_V.read()));
}

void match_hw::thread_tmp_53_i_cast_fu_299_p1() {
    tmp_53_i_cast_fu_299_p1 = esl_zext<10,9>(tmp_52_i_fu_293_p2.read());
}

void match_hw::thread_tmp_54_i_fu_303_p3() {
    tmp_54_i_fu_303_p3 = (!tmp_42_fu_285_p3.read()[0].is_01())? sc_lv<10>(): ((tmp_42_fu_285_p3.read()[0].to_bool())? tmp_53_i_cast_fu_299_p1.read(): x_assign_cast_fu_281_p1.read());
}

void match_hw::thread_tmp_5_fu_464_p2() {
    tmp_5_fu_464_p2 = (!ap_const_lv12_FF6.is_01() || !F2_reg_1024.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_FF6) + sc_biguint<12>(F2_reg_1024.read()));
}

void match_hw::thread_tmp_6_fu_370_p1() {
    tmp_6_fu_370_p1 = esl_zext<12,11>(exp_tmp_V_fu_360_p4.read());
}

void match_hw::thread_tmp_7_fu_469_p2() {
    tmp_7_fu_469_p2 = (!ap_const_lv12_A.is_01() || !F2_reg_1024.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_A) - sc_biguint<12>(F2_reg_1024.read()));
}

void match_hw::thread_tmp_8_fu_482_p2() {
    tmp_8_fu_482_p2 = (!F2_reg_1024.read().is_01() || !ap_const_lv12_A.is_01())? sc_lv<1>(): sc_lv<1>(F2_reg_1024.read() == ap_const_lv12_A);
}

void match_hw::thread_tmp_9_fu_348_p1() {
    tmp_9_fu_348_p1 = ireg_V_fu_345_p1.read().range(63-1, 0);
}

void match_hw::thread_tmp_s_fu_491_p2() {
    tmp_s_fu_491_p2 = (!sh_amt_fu_474_p3.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_biguint<12>(sh_amt_fu_474_p3.read()) < sc_biguint<12>(ap_const_lv12_36));
}

void match_hw::thread_x_assign_cast_fu_281_p1() {
    x_assign_cast_fu_281_p1 = esl_sext<10,9>(inMuon_hwEta_V.read());
}

void match_hw::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm =  (sc_lv<1>) ("X");
            break;
    }
}

void match_hw::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inTrack_hwRinv_V\" :  \"" << inTrack_hwRinv_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inTrack_hwPt_V\" :  \"" << inTrack_hwPt_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inTrack_hwSinhEta_V\" :  \"" << inTrack_hwSinhEta_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inTrack_hwEta_V\" :  \"" << inTrack_hwEta_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inTrack_hwPhi_V\" :  \"" << inTrack_hwPhi_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inTrack_hwPhiGlobal_V\" :  \"" << inTrack_hwPhiGlobal_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inTrack_hwZ0_V\" :  \"" << inTrack_hwZ0_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inTrack_hwSector_V\" :  \"" << inTrack_hwSector_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inTrack_hwQ_V\" :  \"" << inTrack_hwQ_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inTrack_hwX2_V\" :  \"" << inTrack_hwX2_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inTrack_hwValid_V\" :  \"" << inTrack_hwValid_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inTrack_hwBX_V\" :  \"" << inTrack_hwBX_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inMuon_hwPt_V\" :  \"" << inMuon_hwPt_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inMuon_hwEta_V\" :  \"" << inMuon_hwEta_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inMuon_hwPhi_V\" :  \"" << inMuon_hwPhi_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inMuon_hwQ_V\" :  \"" << inMuon_hwQ_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inMuon_hwValid_V\" :  \"" << inMuon_hwValid_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inMuon_hwBX_V\" :  \"" << inMuon_hwBX_V.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"inMuon_hwQuality_V\" :  \"" << inMuon_hwQuality_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outTrackMuon_hwPt_V\" :  \"" << outTrackMuon_hwPt_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outTrackMuon_hwPt_V_ap_vld\" :  \"" << outTrackMuon_hwPt_V_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outTrackMuon_hwEta_V\" :  \"" << outTrackMuon_hwEta_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outTrackMuon_hwEta_V_ap_vld\" :  \"" << outTrackMuon_hwEta_V_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outTrackMuon_hwPhi_V\" :  \"" << outTrackMuon_hwPhi_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outTrackMuon_hwPhi_V_ap_vld\" :  \"" << outTrackMuon_hwPhi_V_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outTrackMuon_hwQ_V\" :  \"" << outTrackMuon_hwQ_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outTrackMuon_hwQ_V_ap_vld\" :  \"" << outTrackMuon_hwQ_V_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outTrackMuon_hwValid_V\" :  \"" << outTrackMuon_hwValid_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outTrackMuon_hwValid_V_ap_vld\" :  \"" << outTrackMuon_hwValid_V_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outTrackMuon_hwBX_V\" :  \"" << outTrackMuon_hwBX_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"outTrackMuon_hwBX_V_ap_vld\" :  \"" << outTrackMuon_hwBX_V_ap_vld.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"outTrackMuon_hwQuality_V\" :  \"" << outTrackMuon_hwQuality_V.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

