-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity calc_eta_hw is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    hwSinhEta_V : IN STD_LOGIC_VECTOR (13 downto 0);
    outEta_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    outEta_V_ap_vld : OUT STD_LOGIC );
end;


architecture behav of calc_eta_hw is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "calc_eta_hw,hls_ip_2016_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7vx690tffg1927-2,HLS_INPUT_CLOCK=4.115000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=3.490000,HLS_SYN_LAT=27,HLS_SYN_TPT=1,HLS_SYN_MEM=6,HLS_SYN_DSP=23,HLS_SYN_FF=2420,HLS_SYN_LUT=2521}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";
    constant ap_const_lv64_3F600000972ECF2E : STD_LOGIC_VECTOR (63 downto 0) := "0011111101100000000000000000000010010111001011101100111100101110";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv14_2000 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv54_0 : STD_LOGIC_VECTOR (53 downto 0) := "000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv63_0 : STD_LOGIC_VECTOR (62 downto 0) := "000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv12_433 : STD_LOGIC_VECTOR (11 downto 0) := "010000110011";
    constant ap_const_lv12_A : STD_LOGIC_VECTOR (11 downto 0) := "000000001010";
    constant ap_const_lv12_FF6 : STD_LOGIC_VECTOR (11 downto 0) := "111111110110";
    constant ap_const_lv12_E : STD_LOGIC_VECTOR (11 downto 0) := "000000001110";
    constant ap_const_lv12_36 : STD_LOGIC_VECTOR (11 downto 0) := "000000110110";
    constant ap_const_lv14_3FFF : STD_LOGIC_VECTOR (13 downto 0) := "11111111111111";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal tmp_fu_166_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter3_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter4_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter5_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter6_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter7_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter8_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter9_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter10_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter11_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter12_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter13_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter14_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter15_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter16_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter17_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter18_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter19_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter20_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter21_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter22_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter23_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter24_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter25_tmp_reg_559 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_fu_179_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal r_V_reg_569 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_160_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_2_reg_579 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_163_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_3_reg_584 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_150_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal v_assign_1_reg_589 : STD_LOGIC_VECTOR (63 downto 0);
    signal isneg_1_fu_196_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isneg_1_reg_594 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter17_isneg_1_reg_594 : STD_LOGIC_VECTOR (0 downto 0);
    signal man_V_5_fu_240_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_5_reg_599 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_9_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_606 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter17_tmp_9_reg_606 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_260_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_610 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter17_tmp_13_reg_610 : STD_LOGIC_VECTOR (0 downto 0);
    signal sh_amt_1_fu_278_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sh_amt_1_reg_614 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_16_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_622 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter17_tmp_16_reg_622 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_155_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal v_assign_reg_626 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_24_fu_301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_reg_631 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_306_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_30_reg_635 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_22_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_reg_640 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_fu_326_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_39_reg_644 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_34_fu_330_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_34_reg_649 : STD_LOGIC_VECTOR (13 downto 0);
    signal isneg_fu_340_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal isneg_reg_654 : STD_LOGIC_VECTOR (0 downto 0);
    signal man_V_2_fu_384_p3 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_2_reg_659 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_1_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_666 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter18_tmp_1_reg_666 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_670 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter18_tmp_8_reg_670 : STD_LOGIC_VECTOR (0 downto 0);
    signal sh_amt_fu_422_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sh_amt_reg_674 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_12_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_682 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter18_tmp_12_reg_682 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_3_fu_436_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_27_fu_457_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_21_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_reg_699 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_2_fu_468_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_38_fu_484_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_38_reg_708 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_33_fu_488_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_arcsinh_fu_142_ap_return : STD_LOGIC_VECTOR (11 downto 0);
    signal inhwEta_V_reg_718 : STD_LOGIC_VECTOR (11 downto 0);
    signal ret_V_cast_fu_517_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal ret_V_cast_reg_723 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_41_fu_521_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_reg_730 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_fu_529_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_reg_734 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_arcsinh_fu_142_ap_start : STD_LOGIC;
    signal grp_arcsinh_fu_142_ap_done : STD_LOGIC;
    signal grp_arcsinh_fu_142_ap_idle : STD_LOGIC;
    signal grp_arcsinh_fu_142_ap_ready : STD_LOGIC;
    signal ap_phi_precharge_reg_pp0_iter17_absSinhEta_V_reg_97 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_phi_precharge_reg_pp0_iter18_absSinhEta_V_reg_97 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_phi_precharge_reg_pp0_iter19_absSinhEta_V_reg_97 : STD_LOGIC_VECTOR (13 downto 0);
    signal absSinhEta_V_phi_fu_101_p24 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_phi_precharge_reg_pp0_iter16_absSinhEta_V_reg_97 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_s_fu_551_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_phi_precharge_reg_pp0_iter27_p_1_reg_132 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_1_phi_fu_135_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_phi_precharge_reg_pp0_iter26_p_1_reg_132 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_reg_grp_arcsinh_fu_142_ap_start : STD_LOGIC := '0';
    signal grp_fu_160_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_163_p0 : STD_LOGIC_VECTOR (63 downto 0);
    signal ireg_V_1_fu_189_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal exp_tmp_V_1_fu_204_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_31_fu_218_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_5_fu_222_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal p_Result_1_fu_230_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_4_fu_234_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_23_fu_192_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_7_fu_214_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal F2_1_fu_254_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_14_fu_266_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_15_fu_272_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_37_fu_298_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sh_amt_1_cast1_fu_292_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sh_amt_1_cast_fu_295_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_28_fu_317_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_29_fu_321_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal ireg_V_fu_333_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal exp_tmp_V_fu_348_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_20_fu_362_p1 : STD_LOGIC_VECTOR (51 downto 0);
    signal tmp_4_fu_366_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal p_Result_s_fu_374_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal man_V_1_fu_378_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_17_fu_336_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal tmp_6_fu_358_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal F2_fu_398_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_10_fu_410_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_11_fu_416_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_36_fu_449_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sh_amt_cast2_fu_443_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sh_amt_cast_fu_446_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_25_fu_475_p1 : STD_LOGIC_VECTOR (53 downto 0);
    signal tmp_26_fu_479_p2 : STD_LOGIC_VECTOR (53 downto 0);
    signal inhwEta_V_2_cast_fu_491_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal inhwEta_V_1_fu_494_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_Val2_4_call_ret_fu_500_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_40_fu_507_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Result_s_12_fu_533_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_32_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ret_V_fu_546_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_idle_pp0 : STD_LOGIC;
    signal ap_condition_398 : BOOLEAN;
    signal ap_condition_340 : BOOLEAN;
    signal ap_condition_320 : BOOLEAN;
    signal ap_condition_393 : BOOLEAN;
    signal ap_condition_330 : BOOLEAN;
    signal ap_condition_403 : BOOLEAN;
    signal ap_condition_406 : BOOLEAN;
    signal ap_condition_411 : BOOLEAN;
    signal ap_condition_306 : BOOLEAN;
    signal ap_condition_367 : BOOLEAN;
    signal ap_condition_431 : BOOLEAN;

    component arcsinh IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_V_read : IN STD_LOGIC_VECTOR (13 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component calc_eta_hw_dmul_dEe IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component calc_eta_hw_sitodeOg IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component calc_eta_hw_sitodfYi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;



begin
    grp_arcsinh_fu_142 : component arcsinh
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_arcsinh_fu_142_ap_start,
        ap_done => grp_arcsinh_fu_142_ap_done,
        ap_idle => grp_arcsinh_fu_142_ap_idle,
        ap_ready => grp_arcsinh_fu_142_ap_ready,
        data_V_read => absSinhEta_V_phi_fu_101_p24,
        ap_return => grp_arcsinh_fu_142_ap_return);

    calc_eta_hw_dmul_dEe_U4 : component calc_eta_hw_dmul_dEe
    generic map (
        ID => 1,
        NUM_STAGE => 10,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_2_reg_579,
        din1 => ap_const_lv64_3F600000972ECF2E,
        ce => ap_const_logic_1,
        dout => grp_fu_150_p2);

    calc_eta_hw_dmul_dEe_U5 : component calc_eta_hw_dmul_dEe
    generic map (
        ID => 1,
        NUM_STAGE => 10,
        din0_WIDTH => 64,
        din1_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_3_reg_584,
        din1 => ap_const_lv64_3F600000972ECF2E,
        ce => ap_const_logic_1,
        dout => grp_fu_155_p2);

    calc_eta_hw_sitodeOg_U6 : component calc_eta_hw_sitodeOg
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 32,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_160_p0,
        ce => ap_const_logic_1,
        dout => grp_fu_160_p1);

    calc_eta_hw_sitodfYi_U7 : component calc_eta_hw_sitodfYi
    generic map (
        ID => 1,
        NUM_STAGE => 6,
        din0_WIDTH => 64,
        dout_WIDTH => 64)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_163_p0,
        ce => ap_const_logic_1,
        dout => grp_fu_163_p1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_arcsinh_fu_142_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_arcsinh_fu_142_ap_start <= ap_const_logic_0;
            else
                if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter18))) then 
                    ap_reg_grp_arcsinh_fu_142_ap_start <= ap_const_logic_1;
                elsif ((ap_const_logic_1 = grp_arcsinh_fu_142_ap_ready)) then 
                    ap_reg_grp_arcsinh_fu_142_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_precharge_reg_pp0_iter17_absSinhEta_V_reg_97_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_398 = ap_const_boolean_1)) then
                if (((ap_pipeline_reg_pp0_iter15_tmp_reg_559 = ap_const_lv1_0) and not((ap_const_lv1_0 = tmp_9_fu_248_p2)))) then 
                    ap_phi_precharge_reg_pp0_iter17_absSinhEta_V_reg_97 <= ap_const_lv14_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter17_absSinhEta_V_reg_97 <= ap_phi_precharge_reg_pp0_iter16_absSinhEta_V_reg_97;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_precharge_reg_pp0_iter18_absSinhEta_V_reg_97_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and not((ap_pipeline_reg_pp0_iter16_tmp_reg_559 = ap_const_lv1_0)) and (ap_const_logic_1 = ap_enable_reg_pp0_iter17) and not((ap_const_lv1_0 = tmp_1_fu_392_p2))) or (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter16_tmp_reg_559 = ap_const_lv1_0) and (ap_const_lv1_0 = tmp_9_reg_606) and (ap_const_lv1_0 = tmp_16_reg_622) and (ap_const_lv1_0 = tmp_13_reg_610) and (ap_const_lv1_0 = tmp_24_fu_301_p2) and (ap_const_logic_1 = ap_enable_reg_pp0_iter17)))) then 
                ap_phi_precharge_reg_pp0_iter18_absSinhEta_V_reg_97 <= ap_const_lv14_0;
            elsif ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter17))) then 
                ap_phi_precharge_reg_pp0_iter18_absSinhEta_V_reg_97 <= ap_phi_precharge_reg_pp0_iter17_absSinhEta_V_reg_97;
            end if; 
        end if;
    end process;

    ap_phi_precharge_reg_pp0_iter19_absSinhEta_V_reg_97_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_367 = ap_const_boolean_1)) then
                if ((ap_condition_306 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter19_absSinhEta_V_reg_97 <= p_3_fu_436_p3;
                elsif ((ap_condition_411 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter19_absSinhEta_V_reg_97 <= tmp_30_reg_635;
                elsif ((ap_condition_406 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter19_absSinhEta_V_reg_97 <= tmp_39_reg_644;
                elsif ((ap_condition_403 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter19_absSinhEta_V_reg_97 <= tmp_34_reg_649;
                elsif ((ap_condition_330 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter19_absSinhEta_V_reg_97 <= p_2_fu_468_p3;
                elsif ((ap_condition_393 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter19_absSinhEta_V_reg_97 <= ap_const_lv14_0;
                elsif ((ap_condition_320 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter19_absSinhEta_V_reg_97 <= tmp_27_fu_457_p2;
                elsif ((ap_condition_340 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter19_absSinhEta_V_reg_97 <= tmp_33_fu_488_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter19_absSinhEta_V_reg_97 <= ap_phi_precharge_reg_pp0_iter18_absSinhEta_V_reg_97;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_precharge_reg_pp0_iter27_p_1_reg_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_431 = ap_const_boolean_1)) then
                if ((ap_const_lv1_0 = tmp_41_fu_521_p3)) then 
                    ap_phi_precharge_reg_pp0_iter27_p_1_reg_132 <= ret_V_cast_fu_517_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter27_p_1_reg_132 <= ap_phi_precharge_reg_pp0_iter26_p_1_reg_132;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then
                ap_pipeline_reg_pp0_iter10_tmp_reg_559 <= ap_pipeline_reg_pp0_iter9_tmp_reg_559;
                ap_pipeline_reg_pp0_iter11_tmp_reg_559 <= ap_pipeline_reg_pp0_iter10_tmp_reg_559;
                ap_pipeline_reg_pp0_iter12_tmp_reg_559 <= ap_pipeline_reg_pp0_iter11_tmp_reg_559;
                ap_pipeline_reg_pp0_iter13_tmp_reg_559 <= ap_pipeline_reg_pp0_iter12_tmp_reg_559;
                ap_pipeline_reg_pp0_iter14_tmp_reg_559 <= ap_pipeline_reg_pp0_iter13_tmp_reg_559;
                ap_pipeline_reg_pp0_iter15_tmp_reg_559 <= ap_pipeline_reg_pp0_iter14_tmp_reg_559;
                ap_pipeline_reg_pp0_iter16_tmp_reg_559 <= ap_pipeline_reg_pp0_iter15_tmp_reg_559;
                ap_pipeline_reg_pp0_iter17_isneg_1_reg_594 <= isneg_1_reg_594;
                ap_pipeline_reg_pp0_iter17_tmp_13_reg_610 <= tmp_13_reg_610;
                ap_pipeline_reg_pp0_iter17_tmp_16_reg_622 <= tmp_16_reg_622;
                ap_pipeline_reg_pp0_iter17_tmp_9_reg_606 <= tmp_9_reg_606;
                ap_pipeline_reg_pp0_iter17_tmp_reg_559 <= ap_pipeline_reg_pp0_iter16_tmp_reg_559;
                ap_pipeline_reg_pp0_iter18_tmp_12_reg_682 <= tmp_12_reg_682;
                ap_pipeline_reg_pp0_iter18_tmp_1_reg_666 <= tmp_1_reg_666;
                ap_pipeline_reg_pp0_iter18_tmp_8_reg_670 <= tmp_8_reg_670;
                ap_pipeline_reg_pp0_iter18_tmp_reg_559 <= ap_pipeline_reg_pp0_iter17_tmp_reg_559;
                ap_pipeline_reg_pp0_iter19_tmp_reg_559 <= ap_pipeline_reg_pp0_iter18_tmp_reg_559;
                ap_pipeline_reg_pp0_iter20_tmp_reg_559 <= ap_pipeline_reg_pp0_iter19_tmp_reg_559;
                ap_pipeline_reg_pp0_iter21_tmp_reg_559 <= ap_pipeline_reg_pp0_iter20_tmp_reg_559;
                ap_pipeline_reg_pp0_iter22_tmp_reg_559 <= ap_pipeline_reg_pp0_iter21_tmp_reg_559;
                ap_pipeline_reg_pp0_iter23_tmp_reg_559 <= ap_pipeline_reg_pp0_iter22_tmp_reg_559;
                ap_pipeline_reg_pp0_iter24_tmp_reg_559 <= ap_pipeline_reg_pp0_iter23_tmp_reg_559;
                ap_pipeline_reg_pp0_iter25_tmp_reg_559 <= ap_pipeline_reg_pp0_iter24_tmp_reg_559;
                ap_pipeline_reg_pp0_iter2_tmp_reg_559 <= ap_pipeline_reg_pp0_iter1_tmp_reg_559;
                ap_pipeline_reg_pp0_iter3_tmp_reg_559 <= ap_pipeline_reg_pp0_iter2_tmp_reg_559;
                ap_pipeline_reg_pp0_iter4_tmp_reg_559 <= ap_pipeline_reg_pp0_iter3_tmp_reg_559;
                ap_pipeline_reg_pp0_iter5_tmp_reg_559 <= ap_pipeline_reg_pp0_iter4_tmp_reg_559;
                ap_pipeline_reg_pp0_iter6_tmp_reg_559 <= ap_pipeline_reg_pp0_iter5_tmp_reg_559;
                ap_pipeline_reg_pp0_iter7_tmp_reg_559 <= ap_pipeline_reg_pp0_iter6_tmp_reg_559;
                ap_pipeline_reg_pp0_iter8_tmp_reg_559 <= ap_pipeline_reg_pp0_iter7_tmp_reg_559;
                ap_pipeline_reg_pp0_iter9_tmp_reg_559 <= ap_pipeline_reg_pp0_iter8_tmp_reg_559;
                inhwEta_V_reg_718 <= grp_arcsinh_fu_142_ap_return;
                ret_V_cast_reg_723 <= ret_V_cast_fu_517_p1;
                tmp_41_reg_730 <= p_Val2_4_call_ret_fu_500_p3(12 downto 12);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then
                ap_pipeline_reg_pp0_iter1_tmp_reg_559 <= tmp_reg_559;
                tmp_reg_559 <= hwSinhEta_V(13 downto 13);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter15_tmp_reg_559 = ap_const_lv1_0))) then
                isneg_1_reg_594 <= ireg_V_1_fu_189_p1(63 downto 63);
                man_V_5_reg_599 <= man_V_5_fu_240_p3;
                tmp_9_reg_606 <= tmp_9_fu_248_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and not((ap_pipeline_reg_pp0_iter16_tmp_reg_559 = ap_const_lv1_0)))) then
                isneg_reg_654 <= ireg_V_fu_333_p1(63 downto 63);
                man_V_2_reg_659 <= man_V_2_fu_384_p3;
                tmp_1_reg_666 <= tmp_1_fu_392_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and not((tmp_fu_166_p3 = ap_const_lv1_0)))) then
                r_V_reg_569 <= r_V_fu_179_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter15_tmp_reg_559 = ap_const_lv1_0) and (ap_const_lv1_0 = tmp_9_fu_248_p2))) then
                sh_amt_1_reg_614 <= sh_amt_1_fu_278_p3;
                tmp_13_reg_610 <= tmp_13_fu_260_p2;
                tmp_16_reg_622 <= tmp_16_fu_286_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and not((ap_pipeline_reg_pp0_iter16_tmp_reg_559 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_fu_392_p2))) then
                sh_amt_reg_674 <= sh_amt_fu_422_p3;
                tmp_12_reg_682 <= tmp_12_fu_430_p2;
                tmp_8_reg_670 <= tmp_8_fu_404_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and not((ap_pipeline_reg_pp0_iter17_tmp_reg_559 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_reg_666) and (ap_const_lv1_0 = tmp_12_reg_682) and not((ap_const_lv1_0 = tmp_8_reg_670)))) then
                tmp_19_reg_699 <= tmp_19_fu_463_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter16_tmp_reg_559 = ap_const_lv1_0) and (ap_const_lv1_0 = tmp_9_reg_606) and (ap_const_lv1_0 = tmp_16_reg_622) and not((ap_const_lv1_0 = tmp_13_reg_610)))) then
                tmp_22_reg_640 <= tmp_22_fu_312_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter16_tmp_reg_559 = ap_const_lv1_0) and (ap_const_lv1_0 = tmp_9_reg_606) and (ap_const_lv1_0 = tmp_16_reg_622) and (ap_const_lv1_0 = tmp_13_reg_610))) then
                tmp_24_reg_631 <= tmp_24_fu_301_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter4_tmp_reg_559 = ap_const_lv1_0))) then
                tmp_2_reg_579 <= grp_fu_160_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter16_tmp_reg_559 = ap_const_lv1_0) and (ap_const_lv1_0 = tmp_9_reg_606) and (ap_const_lv1_0 = tmp_16_reg_622) and (ap_const_lv1_0 = tmp_13_reg_610) and not((ap_const_lv1_0 = tmp_24_fu_301_p2)))) then
                tmp_30_reg_635 <= tmp_30_fu_306_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter16_tmp_reg_559 = ap_const_lv1_0) and (ap_const_lv1_0 = tmp_9_reg_606) and not((ap_const_lv1_0 = tmp_16_reg_622)))) then
                tmp_34_reg_649 <= tmp_34_fu_330_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and not((ap_pipeline_reg_pp0_iter17_tmp_reg_559 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_reg_666) and (ap_const_lv1_0 = tmp_12_reg_682) and not((ap_const_lv1_0 = tmp_8_reg_670)) and not((ap_const_lv1_0 = tmp_19_fu_463_p2)))) then
                tmp_38_reg_708 <= tmp_38_fu_484_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter16_tmp_reg_559 = ap_const_lv1_0) and (ap_const_lv1_0 = tmp_9_reg_606) and (ap_const_lv1_0 = tmp_16_reg_622) and not((ap_const_lv1_0 = tmp_13_reg_610)) and not((ap_const_lv1_0 = tmp_22_fu_312_p2)))) then
                tmp_39_reg_644 <= tmp_39_fu_326_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and not((ap_pipeline_reg_pp0_iter5_tmp_reg_559 = ap_const_lv1_0)))) then
                tmp_3_reg_584 <= grp_fu_163_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and not((ap_const_lv1_0 = tmp_41_fu_521_p3)))) then
                tmp_42_reg_734 <= tmp_42_fu_529_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter14_tmp_reg_559 = ap_const_lv1_0))) then
                v_assign_1_reg_589 <= grp_fu_150_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and not((ap_pipeline_reg_pp0_iter15_tmp_reg_559 = ap_const_lv1_0)))) then
                v_assign_reg_626 <= grp_fu_155_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_enable_reg_pp0_iter0, ap_pipeline_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    F2_1_fu_254_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(tmp_7_fu_214_p1));
    F2_fu_398_p2 <= std_logic_vector(unsigned(ap_const_lv12_433) - unsigned(tmp_6_fu_358_p1));

    absSinhEta_V_phi_fu_101_p24_assign_proc : process(ap_enable_reg_pp0_iter19, ap_pipeline_reg_pp0_iter18_tmp_reg_559, ap_pipeline_reg_pp0_iter18_tmp_1_reg_666, ap_pipeline_reg_pp0_iter18_tmp_8_reg_670, ap_pipeline_reg_pp0_iter18_tmp_12_reg_682, tmp_19_reg_699, tmp_38_reg_708, ap_phi_precharge_reg_pp0_iter19_absSinhEta_V_reg_97)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter19) and not((ap_pipeline_reg_pp0_iter18_tmp_reg_559 = ap_const_lv1_0)) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter18_tmp_1_reg_666) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter18_tmp_12_reg_682) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter18_tmp_8_reg_670)) and not((ap_const_lv1_0 = tmp_19_reg_699)))) then 
            absSinhEta_V_phi_fu_101_p24 <= tmp_38_reg_708;
        else 
            absSinhEta_V_phi_fu_101_p24 <= ap_phi_precharge_reg_pp0_iter19_absSinhEta_V_reg_97;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0 downto 0);

    ap_condition_306_assign_proc : process(ap_pipeline_reg_pp0_iter17_tmp_reg_559, ap_pipeline_reg_pp0_iter17_tmp_9_reg_606, ap_pipeline_reg_pp0_iter17_tmp_13_reg_610, ap_pipeline_reg_pp0_iter17_tmp_16_reg_622, tmp_22_reg_640)
    begin
                ap_condition_306 <= ((ap_pipeline_reg_pp0_iter17_tmp_reg_559 = ap_const_lv1_0) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter17_tmp_9_reg_606) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter17_tmp_16_reg_622) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter17_tmp_13_reg_610)) and (ap_const_lv1_0 = tmp_22_reg_640));
    end process;


    ap_condition_320_assign_proc : process(ap_pipeline_reg_pp0_iter17_tmp_reg_559, tmp_1_reg_666, tmp_8_reg_670, tmp_12_reg_682, tmp_21_fu_452_p2)
    begin
                ap_condition_320 <= (not((ap_pipeline_reg_pp0_iter17_tmp_reg_559 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_reg_666) and (ap_const_lv1_0 = tmp_12_reg_682) and (ap_const_lv1_0 = tmp_8_reg_670) and not((ap_const_lv1_0 = tmp_21_fu_452_p2)));
    end process;


    ap_condition_330_assign_proc : process(ap_pipeline_reg_pp0_iter17_tmp_reg_559, tmp_1_reg_666, tmp_8_reg_670, tmp_12_reg_682, tmp_19_fu_463_p2)
    begin
                ap_condition_330 <= (not((ap_pipeline_reg_pp0_iter17_tmp_reg_559 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_reg_666) and (ap_const_lv1_0 = tmp_12_reg_682) and not((ap_const_lv1_0 = tmp_8_reg_670)) and (ap_const_lv1_0 = tmp_19_fu_463_p2));
    end process;


    ap_condition_340_assign_proc : process(ap_pipeline_reg_pp0_iter17_tmp_reg_559, tmp_1_reg_666, tmp_12_reg_682)
    begin
                ap_condition_340 <= (not((ap_pipeline_reg_pp0_iter17_tmp_reg_559 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_reg_666) and not((ap_const_lv1_0 = tmp_12_reg_682)));
    end process;


    ap_condition_367_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter18)
    begin
                ap_condition_367 <= (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter18));
    end process;


    ap_condition_393_assign_proc : process(ap_pipeline_reg_pp0_iter17_tmp_reg_559, tmp_1_reg_666, tmp_8_reg_670, tmp_12_reg_682, tmp_21_fu_452_p2)
    begin
                ap_condition_393 <= (not((ap_pipeline_reg_pp0_iter17_tmp_reg_559 = ap_const_lv1_0)) and (ap_const_lv1_0 = tmp_1_reg_666) and (ap_const_lv1_0 = tmp_12_reg_682) and (ap_const_lv1_0 = tmp_8_reg_670) and (ap_const_lv1_0 = tmp_21_fu_452_p2));
    end process;


    ap_condition_398_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter16)
    begin
                ap_condition_398 <= (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter16));
    end process;


    ap_condition_403_assign_proc : process(ap_pipeline_reg_pp0_iter17_tmp_reg_559, ap_pipeline_reg_pp0_iter17_tmp_9_reg_606, ap_pipeline_reg_pp0_iter17_tmp_16_reg_622)
    begin
                ap_condition_403 <= ((ap_pipeline_reg_pp0_iter17_tmp_reg_559 = ap_const_lv1_0) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter17_tmp_9_reg_606) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter17_tmp_16_reg_622)));
    end process;


    ap_condition_406_assign_proc : process(ap_pipeline_reg_pp0_iter17_tmp_reg_559, ap_pipeline_reg_pp0_iter17_tmp_9_reg_606, ap_pipeline_reg_pp0_iter17_tmp_13_reg_610, ap_pipeline_reg_pp0_iter17_tmp_16_reg_622, tmp_22_reg_640)
    begin
                ap_condition_406 <= ((ap_pipeline_reg_pp0_iter17_tmp_reg_559 = ap_const_lv1_0) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter17_tmp_9_reg_606) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter17_tmp_16_reg_622) and not((ap_const_lv1_0 = ap_pipeline_reg_pp0_iter17_tmp_13_reg_610)) and not((ap_const_lv1_0 = tmp_22_reg_640)));
    end process;


    ap_condition_411_assign_proc : process(ap_pipeline_reg_pp0_iter17_tmp_reg_559, ap_pipeline_reg_pp0_iter17_tmp_9_reg_606, ap_pipeline_reg_pp0_iter17_tmp_13_reg_610, ap_pipeline_reg_pp0_iter17_tmp_16_reg_622, tmp_24_reg_631)
    begin
                ap_condition_411 <= ((ap_pipeline_reg_pp0_iter17_tmp_reg_559 = ap_const_lv1_0) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter17_tmp_9_reg_606) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter17_tmp_16_reg_622) and (ap_const_lv1_0 = ap_pipeline_reg_pp0_iter17_tmp_13_reg_610) and not((ap_const_lv1_0 = tmp_24_reg_631)));
    end process;


    ap_condition_431_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter26)
    begin
                ap_condition_431 <= (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter26));
    end process;


    ap_done_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter27)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter27))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2) and (ap_const_logic_0 = ap_enable_reg_pp0_iter3) and (ap_const_logic_0 = ap_enable_reg_pp0_iter4) and (ap_const_logic_0 = ap_enable_reg_pp0_iter5) and (ap_const_logic_0 = ap_enable_reg_pp0_iter6) and (ap_const_logic_0 = ap_enable_reg_pp0_iter7) and (ap_const_logic_0 = ap_enable_reg_pp0_iter8) and (ap_const_logic_0 = ap_enable_reg_pp0_iter9) and (ap_const_logic_0 = ap_enable_reg_pp0_iter10) and (ap_const_logic_0 = ap_enable_reg_pp0_iter11) and (ap_const_logic_0 = ap_enable_reg_pp0_iter12) and (ap_const_logic_0 = ap_enable_reg_pp0_iter13) and (ap_const_logic_0 = ap_enable_reg_pp0_iter14) and (ap_const_logic_0 = ap_enable_reg_pp0_iter15) and (ap_const_logic_0 = ap_enable_reg_pp0_iter16) and (ap_const_logic_0 = ap_enable_reg_pp0_iter17) and (ap_const_logic_0 = ap_enable_reg_pp0_iter18) and (ap_const_logic_0 = ap_enable_reg_pp0_iter19) and (ap_const_logic_0 = ap_enable_reg_pp0_iter20) and (ap_const_logic_0 = ap_enable_reg_pp0_iter21) and (ap_const_logic_0 = ap_enable_reg_pp0_iter22) and (ap_const_logic_0 = ap_enable_reg_pp0_iter23) and (ap_const_logic_0 = ap_enable_reg_pp0_iter24) and (ap_const_logic_0 = ap_enable_reg_pp0_iter25) and (ap_const_logic_0 = ap_enable_reg_pp0_iter26) and (ap_const_logic_0 = ap_enable_reg_pp0_iter27))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_precharge_reg_pp0_iter16_absSinhEta_V_reg_97 <= "XXXXXXXXXXXXXX";
    ap_phi_precharge_reg_pp0_iter26_p_1_reg_132 <= "XXXXXXXXXXXXXX";

    ap_pipeline_idle_pp0_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2) and (ap_const_logic_0 = ap_enable_reg_pp0_iter3) and (ap_const_logic_0 = ap_enable_reg_pp0_iter4) and (ap_const_logic_0 = ap_enable_reg_pp0_iter5) and (ap_const_logic_0 = ap_enable_reg_pp0_iter6) and (ap_const_logic_0 = ap_enable_reg_pp0_iter7) and (ap_const_logic_0 = ap_enable_reg_pp0_iter8) and (ap_const_logic_0 = ap_enable_reg_pp0_iter9) and (ap_const_logic_0 = ap_enable_reg_pp0_iter10) and (ap_const_logic_0 = ap_enable_reg_pp0_iter11) and (ap_const_logic_0 = ap_enable_reg_pp0_iter12) and (ap_const_logic_0 = ap_enable_reg_pp0_iter13) and (ap_const_logic_0 = ap_enable_reg_pp0_iter14) and (ap_const_logic_0 = ap_enable_reg_pp0_iter15) and (ap_const_logic_0 = ap_enable_reg_pp0_iter16) and (ap_const_logic_0 = ap_enable_reg_pp0_iter17) and (ap_const_logic_0 = ap_enable_reg_pp0_iter18) and (ap_const_logic_0 = ap_enable_reg_pp0_iter19) and (ap_const_logic_0 = ap_enable_reg_pp0_iter20) and (ap_const_logic_0 = ap_enable_reg_pp0_iter21) and (ap_const_logic_0 = ap_enable_reg_pp0_iter22) and (ap_const_logic_0 = ap_enable_reg_pp0_iter23) and (ap_const_logic_0 = ap_enable_reg_pp0_iter24) and (ap_const_logic_0 = ap_enable_reg_pp0_iter25) and (ap_const_logic_0 = ap_enable_reg_pp0_iter26))) then 
            ap_pipeline_idle_pp0 <= ap_const_logic_1;
        else 
            ap_pipeline_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    exp_tmp_V_1_fu_204_p4 <= ireg_V_1_fu_189_p1(62 downto 52);
    exp_tmp_V_fu_348_p4 <= ireg_V_fu_333_p1(62 downto 52);
    grp_arcsinh_fu_142_ap_start <= ap_reg_grp_arcsinh_fu_142_ap_start;
        grp_fu_160_p0 <= std_logic_vector(resize(signed(hwSinhEta_V),32));

    grp_fu_163_p0 <= std_logic_vector(resize(unsigned(r_V_reg_569),64));
    inhwEta_V_1_fu_494_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(inhwEta_V_2_cast_fu_491_p1));
    inhwEta_V_2_cast_fu_491_p1 <= std_logic_vector(resize(unsigned(inhwEta_V_reg_718),13));
    ireg_V_1_fu_189_p1 <= v_assign_1_reg_589;
    ireg_V_fu_333_p1 <= v_assign_reg_626;
    isneg_1_fu_196_p3 <= ireg_V_1_fu_189_p1(63 downto 63);
    isneg_fu_340_p3 <= ireg_V_fu_333_p1(63 downto 63);
    man_V_1_fu_378_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(p_Result_s_fu_374_p1));
    man_V_2_fu_384_p3 <= 
        man_V_1_fu_378_p2 when (isneg_fu_340_p3(0) = '1') else 
        p_Result_s_fu_374_p1;
    man_V_4_fu_234_p2 <= std_logic_vector(unsigned(ap_const_lv54_0) - unsigned(p_Result_1_fu_230_p1));
    man_V_5_fu_240_p3 <= 
        man_V_4_fu_234_p2 when (isneg_1_fu_196_p3(0) = '1') else 
        p_Result_1_fu_230_p1;
    outEta_V <= p_1_phi_fu_135_p4;

    outEta_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter27)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter27))) then 
            outEta_V_ap_vld <= ap_const_logic_1;
        else 
            outEta_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    p_1_phi_fu_135_p4_assign_proc : process(ap_enable_reg_pp0_iter27, tmp_41_reg_730, p_s_fu_551_p3, ap_phi_precharge_reg_pp0_iter27_p_1_reg_132)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter27) and not((ap_const_lv1_0 = tmp_41_reg_730)))) then 
            p_1_phi_fu_135_p4 <= p_s_fu_551_p3;
        else 
            p_1_phi_fu_135_p4 <= ap_phi_precharge_reg_pp0_iter27_p_1_reg_132;
        end if; 
    end process;

    p_2_fu_468_p3 <= 
        ap_const_lv14_3FFF when (isneg_reg_654(0) = '1') else 
        ap_const_lv14_0;
    p_3_fu_436_p3 <= 
        ap_const_lv14_3FFF when (ap_pipeline_reg_pp0_iter17_isneg_1_reg_594(0) = '1') else 
        ap_const_lv14_0;
    p_Result_1_fu_230_p1 <= std_logic_vector(resize(unsigned(tmp_5_fu_222_p3),54));
    p_Result_s_12_fu_533_p3 <= (tmp_42_reg_734 & ap_const_lv9_0);
    p_Result_s_fu_374_p1 <= std_logic_vector(resize(unsigned(tmp_4_fu_366_p3),54));
    p_Val2_4_call_ret_fu_500_p3 <= 
        inhwEta_V_1_fu_494_p2 when (ap_pipeline_reg_pp0_iter25_tmp_reg_559(0) = '1') else 
        inhwEta_V_2_cast_fu_491_p1;
    p_s_fu_551_p3 <= 
        ret_V_cast_reg_723 when (tmp_32_fu_540_p2(0) = '1') else 
        ret_V_fu_546_p2;
    r_V_fu_179_p2 <= (hwSinhEta_V xor ap_const_lv14_2000);
        ret_V_cast_fu_517_p1 <= std_logic_vector(resize(signed(tmp_40_fu_507_p4),14));

    ret_V_fu_546_p2 <= std_logic_vector(unsigned(ap_const_lv14_1) + unsigned(ret_V_cast_reg_723));
        sh_amt_1_cast1_fu_292_p1 <= std_logic_vector(resize(signed(sh_amt_1_reg_614),14));

        sh_amt_1_cast_fu_295_p1 <= std_logic_vector(resize(signed(sh_amt_1_reg_614),32));

    sh_amt_1_fu_278_p3 <= 
        tmp_14_fu_266_p2 when (tmp_13_fu_260_p2(0) = '1') else 
        tmp_15_fu_272_p2;
        sh_amt_cast2_fu_443_p1 <= std_logic_vector(resize(signed(sh_amt_reg_674),14));

        sh_amt_cast_fu_446_p1 <= std_logic_vector(resize(signed(sh_amt_reg_674),32));

    sh_amt_fu_422_p3 <= 
        tmp_10_fu_410_p2 when (tmp_8_fu_404_p2(0) = '1') else 
        tmp_11_fu_416_p2;
    tmp_10_fu_410_p2 <= std_logic_vector(unsigned(F2_fu_398_p2) + unsigned(ap_const_lv12_FF6));
    tmp_11_fu_416_p2 <= std_logic_vector(unsigned(ap_const_lv12_A) - unsigned(F2_fu_398_p2));
    tmp_12_fu_430_p2 <= "1" when (F2_fu_398_p2 = ap_const_lv12_A) else "0";
    tmp_13_fu_260_p2 <= "1" when (signed(F2_1_fu_254_p2) > signed(ap_const_lv12_A)) else "0";
    tmp_14_fu_266_p2 <= std_logic_vector(unsigned(F2_1_fu_254_p2) + unsigned(ap_const_lv12_FF6));
    tmp_15_fu_272_p2 <= std_logic_vector(unsigned(ap_const_lv12_A) - unsigned(F2_1_fu_254_p2));
    tmp_16_fu_286_p2 <= "1" when (F2_1_fu_254_p2 = ap_const_lv12_A) else "0";
    tmp_17_fu_336_p1 <= ireg_V_fu_333_p1(63 - 1 downto 0);
    tmp_19_fu_463_p2 <= "1" when (unsigned(sh_amt_reg_674) < unsigned(ap_const_lv12_36)) else "0";
    tmp_1_fu_392_p2 <= "1" when (tmp_17_fu_336_p1 = ap_const_lv63_0) else "0";
    tmp_20_fu_362_p1 <= ireg_V_fu_333_p1(52 - 1 downto 0);
    tmp_21_fu_452_p2 <= "1" when (unsigned(sh_amt_reg_674) < unsigned(ap_const_lv12_E)) else "0";
    tmp_22_fu_312_p2 <= "1" when (unsigned(sh_amt_1_reg_614) < unsigned(ap_const_lv12_36)) else "0";
    tmp_23_fu_192_p1 <= ireg_V_1_fu_189_p1(63 - 1 downto 0);
    tmp_24_fu_301_p2 <= "1" when (unsigned(sh_amt_1_reg_614) < unsigned(ap_const_lv12_E)) else "0";
    tmp_25_fu_475_p1 <= std_logic_vector(resize(unsigned(sh_amt_cast_fu_446_p1),54));
    tmp_26_fu_479_p2 <= std_logic_vector(shift_right(signed(man_V_2_reg_659),to_integer(unsigned('0' & tmp_25_fu_475_p1(31-1 downto 0)))));
    tmp_27_fu_457_p2 <= std_logic_vector(shift_left(unsigned(tmp_36_fu_449_p1),to_integer(unsigned('0' & sh_amt_cast2_fu_443_p1(14-1 downto 0)))));
    tmp_28_fu_317_p1 <= std_logic_vector(resize(unsigned(sh_amt_1_cast_fu_295_p1),54));
    tmp_29_fu_321_p2 <= std_logic_vector(shift_right(signed(man_V_5_reg_599),to_integer(unsigned('0' & tmp_28_fu_317_p1(31-1 downto 0)))));
    tmp_30_fu_306_p2 <= std_logic_vector(shift_left(unsigned(tmp_37_fu_298_p1),to_integer(unsigned('0' & sh_amt_1_cast1_fu_292_p1(14-1 downto 0)))));
    tmp_31_fu_218_p1 <= ireg_V_1_fu_189_p1(52 - 1 downto 0);
    tmp_32_fu_540_p2 <= "1" when (p_Result_s_12_fu_533_p3 = ap_const_lv10_0) else "0";
    tmp_33_fu_488_p1 <= man_V_2_reg_659(14 - 1 downto 0);
    tmp_34_fu_330_p1 <= man_V_5_reg_599(14 - 1 downto 0);
    tmp_36_fu_449_p1 <= man_V_2_reg_659(14 - 1 downto 0);
    tmp_37_fu_298_p1 <= man_V_5_reg_599(14 - 1 downto 0);
    tmp_38_fu_484_p1 <= tmp_26_fu_479_p2(14 - 1 downto 0);
    tmp_39_fu_326_p1 <= tmp_29_fu_321_p2(14 - 1 downto 0);
    tmp_40_fu_507_p4 <= p_Val2_4_call_ret_fu_500_p3(12 downto 1);
    tmp_41_fu_521_p3 <= p_Val2_4_call_ret_fu_500_p3(12 downto 12);
    tmp_42_fu_529_p1 <= p_Val2_4_call_ret_fu_500_p3(1 - 1 downto 0);
    tmp_4_fu_366_p3 <= (ap_const_lv1_1 & tmp_20_fu_362_p1);
    tmp_5_fu_222_p3 <= (ap_const_lv1_1 & tmp_31_fu_218_p1);
    tmp_6_fu_358_p1 <= std_logic_vector(resize(unsigned(exp_tmp_V_fu_348_p4),12));
    tmp_7_fu_214_p1 <= std_logic_vector(resize(unsigned(exp_tmp_V_1_fu_204_p4),12));
    tmp_8_fu_404_p2 <= "1" when (signed(F2_fu_398_p2) > signed(ap_const_lv12_A)) else "0";
    tmp_9_fu_248_p2 <= "1" when (tmp_23_fu_192_p1 = ap_const_lv63_0) else "0";
    tmp_fu_166_p3 <= hwSinhEta_V(13 downto 13);
end behav;
