-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity deta_LUT_deta_tabibs_rom is 
    generic(
             dwidth     : integer := 5; 
             awidth     : integer := 10; 
             mem_size    : integer := 1024
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of deta_LUT_deta_tabibs_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 to 33=> "11011", 34 to 69=> "11010", 70 to 106=> "11001", 107 to 143=> "11000", 144 to 179=> "10111", 
    180 to 216=> "10110", 217 to 253=> "10101", 254 to 289=> "10100", 290 to 326=> "10011", 327 to 363=> "10010", 
    364 to 399=> "10001", 400 to 436=> "10000", 437 to 473=> "01111", 474 to 509=> "01110", 510 to 546=> "01101", 
    547 to 583=> "01100", 584 to 619=> "01011", 620 to 656=> "01010", 657 to 693=> "01001", 694 to 729=> "01000", 
    730 to 766=> "00111", 767 to 803=> "00110", 804 to 839=> "00101", 840 to 876=> "00100", 877 to 913=> "00011", 
    914 to 949=> "00010", 950 to 986=> "00001", 987 to 1023=> "00000" );


attribute EQUIVALENT_REGISTER_REMOVAL : string;
begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity deta_LUT_deta_tabibs is
    generic (
        DataWidth : INTEGER := 5;
        AddressRange : INTEGER := 1024;
        AddressWidth : INTEGER := 10);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of deta_LUT_deta_tabibs is
    component deta_LUT_deta_tabibs_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    deta_LUT_deta_tabibs_rom_U :  component deta_LUT_deta_tabibs_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


