// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "rinvToInvPt.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic rinvToInvPt::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic rinvToInvPt::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> rinvToInvPt::ap_ST_fsm_pp0_stage0 = "1";
const sc_lv<32> rinvToInvPt::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> rinvToInvPt::ap_const_lv1_1 = "1";
const sc_lv<32> rinvToInvPt::ap_const_lv32_8 = "1000";
const sc_lv<32> rinvToInvPt::ap_const_lv32_1F = "11111";
const sc_lv<14> rinvToInvPt::ap_const_lv14_0 = "00000000000000";
const sc_lv<22> rinvToInvPt::ap_const_lv22_0 = "0000000000000000000000";
const sc_lv<25> rinvToInvPt::ap_const_lv25_1 = "1";
const sc_lv<32> rinvToInvPt::ap_const_lv32_E = "1110";
const sc_lv<18> rinvToInvPt::ap_const_lv18_0 = "000000000000000000";
const sc_lv<21> rinvToInvPt::ap_const_lv21_0 = "000000000000000000000";
const sc_lv<21> rinvToInvPt::ap_const_lv21_1FFF80 = "111111111111110000000";
const sc_lv<32> rinvToInvPt::ap_const_lv32_FFFFFF51 = "11111111111111111111111101010001";
const sc_lv<32> rinvToInvPt::ap_const_lv32_400000 = "10000000000000000000000";

rinvToInvPt::rinvToInvPt(sc_module_name name) : sc_module(name), mVcdFile(0) {
    rinvToInvPt_table1_U = new rinvToInvPt_rinvTbkb("rinvToInvPt_table1_U");
    rinvToInvPt_table1_U->clk(ap_clk);
    rinvToInvPt_table1_U->reset(ap_rst);
    rinvToInvPt_table1_U->address0(rinvToInvPt_table1_address0);
    rinvToInvPt_table1_U->ce0(rinvToInvPt_table1_ce0);
    rinvToInvPt_table1_U->q0(rinvToInvPt_table1_q0);
    rinvToInvPt_mac_mcud_U1 = new rinvToInvPt_mac_mcud<1,3,9,24,24,32>("rinvToInvPt_mac_mcud_U1");
    rinvToInvPt_mac_mcud_U1->clk(ap_clk);
    rinvToInvPt_mac_mcud_U1->reset(ap_rst);
    rinvToInvPt_mac_mcud_U1->din0(grp_fu_217_p0);
    rinvToInvPt_mac_mcud_U1->din1(data_V);
    rinvToInvPt_mac_mcud_U1->din2(grp_fu_217_p2);
    rinvToInvPt_mac_mcud_U1->ce(ap_var_for_const0);
    rinvToInvPt_mac_mcud_U1->dout(grp_fu_217_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_ap_pipeline_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_217_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_grp_fu_217_p2);
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_icmp_fu_171_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( tmp_10_fu_161_p4 );

    SC_METHOD(thread_index_fu_145_p3);
    sensitive << ( tmp_6_fu_130_p1 );
    sensitive << ( tmp_3_fu_104_p3 );
    sensitive << ( tmp_5_fu_137_p3 );

    SC_METHOD(thread_p_Result_2_fu_111_p3);
    sensitive << ( tmp_4_reg_243 );

    SC_METHOD(thread_res_V);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( storemerge1_fu_204_p3 );

    SC_METHOD(thread_res_V_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );

    SC_METHOD(thread_ret_V_cast_cast_fu_101_p1);
    sensitive << ( tmp_2_reg_237 );

    SC_METHOD(thread_ret_V_fu_124_p2);
    sensitive << ( ret_V_cast_cast_fu_101_p1 );

    SC_METHOD(thread_rinvToInvPt_table1_address0);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_1_fu_177_p1 );

    SC_METHOD(thread_rinvToInvPt_table1_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_sel_tmp1_fu_181_p2);
    sensitive << ( ap_pipeline_reg_pp0_iter4_tmp_9_reg_253 );

    SC_METHOD(thread_sel_tmp2_fu_186_p2);
    sensitive << ( ap_pipeline_reg_pp0_iter4_icmp_reg_259 );
    sensitive << ( sel_tmp1_fu_181_p2 );

    SC_METHOD(thread_sel_tmp_cast_fu_191_p3);
    sensitive << ( sel_tmp2_fu_186_p2 );

    SC_METHOD(thread_storemerge1_fu_204_p3);
    sensitive << ( rinvToInvPt_table1_q0 );
    sensitive << ( tmp_8_fu_199_p2 );
    sensitive << ( sel_tmp_cast_fu_191_p3 );

    SC_METHOD(thread_tmp_10_fu_161_p4);
    sensitive << ( index_fu_145_p3 );

    SC_METHOD(thread_tmp_1_fu_177_p1);
    sensitive << ( index_reg_248 );

    SC_METHOD(thread_tmp_3_fu_104_p3);
    sensitive << ( r_V_reg_232 );

    SC_METHOD(thread_tmp_4_fu_98_p1);
    sensitive << ( grp_fu_217_p3 );

    SC_METHOD(thread_tmp_5_fu_137_p3);
    sensitive << ( tmp_7_fu_118_p2 );
    sensitive << ( tmp_6_fu_130_p1 );
    sensitive << ( tmp_s_fu_133_p1 );

    SC_METHOD(thread_tmp_6_fu_130_p1);
    sensitive << ( tmp_2_reg_237 );

    SC_METHOD(thread_tmp_7_fu_118_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( p_Result_2_fu_111_p3 );

    SC_METHOD(thread_tmp_8_fu_199_p2);
    sensitive << ( ap_pipeline_reg_pp0_iter4_tmp_9_reg_253 );
    sensitive << ( sel_tmp2_fu_186_p2 );

    SC_METHOD(thread_tmp_s_fu_133_p1);
    sensitive << ( ret_V_fu_124_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_pipeline_idle_pp0 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "1";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "rinvToInvPt_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V, "(port)data_V");
    sc_trace(mVcdFile, res_V, "(port)res_V");
    sc_trace(mVcdFile, res_V_ap_vld, "(port)res_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, rinvToInvPt_table1_address0, "rinvToInvPt_table1_address0");
    sc_trace(mVcdFile, rinvToInvPt_table1_ce0, "rinvToInvPt_table1_ce0");
    sc_trace(mVcdFile, rinvToInvPt_table1_q0, "rinvToInvPt_table1_q0");
    sc_trace(mVcdFile, grp_fu_217_p3, "grp_fu_217_p3");
    sc_trace(mVcdFile, r_V_reg_232, "r_V_reg_232");
    sc_trace(mVcdFile, tmp_2_reg_237, "tmp_2_reg_237");
    sc_trace(mVcdFile, tmp_4_fu_98_p1, "tmp_4_fu_98_p1");
    sc_trace(mVcdFile, tmp_4_reg_243, "tmp_4_reg_243");
    sc_trace(mVcdFile, index_fu_145_p3, "index_fu_145_p3");
    sc_trace(mVcdFile, index_reg_248, "index_reg_248");
    sc_trace(mVcdFile, tmp_9_reg_253, "tmp_9_reg_253");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter4_tmp_9_reg_253, "ap_pipeline_reg_pp0_iter4_tmp_9_reg_253");
    sc_trace(mVcdFile, icmp_fu_171_p2, "icmp_fu_171_p2");
    sc_trace(mVcdFile, icmp_reg_259, "icmp_reg_259");
    sc_trace(mVcdFile, ap_pipeline_reg_pp0_iter4_icmp_reg_259, "ap_pipeline_reg_pp0_iter4_icmp_reg_259");
    sc_trace(mVcdFile, tmp_1_fu_177_p1, "tmp_1_fu_177_p1");
    sc_trace(mVcdFile, p_Result_2_fu_111_p3, "p_Result_2_fu_111_p3");
    sc_trace(mVcdFile, ret_V_cast_cast_fu_101_p1, "ret_V_cast_cast_fu_101_p1");
    sc_trace(mVcdFile, ret_V_fu_124_p2, "ret_V_fu_124_p2");
    sc_trace(mVcdFile, tmp_7_fu_118_p2, "tmp_7_fu_118_p2");
    sc_trace(mVcdFile, tmp_6_fu_130_p1, "tmp_6_fu_130_p1");
    sc_trace(mVcdFile, tmp_s_fu_133_p1, "tmp_s_fu_133_p1");
    sc_trace(mVcdFile, tmp_3_fu_104_p3, "tmp_3_fu_104_p3");
    sc_trace(mVcdFile, tmp_5_fu_137_p3, "tmp_5_fu_137_p3");
    sc_trace(mVcdFile, tmp_10_fu_161_p4, "tmp_10_fu_161_p4");
    sc_trace(mVcdFile, sel_tmp1_fu_181_p2, "sel_tmp1_fu_181_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_186_p2, "sel_tmp2_fu_186_p2");
    sc_trace(mVcdFile, tmp_8_fu_199_p2, "tmp_8_fu_199_p2");
    sc_trace(mVcdFile, sel_tmp_cast_fu_191_p3, "sel_tmp_cast_fu_191_p3");
    sc_trace(mVcdFile, storemerge1_fu_204_p3, "storemerge1_fu_204_p3");
    sc_trace(mVcdFile, grp_fu_217_p0, "grp_fu_217_p0");
    sc_trace(mVcdFile, grp_fu_217_p2, "grp_fu_217_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_pipeline_idle_pp0, "ap_pipeline_idle_pp0");
#endif

    }
    mHdltvinHandle.open("rinvToInvPt.hdltvin.dat");
    mHdltvoutHandle.open("rinvToInvPt.hdltvout.dat");
}

rinvToInvPt::~rinvToInvPt() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete rinvToInvPt_table1_U;
    delete rinvToInvPt_mac_mcud_U1;
}

void rinvToInvPt::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void rinvToInvPt::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_pp0_stage0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
             !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        ap_pipeline_reg_pp0_iter4_icmp_reg_259 = icmp_reg_259.read();
        ap_pipeline_reg_pp0_iter4_tmp_9_reg_253 = tmp_9_reg_253.read();
        icmp_reg_259 = icmp_fu_171_p2.read();
        index_reg_248 = index_fu_145_p3.read();
        tmp_2_reg_237 = grp_fu_217_p3.read().range(31, 8);
        tmp_4_reg_243 = tmp_4_fu_98_p1.read();
        tmp_9_reg_253 = index_fu_145_p3.read().range(31, 31);
    }
    if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        r_V_reg_232 = grp_fu_217_p3.read();
    }
}

void rinvToInvPt::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read().range(0, 0);
}

void rinvToInvPt::thread_ap_done() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void rinvToInvPt::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void rinvToInvPt::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void rinvToInvPt::thread_ap_pipeline_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_pipeline_idle_pp0 = ap_const_logic_1;
    } else {
        ap_pipeline_idle_pp0 = ap_const_logic_0;
    }
}

void rinvToInvPt::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_pp0_stage0.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void rinvToInvPt::thread_grp_fu_217_p0() {
    grp_fu_217_p0 =  (sc_lv<9>) (ap_const_lv32_FFFFFF51);
}

void rinvToInvPt::thread_grp_fu_217_p2() {
    grp_fu_217_p2 =  (sc_lv<24>) (ap_const_lv32_400000);
}

void rinvToInvPt::thread_icmp_fu_171_p2() {
    icmp_fu_171_p2 = (!tmp_10_fu_161_p4.read().is_01() || !ap_const_lv18_0.is_01())? sc_lv<1>(): (sc_bigint<18>(tmp_10_fu_161_p4.read()) > sc_bigint<18>(ap_const_lv18_0));
}

void rinvToInvPt::thread_index_fu_145_p3() {
    index_fu_145_p3 = (!tmp_3_fu_104_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_3_fu_104_p3.read()[0].to_bool())? tmp_5_fu_137_p3.read(): tmp_6_fu_130_p1.read());
}

void rinvToInvPt::thread_p_Result_2_fu_111_p3() {
    p_Result_2_fu_111_p3 = esl_concat<8,14>(tmp_4_reg_243.read(), ap_const_lv14_0);
}

void rinvToInvPt::thread_res_V() {
    res_V = esl_zext<24,21>(storemerge1_fu_204_p3.read());
}

void rinvToInvPt::thread_res_V_ap_vld() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()))) {
        res_V_ap_vld = ap_const_logic_1;
    } else {
        res_V_ap_vld = ap_const_logic_0;
    }
}

void rinvToInvPt::thread_ret_V_cast_cast_fu_101_p1() {
    ret_V_cast_cast_fu_101_p1 = esl_sext<25,24>(tmp_2_reg_237.read());
}

void rinvToInvPt::thread_ret_V_fu_124_p2() {
    ret_V_fu_124_p2 = (!ap_const_lv25_1.is_01() || !ret_V_cast_cast_fu_101_p1.read().is_01())? sc_lv<25>(): (sc_biguint<25>(ap_const_lv25_1) + sc_bigint<25>(ret_V_cast_cast_fu_101_p1.read()));
}

void rinvToInvPt::thread_rinvToInvPt_table1_address0() {
    rinvToInvPt_table1_address0 =  (sc_lv<14>) (tmp_1_fu_177_p1.read());
}

void rinvToInvPt::thread_rinvToInvPt_table1_ce0() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()))) {
        rinvToInvPt_table1_ce0 = ap_const_logic_1;
    } else {
        rinvToInvPt_table1_ce0 = ap_const_logic_0;
    }
}

void rinvToInvPt::thread_sel_tmp1_fu_181_p2() {
    sel_tmp1_fu_181_p2 = (ap_pipeline_reg_pp0_iter4_tmp_9_reg_253.read() ^ ap_const_lv1_1);
}

void rinvToInvPt::thread_sel_tmp2_fu_186_p2() {
    sel_tmp2_fu_186_p2 = (ap_pipeline_reg_pp0_iter4_icmp_reg_259.read() & sel_tmp1_fu_181_p2.read());
}

void rinvToInvPt::thread_sel_tmp_cast_fu_191_p3() {
    sel_tmp_cast_fu_191_p3 = (!sel_tmp2_fu_186_p2.read()[0].is_01())? sc_lv<21>(): ((sel_tmp2_fu_186_p2.read()[0].to_bool())? ap_const_lv21_0: ap_const_lv21_1FFF80);
}

void rinvToInvPt::thread_storemerge1_fu_204_p3() {
    storemerge1_fu_204_p3 = (!tmp_8_fu_199_p2.read()[0].is_01())? sc_lv<21>(): ((tmp_8_fu_199_p2.read()[0].to_bool())? sel_tmp_cast_fu_191_p3.read(): rinvToInvPt_table1_q0.read());
}

void rinvToInvPt::thread_tmp_10_fu_161_p4() {
    tmp_10_fu_161_p4 = index_fu_145_p3.read().range(31, 14);
}

void rinvToInvPt::thread_tmp_1_fu_177_p1() {
    tmp_1_fu_177_p1 = esl_zext<64,32>(index_reg_248.read());
}

void rinvToInvPt::thread_tmp_3_fu_104_p3() {
    tmp_3_fu_104_p3 = r_V_reg_232.read().range(31, 31);
}

void rinvToInvPt::thread_tmp_4_fu_98_p1() {
    tmp_4_fu_98_p1 = grp_fu_217_p3.read().range(8-1, 0);
}

void rinvToInvPt::thread_tmp_5_fu_137_p3() {
    tmp_5_fu_137_p3 = (!tmp_7_fu_118_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_7_fu_118_p2.read()[0].to_bool())? tmp_6_fu_130_p1.read(): tmp_s_fu_133_p1.read());
}

void rinvToInvPt::thread_tmp_6_fu_130_p1() {
    tmp_6_fu_130_p1 = esl_sext<32,24>(tmp_2_reg_237.read());
}

void rinvToInvPt::thread_tmp_7_fu_118_p2() {
    tmp_7_fu_118_p2 = (!p_Result_2_fu_111_p3.read().is_01() || !ap_const_lv22_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_2_fu_111_p3.read() == ap_const_lv22_0);
}

void rinvToInvPt::thread_tmp_8_fu_199_p2() {
    tmp_8_fu_199_p2 = (sel_tmp2_fu_186_p2.read() | ap_pipeline_reg_pp0_iter4_tmp_9_reg_253.read());
}

void rinvToInvPt::thread_tmp_s_fu_133_p1() {
    tmp_s_fu_133_p1 = esl_sext<32,25>(ret_V_fu_124_p2.read());
}

void rinvToInvPt::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

void rinvToInvPt::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"data_V\" :  \"" << data_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_V\" :  \"" << res_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"res_V_ap_vld\" :  \"" << res_V_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

