#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("agg_result_hwRinv_V", 15, hls_out, 0, "ap_vld", "out_data", 1),
	Port_Property("agg_result_hwRinv_V_ap_vld", 1, hls_out, 0, "ap_vld", "out_vld", 1),
	Port_Property("agg_result_hwPt_V", 12, hls_out, 1, "ap_vld", "out_data", 1),
	Port_Property("agg_result_hwPt_V_ap_vld", 1, hls_out, 1, "ap_vld", "out_vld", 1),
	Port_Property("agg_result_hwSinhEta_V", 14, hls_out, 2, "ap_vld", "out_data", 1),
	Port_Property("agg_result_hwSinhEta_V_ap_vld", 1, hls_out, 2, "ap_vld", "out_vld", 1),
	Port_Property("agg_result_hwEta_V", 14, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("agg_result_hwEta_V_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("agg_result_hwPhi_V", 19, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("agg_result_hwPhi_V_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("agg_result_hwZ0_V", 11, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("agg_result_hwZ0_V_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("agg_result_hwQ_V", 1, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("agg_result_hwQ_V_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("agg_result_hwX2_V", 10, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("agg_result_hwX2_V_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
	Port_Property("agg_result_VALID_V", 1, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("agg_result_VALID_V_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("agg_result_hwBX_V", 3, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("agg_result_hwBX_V_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("agg_result_hwPropEta_V", 14, hls_out, 10, "ap_vld", "out_data", 1),
	Port_Property("agg_result_hwPropEta_V_ap_vld", 1, hls_out, 10, "ap_vld", "out_vld", 1),
	Port_Property("agg_result_hwPropPhi_V", 19, hls_out, 11, "ap_vld", "out_data", 1),
	Port_Property("agg_result_hwPropPhi_V_ap_vld", 1, hls_out, 11, "ap_vld", "out_vld", 1),
	Port_Property("in_hwRinv_V", 15, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("in_hwPt_V", 12, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("in_hwSinhEta_V", 14, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("in_hwEta_V", 14, hls_out, 15, "ap_vld", "out_data", 1),
	Port_Property("in_hwEta_V_ap_vld", 1, hls_out, 15, "ap_vld", "out_vld", 1),
	Port_Property("in_hwPhi_V", 19, hls_in, 16, "ap_none", "in_data", 1),
	Port_Property("in_hwZ0_V", 11, hls_in, 17, "ap_none", "in_data", 1),
	Port_Property("in_hwQ_V", 1, hls_in, 18, "ap_none", "in_data", 1),
	Port_Property("in_hwX2_V", 10, hls_in, 19, "ap_none", "in_data", 1),
	Port_Property("in_VALID_V", 1, hls_in, 20, "ap_none", "in_data", 1),
	Port_Property("in_hwBX_V", 3, hls_in, 21, "ap_none", "in_data", 1),
};
const char* HLS_Design_Meta::dut_name = "tkmu_simple_hw";
