// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _rinvToInvPt_HH_
#define _rinvToInvPt_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "prop_hw_mac_muladeOg.h"
#include "rinvToInvPt_rinvTdEe.h"

namespace ap_rtl {

struct rinvToInvPt : public sc_module {
    // Port declarations 8
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<24> > data_V_read;
    sc_out< sc_lv<21> > ap_return;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    rinvToInvPt(sc_module_name name);
    SC_HAS_PROCESS(rinvToInvPt);

    ~rinvToInvPt();

    sc_trace_file* mVcdFile;

    rinvToInvPt_rinvTdEe* rinvToInvPt_table9_U;
    prop_hw_mac_muladeOg<1,3,9,24,24,32>* prop_hw_mac_muladeOg_U4;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter4;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter5;
    sc_signal< sc_lv<14> > rinvToInvPt_table9_address0;
    sc_signal< sc_logic > rinvToInvPt_table9_ce0;
    sc_signal< sc_lv<21> > rinvToInvPt_table9_q0;
    sc_signal< sc_lv<32> > grp_fu_195_p3;
    sc_signal< sc_lv<32> > r_V_reg_210;
    sc_signal< sc_lv<24> > tmp_9_reg_215;
    sc_signal< sc_lv<8> > tmp_17_fu_81_p1;
    sc_signal< sc_lv<8> > tmp_17_reg_221;
    sc_signal< sc_lv<32> > index_fu_128_p3;
    sc_signal< sc_lv<32> > index_reg_226;
    sc_signal< sc_lv<1> > tmp_18_reg_231;
    sc_signal< sc_lv<1> > ap_pipeline_reg_pp0_iter4_tmp_18_reg_231;
    sc_signal< sc_lv<1> > icmp_fu_154_p2;
    sc_signal< sc_lv<1> > icmp_reg_237;
    sc_signal< sc_lv<1> > ap_pipeline_reg_pp0_iter4_icmp_reg_237;
    sc_signal< sc_lv<64> > tmp_8_fu_160_p1;
    sc_signal< sc_lv<22> > p_Result_4_fu_94_p3;
    sc_signal< sc_lv<25> > ret_V_cast_cast_fu_84_p1;
    sc_signal< sc_lv<25> > ret_V_fu_107_p2;
    sc_signal< sc_lv<1> > tmp_5_fu_101_p2;
    sc_signal< sc_lv<32> > tmp_s_fu_113_p1;
    sc_signal< sc_lv<32> > tmp_2_fu_116_p1;
    sc_signal< sc_lv<1> > tmp_16_fu_87_p3;
    sc_signal< sc_lv<32> > tmp_3_fu_120_p3;
    sc_signal< sc_lv<18> > tmp_19_fu_144_p4;
    sc_signal< sc_lv<1> > sel_tmp1_fu_164_p2;
    sc_signal< sc_lv<1> > sel_tmp2_fu_169_p2;
    sc_signal< sc_lv<1> > tmp_1_fu_182_p2;
    sc_signal< sc_lv<21> > sel_tmp_cast_fu_174_p3;
    sc_signal< sc_lv<9> > grp_fu_195_p0;
    sc_signal< sc_lv<24> > grp_fu_195_p2;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    sc_signal< sc_logic > ap_pipeline_idle_pp0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_pp0_stage0;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<14> ap_const_lv14_0;
    static const sc_lv<22> ap_const_lv22_0;
    static const sc_lv<25> ap_const_lv25_1;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<18> ap_const_lv18_0;
    static const sc_lv<21> ap_const_lv21_0;
    static const sc_lv<21> ap_const_lv21_1FFF80;
    static const sc_lv<32> ap_const_lv32_FFFFFF51;
    static const sc_lv<32> ap_const_lv32_400000;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_done();
    void thread_ap_enable_reg_pp0_iter0();
    void thread_ap_idle();
    void thread_ap_pipeline_idle_pp0();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_grp_fu_195_p0();
    void thread_grp_fu_195_p2();
    void thread_icmp_fu_154_p2();
    void thread_index_fu_128_p3();
    void thread_p_Result_4_fu_94_p3();
    void thread_ret_V_cast_cast_fu_84_p1();
    void thread_ret_V_fu_107_p2();
    void thread_rinvToInvPt_table9_address0();
    void thread_rinvToInvPt_table9_ce0();
    void thread_sel_tmp1_fu_164_p2();
    void thread_sel_tmp2_fu_169_p2();
    void thread_sel_tmp_cast_fu_174_p3();
    void thread_tmp_16_fu_87_p3();
    void thread_tmp_17_fu_81_p1();
    void thread_tmp_19_fu_144_p4();
    void thread_tmp_1_fu_182_p2();
    void thread_tmp_2_fu_116_p1();
    void thread_tmp_3_fu_120_p3();
    void thread_tmp_5_fu_101_p2();
    void thread_tmp_8_fu_160_p1();
    void thread_tmp_s_fu_113_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
